// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/mus_heal.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of mus_heal.o: 0xc8 bytes, 5 addresses.
#[repr(C, packed)]
pub struct MUS_HEAL__RODATA_t {
    b0: [u8; 180],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
    p3: Ptr,
    p4: Ptr,
}
#[unsafe(no_mangle)]
pub static MUS_HEAL__RODATA: A4<MUS_HEAL__RODATA_t> = A4(MUS_HEAL__RODATA_t {
    b0: *b"\xbc\x00\xbbB\xbd.\xbeZ\xbf@\xdbSp\x8c\xd5S4\x8c\xdbSp\x8c\xd5S4\x8c\xdbSp\x8cP\x8cX\x8c\xd5X4\x8c\x98\xb1\xbc\x00\xbd.\xbeZ\xbfp\xd5LP\x8cL\x14\x8cLP\x8cL\x14\x8cLP\x8cL\x14\x8cSP\x8cS\x14\x8c\x98\xb1\xbc\x00\xbd.\xbeZ\xbf\x11\x8c\xd5DP\x8cD\x18\x8cDP\x8cD\x18\x8cDP\x8c@\x8c@\x18\x8c\x98\xb1\xbeZ\xbc\x00\xbdd\xbf@\x8c\xd2XP\x86\xbf\x10\xd2X\x18\x86\xbf@\xd2XP\x86\xbfp\xd2X\x18\x86\xbde\xbf@\xd2LP\x86\xbf\x10\xd2L\x18\x9a\xbdd\xbf@\xd2XP\x86\xbfp\xd2X\x18\x92\xbf@\xd2XH\x86X\x1c\x92\xb1\x04\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(7716)),
    p1: Ptr(&raw const MUS_HEAL__RODATA as *const u8),
    p2: Ptr((&raw const MUS_HEAL__RODATA as *const u8).wrapping_add(40)),
    p3: Ptr((&raw const MUS_HEAL__RODATA as *const u8).wrapping_add(75)),
    p4: Ptr((&raw const MUS_HEAL__RODATA as *const u8).wrapping_add(107)),
});

pub const mus_heal: *const u8 = (&raw const MUS_HEAL__RODATA as *const u8).wrapping_add(176);
