// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/mus_obtain_tmhm.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of mus_obtain_tmhm.o: 0x18c bytes, 8 addresses.
#[repr(C, packed)]
pub struct MUS_OBTAIN_TMHM__RODATA_t {
    b0: [u8; 364],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
    p3: Ptr,
    p4: Ptr,
    p5: Ptr,
    p6: Ptr,
    p7: Ptr,
}
#[unsafe(no_mangle)]
pub static MUS_OBTAIN_TMHM__RODATA: A4<MUS_OBTAIN_TMHM__RODATA_t> = A4(MUS_OBTAIN_TMHM__RODATA_t {
    b0: *b"\xbc\x00\x8c\xbbF\xbdI\xbf\x11\xbeZ\xd5J`\x8cC\x86G\x86\xe9J\x8c\xc4\x06\x92\x00\x86\xd5H\x8cJ\x8cL\x8c\xefN\x92\xc4\x06\x86\x98\x98\xb1\xbc\x00\x8c\xbdI\xbf@\xbeZ\xd5Ot\x8cJ\x86O\x86\xe9S\x8c\xc4\x06\x92\x00\x86\xd5Q\x8cS\x8cT\x8c\xefV\x92\xc4\x06\x86\x98\x98\xb1\xbc\x00\x8c\xbd:\xbeZ\xdb+x\x98\xdb\x98)\x98\xdb\x98\xef&\x98\x98\x98\xb1\xbc\x00\x8c\xbdR\xcd\x08\x08\x09\x08\xbf@\xbeZ\xdb>8\x98\xdb\x8c\xd57D\x86;\x86\xdbA8\x98\xe7\x83\xbeO\x83L\x82O\x84P\x82S\x83V\x83Z\x84\xd590\x86>\x86B\x86E\x86\xd7J\x88N\x88Q\x88\xd5V\x98\xb1\xbc\x00\x8c\xbdS\xcd\x08\x08\x09\x08\xbfp\xbeZ\xdb;0\x98\xdb\x8c\xd528\x867\x86\xdb<0\x98\xe7\x83\xbeO\x83L\x82O\x84P\x82S\x83V\x83Z\x84\xc0>\x82\xd59\x18\x86>\x86B\x86E\x84\x82\xd7J\x88N\x88Q\x86\x82\xd5V\x96\xb1\xbc\x00\x8c\xbdW\xbeZ\xbfp\xdb70\x98\xdb\x985\x98\xdb\x98\xeb2\x98\x8c\xdb2\x18\x8c\x98\xb1\xbc\x00\x8c\xbd\x00\xbeZ\xd3(d\x8c\xd3\x84(D\x84\xd3\x84(d\x8c\xd3\x84(H\x84\xd3\x84(d\x8c\xd3\x84(H\x84\xd3\x84(d\x88\xd3\x88\xd3\x88\xd3\x84((\x84\xd3\x84(,\x84\xd3\x84\xd3\x84(H\x84(0\x84(8\x84(<\x84(@\x84\xd4(D\x84\x82(h\x96\xb1\x07\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(7716)),
    p1: Ptr(&raw const MUS_OBTAIN_TMHM__RODATA as *const u8),
    p2: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(43)),
    p3: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(84)),
    p4: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(107)),
    p5: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(175)),
    p6: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(248)),
    p7: Ptr((&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(277)),
});

pub const mus_obtain_tmhm: *const u8 =
    (&raw const MUS_OBTAIN_TMHM__RODATA as *const u8).wrapping_add(360);
