// @generated by tools/rustport/obj2rs.py from build/modern/data/mystery_event_script_cmd_table.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `script_data` of mystery_event_script_cmd_table.o: 0x44 bytes, 17 addresses.
#[repr(C, packed)]
pub struct MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA_t {
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
    p3: Ptr,
    p4: Ptr,
    p5: Ptr,
    p6: Ptr,
    p7: Ptr,
    p8: Ptr,
    p9: Ptr,
    p10: Ptr,
    p11: Ptr,
    p12: Ptr,
    p13: Ptr,
    p14: Ptr,
    p15: Ptr,
    p16: Ptr,
}
#[unsafe(no_mangle)]
pub static MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA: A4<
    MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA_t,
> = A4(MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA_t {
    p0: Ptr(crate::mystery_event_script::MEScrCmd_nop as *const u8),
    p1: Ptr(crate::mystery_event_script::MEScrCmd_checkcompat as *const u8),
    p2: Ptr(crate::mystery_event_script::MEScrCmd_end as *const u8),
    p3: Ptr(crate::mystery_event_script::MEScrCmd_setmsg as *const u8),
    p4: Ptr(crate::mystery_event_script::MEScrCmd_setstatus as *const u8),
    p5: Ptr(crate::mystery_event_script::MEScrCmd_runscript as *const u8),
    p6: Ptr(crate::mystery_event_script::MEScrCmd_initramscript as *const u8),
    p7: Ptr(crate::mystery_event_script::MEScrCmd_setenigmaberry as *const u8),
    p8: Ptr(crate::mystery_event_script::MEScrCmd_giveribbon as *const u8),
    p9: Ptr(crate::mystery_event_script::MEScrCmd_givenationaldex as *const u8),
    p10: Ptr(crate::mystery_event_script::MEScrCmd_addrareword as *const u8),
    p11: Ptr(crate::mystery_event_script::MEScrCmd_setrecordmixinggift as *const u8),
    p12: Ptr(crate::mystery_event_script::MEScrCmd_givepokemon as *const u8),
    p13: Ptr(crate::mystery_event_script::MEScrCmd_addtrainer as *const u8),
    p14: Ptr(crate::mystery_event_script::MEScrCmd_enableresetrtc as *const u8),
    p15: Ptr(crate::mystery_event_script::MEScrCmd_checksum as *const u8),
    p16: Ptr(crate::mystery_event_script::MEScrCmd_crc as *const u8),
});

pub const gMysteryEventScriptCmdTable: *const u8 =
    &raw const MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA as *const u8;
pub const gMysteryEventScriptCmdTableEnd: *const u8 =
    (&raw const MYSTERY_EVENT_SCRIPT_CMD_TABLE__SCRIPT_DATA as *const u8).wrapping_add(68);
