// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/ph_lot_held.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of ph_lot_held.o: 0x24 bytes, 3 addresses.
#[repr(C, packed)]
pub struct PH_LOT_HELD__RODATA_t {
    b0: [u8; 14],
    p0: Ptr,
    b1: [u8; 10],
    p1: Ptr,
    p2: Ptr,
}
#[unsafe(no_mangle)]
pub static PH_LOT_HELD__RODATA: A4<PH_LOT_HELD__RODATA_t> = A4(PH_LOT_HELD__RODATA_t {
    b0: *b"\xbc\x00\xbb<\xbd\x16\xbe\x7f\xcf<\x7f\xb0\xb0\xb2",
    p0: Ptr((&raw const PH_LOT_HELD__RODATA as *const u8).wrapping_add(12)),
    b1: *b"\xa0\xce<\xb1\x00\x00\x01\x00\x04\x00",
    p1: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(174672)),
    p2: Ptr(&raw const PH_LOT_HELD__RODATA as *const u8),
});

pub const ph_lot_held: *const u8 = (&raw const PH_LOT_HELD__RODATA as *const u8).wrapping_add(24);
