// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_ball_throw.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_ball_throw.o: 0x40 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_BALL_THROW__RODATA_t {
    b0: [u8; 56],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_BALL_THROW__RODATA: A4<SE_BALL_THROW__RODATA_t> = A4(SE_BALL_THROW__RODATA_t {
    b0: *b"\xbc\x00\xbbK\xbd\x16\xc1\x0c\xbex\xc0L\xd59\x7f\x83\xbeN\xc0T\x83\xbex\xc0d\xe1<\x82\xc0c\x83`\x82Z\x83\xbef\xc0R\x82\xbeD\xc0G\x83\xbe\x22\xc07\x83\xb1\x00\x01\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_BALL_THROW__RODATA as *const u8),
});

pub const se_ball_throw: *const u8 =
    (&raw const SE_BALL_THROW__RODATA as *const u8).wrapping_add(52);
