// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_bang.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_bang.o: 0x48 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_BANG__RODATA_t {
    b0: [u8; 64],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_BANG__RODATA: A4<SE_BANG__RODATA_t> = A4(SE_BANG__RODATA_t {
    b0: *b"\xbc\x00\xbbx\xbd\x02\xc1\x0c\xben\xc0@\xd24\x7f\x832\x83\xd5+\x86\xf39\x8c\x98\xbe^\xc0;\x83\xbeQ\x83G\xc04\x83\xbe/\x83 \xc0-\x83\xbe\x14\x83\x07\xc0$\x83\xbe\x00\xc0\x1b\x83\xb1\x00\x00\x00\x01\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_BANG__RODATA as *const u8),
});

pub const se_bang: *const u8 = (&raw const SE_BANG__RODATA as *const u8).wrapping_add(60);
