// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_dex_page.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_dex_page.o: 0x34 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_DEX_PAGE__RODATA_t {
    b0: [u8; 44],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_DEX_PAGE__RODATA: A4<SE_DEX_PAGE__RODATA_t> = A4(SE_DEX_PAGE__RODATA_t {
    b0: *b"\xbc\x00\xbb2\xbd\x04\xc1\x0c\xcd\x08\x0a\x09\x08\xbeZ\xc0D\xd0T@\x81T\x14\x81T@\x81T\x14\x81`@\x82`\x14\x83\xb1\x00\x00\x00\x01\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(160752)),
    p1: Ptr(&raw const SE_DEX_PAGE__RODATA as *const u8),
});

pub const se_dex_page: *const u8 = (&raw const SE_DEX_PAGE__RODATA as *const u8).wrapping_add(40);
