// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_door.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_door.o: 0x1c bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_DOOR__RODATA_t {
    b0: [u8; 20],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_DOOR__RODATA: A4<SE_DOOR__RODATA_t> = A4(SE_DOOR__RODATA_t {
    b0: *b"\xbc\x00\xbb7\xbd\x7f\xbeP\xd2>\x7f\x86\xdbB\x92\xb1\x01\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(160752)),
    p1: Ptr(&raw const SE_DOOR__RODATA as *const u8),
});

pub const se_door: *const u8 = (&raw const SE_DOOR__RODATA as *const u8).wrapping_add(16);
