// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_thunderbolt.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_thunderbolt.o: 0x98 bytes, 3 addresses.
#[repr(C, packed)]
pub struct SE_M_THUNDERBOLT__RODATA_t {
    b0: [u8; 140],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_THUNDERBOLT__RODATA: A4<SE_M_THUNDERBOLT__RODATA_t> = A4(SE_M_THUNDERBOLT__RODATA_t {
    b0: *b"\xbc\x00\xbbn\xbd\x12\xbex\xc1\x0c\xbf@\xc0`\xd5>\x7f\x82\xbf8\x81\xc0@\x81\xbf0\x82@\xc0`\xd52h\x82\xbfI\x81\xc04\x81\xbfP\x82@\xc0@\xe4>\x7f\x83\xbf8\x831\x81\xc03\x82\xbf9\x81\xc0)\x82\xbed\xbf@\xc0\x18\x81\xbeV\x81\xc0\x0a\x81\xbfJ\xbeD\x82%\xc0\x00\x81\xbfP\x82\xbe\x11\x81\xbfJ\x8f\xb1\xbc\x00\xbd\x05\xbex\xbf9\xd1@0\x85\xbfJ\xd1@(\x86\xbf9\xd1@ \x87\xbfJ\xd1@\x18\x86\xbf9\xd1@\x10\x98\xb1\x00\x00\x00\x02\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_M_THUNDERBOLT__RODATA as *const u8),
    p2: Ptr((&raw const SE_M_THUNDERBOLT__RODATA as *const u8).wrapping_add(96)),
});

pub const se_m_thunderbolt: *const u8 =
    (&raw const SE_M_THUNDERBOLT__RODATA as *const u8).wrapping_add(136);
