// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_razor_wind.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_razor_wind.o: 0x64 bytes, 3 addresses.
#[repr(C, packed)]
pub struct SE_M_RAZOR_WIND__RODATA_t {
    b0: [u8; 88],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_RAZOR_WIND__RODATA: A4<SE_M_RAZOR_WIND__RODATA_t> = A4(SE_M_RAZOR_WIND__RODATA_t {
    b0: *b"\xbc\x00\xbbn\xbd\x12\xc1\x0c\xbf@\xben\xbfN\xc0@\xd8T\x5c\x83\xbf1\xc0 \x83\xbf@\xc0\x5c\x83\xbd\x02\xc0\x00\xe4;l\x83\xc0\x09\x83\xbfD\xc0\x13\x83\xbf;\xc0^\x83\xbfO\xc0g\x83\xbf1\xc0v\x83\xbf@\xc0\x7f\x95\xb1\xbc\x00\xbd\x05\xbf@\xben\xd5A(\x89\xe7C\x8f\x98\xb1\x02\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_M_RAZOR_WIND__RODATA as *const u8),
    p2: Ptr((&raw const SE_M_RAZOR_WIND__RODATA as *const u8).wrapping_add(67)),
});

pub const se_m_razor_wind: *const u8 =
    (&raw const SE_M_RAZOR_WIND__RODATA as *const u8).wrapping_add(84);
