// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_sketch.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_sketch.o: 0x4c bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_M_SKETCH__RODATA_t {
    b0: [u8; 68],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_SKETCH__RODATA: A4<SE_M_SKETCH__RODATA_t> = A4(SE_M_SKETCH__RODATA_t {
    b0: *b"\xbc\x00\xbbZ\xbd&\xc1\x0c\xbf@\xben\xc0@\xd1O\x7f\x81\xbeJ\xc05\x81\xbd\x1f\xbe(\xc0?\xd2U\x81\xbe@\xbf:\xc04\x81\xbeV\xbfD\xc00\x82\xben\xbf@\xc0@\xd1^\x81\xc0L\x81\xbe\x00\x84\xb1\x00\x00\x01\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_M_SKETCH__RODATA as *const u8),
});

pub const se_m_sketch: *const u8 = (&raw const SE_M_SKETCH__RODATA as *const u8).wrapping_add(64);
