// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_perish_song.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_perish_song.o: 0x110 bytes, 8 addresses.
#[repr(C, packed)]
pub struct SE_M_PERISH_SONG__RODATA_t {
    b0: [u8; 103],
    p0: Ptr,
    b1: [u8; 1],
    p1: Ptr,
    b2: [u8; 1],
    p2: Ptr,
    b3: [u8; 1],
    p3: Ptr,
    b4: [u8; 97],
    p4: Ptr,
    b5: [u8; 37],
    p5: Ptr,
    p6: Ptr,
    p7: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_PERISH_SONG__RODATA: A4<SE_M_PERISH_SONG__RODATA_t> = A4(SE_M_PERISH_SONG__RODATA_t {
    b0: *b"\xbc\x00\xbb2\xbdI\xc1\x0c\xc2(\xbfG\xbe\x19\xc0@\x83\xbe\x1d\x83!\xefEp\x83\xbe(\x81\xbfD\x82\xbe-\xc4\x08\x83\xbe3\x83\xb4\xbe8\xbf@\x83\xbe>\x83\xb4\xbeH\xbf<\x83\xbeQ\x83\xb4\xbe\x5c\xbf8\x83\xbed\x83\xb4\xbf<\x86\xbeR\xbf@\x83\xbe4\x83\x19\xc4\x00\xbfD\x83\xbe\x1d\x81\xbfG\x82\xbe!\xf7Dp\x83\xbe(\x81\xbfD\x82\xb3",
    p0: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(31)),
    b1: *b"\xb3",
    p1: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(40)),
    b2: *b"\xb3",
    p2: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(49)),
    b3: *b"\xb3",
    p3: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(58)),
    b4: *b"\xbf<\x86@\x86D\x83\xbeW\x83K\xbfG\x83\xbe>\x830\xbfD\x83\xbe!\x83\x19\x81\xbf@\x82\xbe\x0a\x83\x81\xbf<\x85\xb1\xbc\x00\xbdI\xbe\x19\xbf/\xefHd\x83\xbe\x1d\x83!\x83(\x83\xbe-\xc4\x08\x83\xbe3\x83\xb48\x83>\x83H\x83Q\x83\x5c\x83d\x83\x86R\x834\x83\x19\xc4\x00\xf7Gd\x83\xbe\x1d\x83!\x83(\x83\xb3",
    p4: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(178)),
    b5: *b"\xbe8\x83>\x83H\x83Q\x83\x5c\x83d\x83\x86\x86\x83W\x83K\x83>\x830\x83!\x83\x19\x83\x0a\x83\x86\xb1\x00\x02\x00\x04\xb2",
    p5: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p6: Ptr(&raw const SE_M_PERISH_SONG__RODATA as *const u8),
    p7: Ptr((&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(159)),
});

pub const se_m_perish_song: *const u8 =
    (&raw const SE_M_PERISH_SONG__RODATA as *const u8).wrapping_add(256);
