// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_encore2.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_encore2.o: 0xd8 bytes, 8 addresses.
#[repr(C, packed)]
pub struct SE_M_ENCORE2__RODATA_t {
    b0: [u8; 110],
    p0: Ptr,
    b1: [u8; 1],
    p1: Ptr,
    b2: [u8; 1],
    p2: Ptr,
    b3: [u8; 1],
    p3: Ptr,
    b4: [u8; 1],
    p4: Ptr,
    b5: [u8; 1],
    p5: Ptr,
    b6: [u8; 69],
    p6: Ptr,
    p7: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_ENCORE2__RODATA: A4<SE_M_ENCORE2__RODATA_t> = A4(SE_M_ENCORE2__RODATA_t {
    b0: *b"\xbc\x00\xbbK\xbd<\xc1\x0c\xbe\x19\xbf@\xc0@\xcf<\x7f\x81\xbfB\x81E\x81\xbe\x22\x81\xbfB\x82@\x81\xbe.\xbf>\x81<\x82\xbe8\xbf>\x82@\x81B\x81E\x81\xbeF\x81\xbfB\x82@\x81\xbeP\xbf>\x81<\x82\xbeX\xbf>\x82@\x81B\x81\xbe`\xbfE\x82B\x82\xbed\xbf@\x81>\x81<\x82>\x82\xbf@\x81B\x81E\x82B\x82@\x81>\x81<\x82>\x82\xb4\xb3",
    p0: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b1: *b"\xb3",
    p1: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b2: *b"\xb3",
    p2: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b3: *b"\xb3",
    p3: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b4: *b"\xb3",
    p4: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b5: *b"\xb3",
    p5: Ptr((&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(91)),
    b6: *b"\xbe`\xbf@\x81B\x81E\x81\xbe\x5c\x81\xbfB\x82@\x81\xbeT\xbf>\x81<\x82\xbeH\xbf>\x82@\x81B\x81\xbe?\xbfE\x82\xbe4\xbfB\x82@\x81\xbe%\xbf>\x81<\x81\xbe\x16\x81\x0c\xbf>\x82\xce<\xb1\x00\x00\x00\x01\x00\x04\xb2",
    p6: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p7: Ptr(&raw const SE_M_ENCORE2__RODATA as *const u8),
});

pub const se_m_encore2: *const u8 =
    (&raw const SE_M_ENCORE2__RODATA as *const u8).wrapping_add(204);
