// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_nightmare.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_nightmare.o: 0xc4 bytes, 3 addresses.
#[repr(C, packed)]
pub struct SE_M_NIGHTMARE__RODATA_t {
    b0: [u8; 184],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_NIGHTMARE__RODATA: A4<SE_M_NIGHTMARE__RODATA_t> = A4(SE_M_NIGHTMARE__RODATA_t {
    b0: *b"\xbc\x00\xbbn\xbd\x03\xben\xc1\x0c\xbf@\xc0@\x86\xd27\x5c\x86\xbf0\xd27X\x89\xbf?\xd2Bh\x83\x83\xbfP\xd2BX\x86\xbf@\xd2?\x86\xbf0\xd2\x89\xbf?\xd29`\x86\xbfQ\xd29X\x89\xbf?\xd2Dh\x86\xbf0\xd2DX\x83\x83\xbf?\xd2A\x86\xbfP\xd2\x8f\xb1\xbc\x00\xbd\x14\xcd\x08\x0a\x09\x08\xben\xbf9\xc0w\xd20d\x86\xbfF\xc0d\xd2\x86\xbf9\xc0Q\xd2\x86\xbfF\xc0B\xd2\x86\xbf9\xc08\xd2\x86\xbfF\xc0L\xd2\x86\xbf9\xc0F\xd2\x86\xbfF\xc0@\xd2\x86\xbf9\xc0:\xd2\x86\xbfF\xc0-\xd2\x86\xbf9\xc0!\xd2\x86\xbfF\xc0\x14\xd2\x86\xbf9\xc0\x09\xd2\x86\xbfF\xc0\x00\xd2\x92\xb1\x02\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_M_NIGHTMARE__RODATA as *const u8),
    p2: Ptr((&raw const SE_M_NIGHTMARE__RODATA as *const u8).wrapping_add(82)),
});

pub const se_m_nightmare: *const u8 =
    (&raw const SE_M_NIGHTMARE__RODATA as *const u8).wrapping_add(180);
