// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_m_encore.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_m_encore.o: 0x34 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_M_ENCORE__RODATA_t {
    b0: [u8; 44],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_M_ENCORE__RODATA: A4<SE_M_ENCORE__RODATA_t> = A4(SE_M_ENCORE__RODATA_t {
    b0: *b"\xbc\x00\xbbK\xbd;\xc1\x0c\xben\xbf@\xc0@\xd5@\x7f\x81\xbfH\x817\x81N\x816\x82@\xd2E0\x81\xbfP\x810\x84\xb1\x00\x00\x01\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_M_ENCORE__RODATA as *const u8),
});

pub const se_m_encore: *const u8 = (&raw const SE_M_ENCORE__RODATA as *const u8).wrapping_add(40);
