// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_not_effective.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_not_effective.o: 0x30 bytes, 3 addresses.
#[repr(C, packed)]
pub struct SE_NOT_EFFECTIVE__RODATA_t {
    b0: [u8; 36],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_NOT_EFFECTIVE__RODATA: A4<SE_NOT_EFFECTIVE__RODATA_t> = A4(SE_NOT_EFFECTIVE__RODATA_t {
    b0: *b"\xbc\x00\xbb-\xbd\x7f\xben\xd27d\x83\xd5:\x83\x83\xb1\xbc\x00\xbd\x00\xben\xd8.\x7f\x83\x83\x83\xb1\x00\x00\x02\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(160752)),
    p1: Ptr(&raw const SE_NOT_EFFECTIVE__RODATA as *const u8),
    p2: Ptr((&raw const SE_NOT_EFFECTIVE__RODATA as *const u8).wrapping_add(17)),
});

pub const se_not_effective: *const u8 =
    (&raw const SE_NOT_EFFECTIVE__RODATA as *const u8).wrapping_add(32);
