// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_puddle.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_puddle.o: 0x30 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_PUDDLE__RODATA_t {
    b0: [u8; 40],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_PUDDLE__RODATA: A4<SE_PUDDLE__RODATA_t> = A4(SE_PUDDLE__RODATA_t {
    b0: *b"\xbc\x00\xbbK\xbd\x17\xbe\x14\xc1\x0c\xbf@\xc0'\xd2Pp\x81\xc07\x81I\x84\x82\xbe\x11\xc0R\xd1P\x7f\x81\xc0b\x83\xb1\x01\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_PUDDLE__RODATA as *const u8),
});

pub const se_puddle: *const u8 = (&raw const SE_PUDDLE__RODATA as *const u8).wrapping_add(36);
