// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_rg_help_error.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_rg_help_error.o: 0x48 bytes, 2 addresses.
#[repr(C, packed)]
pub struct SE_RG_HELP_ERROR__RODATA_t {
    b0: [u8; 64],
    p0: Ptr,
    p1: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_RG_HELP_ERROR__RODATA: A4<SE_RG_HELP_ERROR__RODATA_t> = A4(SE_RG_HELP_ERROR__RODATA_t {
    b0: *b"\xbc\x00\xbb\xd2\xbd\x18\xc2,\xc1\x0c\xbf@\xbe`\xd3Jx\x86\xbf\x00\xd3J \x86\xbf?\xd3N`\x86\xbf\x7f\xd3N \x86\xbd\x5c\xbf@\xbe}\xd3-p\x8a\xc4\x08\x82\xd5-X\x86-\x18\x86\xc4\x00\xb1\x00\x01\x00\x05\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(173136)),
    p1: Ptr(&raw const SE_RG_HELP_ERROR__RODATA as *const u8),
});

pub const se_rg_help_error: *const u8 =
    (&raw const SE_RG_HELP_ERROR__RODATA as *const u8).wrapping_add(60);
