// @generated by tools/rustport/obj2rs.py from build/modern/sound/songs/midi/se_truck_stop.o.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]
#[allow(unused_imports)]
use super::{A4, Ptr, Sec};

/// `.rodata` of se_truck_stop.o: 0x7c bytes, 4 addresses.
#[repr(C, packed)]
pub struct SE_TRUCK_STOP__RODATA_t {
    b0: [u8; 108],
    p0: Ptr,
    p1: Ptr,
    p2: Ptr,
    p3: Ptr,
}
#[unsafe(no_mangle)]
pub static SE_TRUCK_STOP__RODATA: A4<SE_TRUCK_STOP__RODATA_t> = A4(SE_TRUCK_STOP__RODATA_t {
    b0: *b"\xbc\x00\xbbK\xbd\x0a\xbe\x7f\xc0@\xcf=\x7f\x89\xc07\x89.\x86\x89&\x89\x1e\x86\x86\x15\x85\xbe{\x84\xc0\x0a\x82\xbeu\x86n\x81\xc0\x00\x88\xbee\x86Y\x89M\x81\x85<\x890\x86$\x84\x83\x17\x86\x08\x89\x00\x81\xce\x85\xb1\xbc\x00\xbd\x0d\xbeZ\x86\xd8h\x18\x92\x85\xde\x93\x98\x98\x98\x98\xb1\xbc\x00\xbd\x0c\xbeZ\x86\xd8i\x18\x92\x85\xde\x93\x98\x98\x98\x98\xb1\x00\x03\x00\x04\xb2",
    p0: Ptr((&raw const super::sound_data::SOUND_DATA__RODATA as *const u8).wrapping_add(162288)),
    p1: Ptr(&raw const SE_TRUCK_STOP__RODATA as *const u8),
    p2: Ptr((&raw const SE_TRUCK_STOP__RODATA as *const u8).wrapping_add(65)),
    p3: Ptr((&raw const SE_TRUCK_STOP__RODATA as *const u8).wrapping_add(84)),
});

pub const se_truck_stop: *const u8 =
    (&raw const SE_TRUCK_STOP__RODATA as *const u8).wrapping_add(104);
