//! Generated by tools/rustport/gen_consts.py: the constants of include/constants_heal_locations.h
//! that the game code uses.

pub const HEAL_LOCATION_NONE: u8 = 0;
pub const HEAL_LOCATION_PETALBURG_CITY: u8 = 3;
pub const HEAL_LOCATION_EVER_GRANDE_CITY: i32 = 11;
pub const HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE: i32 = 12;
pub const HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE: i32 = 13;
pub const HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE: i32 = 20;
pub const HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR: u8 = 21;
pub const HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST: u8 = 22;
