//! Generated by tools/rustport/gen_consts.py: the constants of include/constants_pokedex.h
//! that the game code uses.

pub const NATIONAL_DEX_NONE: u16 = 0;
pub const NATIONAL_DEX_MEW: u16 = 151;
pub const HOENN_DEX_DEOXYS: u16 = 202;
pub const NATIONAL_DEX_CELEBI: u16 = 251;
pub const NATIONAL_DEX_DEOXYS: u16 = 386;
