//! Generated by tools/rustport/gen_consts.py: the constants of include/menu_helpers.h
//! that the game code uses.

pub const MENU_L_PRESSED: u8 = 1;
pub const MENU_R_PRESSED: u8 = 2;
pub const SWAP_LINE_HAS_MARGIN: u8 = 128;
