//! Generated by tools/rustport/gen_consts.py: the constants of include/sprite.h
//! that the game code uses.

pub const SUBSPRITES_OFF: u8 = 0;
pub const SUBSPRITES_ON: u8 = 1;
pub const SUBSPRITES_IGNORE_PRIORITY: u8 = 2;
pub const MAX_SPRITES: u8 = 64;
pub const SPRITE_NONE: u8 = 255;
pub const NO_ANCHOR: i16 = 2048;
pub const AFFINEANIMCMDTYPE_LOOP: i16 = 0x7ffd;
pub const AFFINEANIMCMDTYPE_JUMP: i16 = 0x7ffe;
pub const AFFINEANIMCMDTYPE_END: i16 = 0x7fff;
pub const TAG_NONE: u16 = 0xffff;
