//! Generated by tools/rustport/gen_types.py from include/battle_anim.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct BattleAnimBgData`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct BattleAnimBgData {
    pub bgTiles: *mut u8,
    pub bgTilemap: *mut u16,
    pub paletteId: u8,
    pub bgId: u8,
    pub tilesOffset: u16,
    pub unused: u16,
}

unsafe impl Sync for BattleAnimBgData {}

/// `struct BattleAnimBackground`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct BattleAnimBackground {
    pub image: *mut u32,
    pub palette: *mut u32,
    pub tilemap: *mut u32,
}

unsafe impl Sync for BattleAnimBackground {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<BattleAnimBgData>() == 16);
    assert!(offset_of!(BattleAnimBgData, bgTiles) == 0);
    assert!(offset_of!(BattleAnimBgData, bgTilemap) == 4);
    assert!(offset_of!(BattleAnimBgData, paletteId) == 8);
    assert!(offset_of!(BattleAnimBgData, bgId) == 9);
    assert!(offset_of!(BattleAnimBgData, tilesOffset) == 10);
    assert!(offset_of!(BattleAnimBgData, unused) == 12);
    assert!(size_of::<BattleAnimBackground>() == 12);
    assert!(offset_of!(BattleAnimBackground, image) == 0);
    assert!(offset_of!(BattleAnimBackground, palette) == 4);
    assert!(offset_of!(BattleAnimBackground, tilemap) == 8);
};
