//! Generated by tools/rustport/gen_types.py from include/battle_message.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct BattleMsgData`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct BattleMsgData {
    pub currentMove: u16,
    pub originallyUsedMove: u16,
    pub lastItem: u16,
    pub lastAbility: u8,
    pub scrActive: u8,
    pub bakScriptPartyIdx: u8,
    pub hpScale: u8,
    pub itemEffectBattler: u8,
    pub moveType: u8,
    pub abilities: CArray<u8, 4>,
    pub textBuffs: CArray<CArray<u8, 16>, 3>,
}

unsafe impl Sync for BattleMsgData {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<BattleMsgData>() == 64);
    assert!(offset_of!(BattleMsgData, currentMove) == 0);
    assert!(offset_of!(BattleMsgData, originallyUsedMove) == 2);
    assert!(offset_of!(BattleMsgData, lastItem) == 4);
    assert!(offset_of!(BattleMsgData, lastAbility) == 6);
    assert!(offset_of!(BattleMsgData, scrActive) == 7);
    assert!(offset_of!(BattleMsgData, bakScriptPartyIdx) == 8);
    assert!(offset_of!(BattleMsgData, hpScale) == 9);
    assert!(offset_of!(BattleMsgData, itemEffectBattler) == 10);
    assert!(offset_of!(BattleMsgData, moveType) == 11);
    assert!(offset_of!(BattleMsgData, abilities) == 12);
    assert!(offset_of!(BattleMsgData, textBuffs) == 16);
};
