//! Generated by tools/rustport/gen_types.py from include/berry.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct BerryCrushBerryData`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct BerryCrushBerryData {
    pub difficulty: u8,
    pub powder: u16,
}

unsafe impl Sync for BerryCrushBerryData {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<BerryCrushBerryData>() == 4);
    assert!(offset_of!(BerryCrushBerryData, difficulty) == 0);
    assert!(offset_of!(BerryCrushBerryData, powder) == 2);
};
