//! Generated by tools/rustport/gen_types.py from include/pokenav.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct PokenavMonListItem`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct PokenavMonListItem {
    pub boxId: u8,
    pub monId: u8,
    pub data: u16,
}

unsafe impl Sync for PokenavMonListItem {}

/// `struct PokenavMatchCallEntry`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct PokenavMatchCallEntry {
    pub isSpecialTrainer: u8,
    pub mapSec: u8,
    pub headerId: u16,
}

unsafe impl Sync for PokenavMatchCallEntry {}

/// `struct PokenavListItem`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PokenavListItem {
    pub item: PokenavListItem_item,
}

unsafe impl Sync for PokenavListItem {}

/// `struct PokenavListTemplate`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PokenavListTemplate {
    pub list: *mut PokenavListItem,
    pub count: u16,
    pub startIndex: u16,
    pub itemSize: u8,
    pub item_X: u8,
    pub windowWidth: u8,
    pub listTop: u8,
    pub maxShowed: u8,
    pub fillValue: u8,
    pub fontId: u8,
    pub bufferItemFunc: Option<unsafe extern "C" fn(*mut PokenavListItem, *mut u8)>,
    pub iconDrawFunc: Option<unsafe extern "C" fn(u16, u32, u32)>,
}

unsafe impl Sync for PokenavListTemplate {}

/// `struct PokenavMonList`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PokenavMonList {
    pub listCount: u16,
    pub currIndex: u16,
    pub monData: CArray<PokenavMonListItem, 426>,
}

unsafe impl Sync for PokenavMonList {}

/// The anonymous type of `PokenavListItem::item`.
#[repr(C)]
#[derive(Clone, Copy)]
pub union PokenavListItem_item {
    pub mon: PokenavMonListItem,
    pub call: PokenavMatchCallEntry,
}

unsafe impl Sync for PokenavListItem_item {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<PokenavMonListItem>() == 4);
    assert!(offset_of!(PokenavMonListItem, boxId) == 0);
    assert!(offset_of!(PokenavMonListItem, monId) == 1);
    assert!(offset_of!(PokenavMonListItem, data) == 2);
    assert!(size_of::<PokenavMatchCallEntry>() == 4);
    assert!(offset_of!(PokenavMatchCallEntry, isSpecialTrainer) == 0);
    assert!(offset_of!(PokenavMatchCallEntry, mapSec) == 1);
    assert!(offset_of!(PokenavMatchCallEntry, headerId) == 2);
    assert!(size_of::<PokenavListItem>() == 4);
    assert!(offset_of!(PokenavListItem, item) == 0);
    assert!(size_of::<PokenavListTemplate>() == 24);
    assert!(offset_of!(PokenavListTemplate, list) == 0);
    assert!(offset_of!(PokenavListTemplate, count) == 4);
    assert!(offset_of!(PokenavListTemplate, startIndex) == 6);
    assert!(offset_of!(PokenavListTemplate, itemSize) == 8);
    assert!(offset_of!(PokenavListTemplate, item_X) == 9);
    assert!(offset_of!(PokenavListTemplate, windowWidth) == 10);
    assert!(offset_of!(PokenavListTemplate, listTop) == 11);
    assert!(offset_of!(PokenavListTemplate, maxShowed) == 12);
    assert!(offset_of!(PokenavListTemplate, fillValue) == 13);
    assert!(offset_of!(PokenavListTemplate, fontId) == 14);
    assert!(offset_of!(PokenavListTemplate, bufferItemFunc) == 16);
    assert!(offset_of!(PokenavListTemplate, iconDrawFunc) == 20);
    assert!(size_of::<PokenavMonList>() == 1708);
    assert!(offset_of!(PokenavMonList, listCount) == 0);
    assert!(offset_of!(PokenavMonList, currIndex) == 2);
    assert!(offset_of!(PokenavMonList, monData) == 4);
    assert!(size_of::<PokenavListItem_item>() == 4);
};
