// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

unsafe extern "C" {
    static BattlePyramid_Text_EightItemsRemaining1: u8;
    static BattlePyramid_Text_EightItemsRemaining2: u8;
    static BattlePyramid_Text_EightItemsRemaining3: u8;
    static BattlePyramid_Text_EightItemsRemaining4: u8;
    static BattlePyramid_Text_EightItemsRemaining5: u8;
    static BattlePyramid_Text_EightItemsRemaining6: u8;
    static BattlePyramid_Text_ExitHintDown1: u8;
    static BattlePyramid_Text_ExitHintDown2: u8;
    static BattlePyramid_Text_ExitHintDown3: u8;
    static BattlePyramid_Text_ExitHintDown4: u8;
    static BattlePyramid_Text_ExitHintDown5: u8;
    static BattlePyramid_Text_ExitHintDown6: u8;
    static BattlePyramid_Text_ExitHintLeft1: u8;
    static BattlePyramid_Text_ExitHintLeft2: u8;
    static BattlePyramid_Text_ExitHintLeft3: u8;
    static BattlePyramid_Text_ExitHintLeft4: u8;
    static BattlePyramid_Text_ExitHintLeft5: u8;
    static BattlePyramid_Text_ExitHintLeft6: u8;
    static BattlePyramid_Text_ExitHintRight1: u8;
    static BattlePyramid_Text_ExitHintRight2: u8;
    static BattlePyramid_Text_ExitHintRight3: u8;
    static BattlePyramid_Text_ExitHintRight4: u8;
    static BattlePyramid_Text_ExitHintRight5: u8;
    static BattlePyramid_Text_ExitHintRight6: u8;
    static BattlePyramid_Text_ExitHintUp1: u8;
    static BattlePyramid_Text_ExitHintUp2: u8;
    static BattlePyramid_Text_ExitHintUp3: u8;
    static BattlePyramid_Text_ExitHintUp4: u8;
    static BattlePyramid_Text_ExitHintUp5: u8;
    static BattlePyramid_Text_ExitHintUp6: u8;
    static BattlePyramid_Text_FiveItemsRemaining1: u8;
    static BattlePyramid_Text_FiveItemsRemaining2: u8;
    static BattlePyramid_Text_FiveItemsRemaining3: u8;
    static BattlePyramid_Text_FiveItemsRemaining4: u8;
    static BattlePyramid_Text_FiveItemsRemaining5: u8;
    static BattlePyramid_Text_FiveItemsRemaining6: u8;
    static BattlePyramid_Text_FiveTrainersRemaining1: u8;
    static BattlePyramid_Text_FiveTrainersRemaining2: u8;
    static BattlePyramid_Text_FiveTrainersRemaining3: u8;
    static BattlePyramid_Text_FiveTrainersRemaining4: u8;
    static BattlePyramid_Text_FiveTrainersRemaining5: u8;
    static BattlePyramid_Text_FiveTrainersRemaining6: u8;
    static BattlePyramid_Text_FourItemsRemaining1: u8;
    static BattlePyramid_Text_FourItemsRemaining2: u8;
    static BattlePyramid_Text_FourItemsRemaining3: u8;
    static BattlePyramid_Text_FourItemsRemaining4: u8;
    static BattlePyramid_Text_FourItemsRemaining5: u8;
    static BattlePyramid_Text_FourItemsRemaining6: u8;
    static BattlePyramid_Text_FourTrainersRemaining1: u8;
    static BattlePyramid_Text_FourTrainersRemaining2: u8;
    static BattlePyramid_Text_FourTrainersRemaining3: u8;
    static BattlePyramid_Text_FourTrainersRemaining4: u8;
    static BattlePyramid_Text_FourTrainersRemaining5: u8;
    static BattlePyramid_Text_FourTrainersRemaining6: u8;
    static BattlePyramid_Text_OneItemRemaining1: u8;
    static BattlePyramid_Text_OneItemRemaining2: u8;
    static BattlePyramid_Text_OneItemRemaining3: u8;
    static BattlePyramid_Text_OneItemRemaining4: u8;
    static BattlePyramid_Text_OneItemRemaining5: u8;
    static BattlePyramid_Text_OneItemRemaining6: u8;
    static BattlePyramid_Text_OneTrainersRemaining1: u8;
    static BattlePyramid_Text_OneTrainersRemaining2: u8;
    static BattlePyramid_Text_OneTrainersRemaining3: u8;
    static BattlePyramid_Text_OneTrainersRemaining4: u8;
    static BattlePyramid_Text_OneTrainersRemaining5: u8;
    static BattlePyramid_Text_OneTrainersRemaining6: u8;
    static BattlePyramid_Text_SevenItemsRemaining1: u8;
    static BattlePyramid_Text_SevenItemsRemaining2: u8;
    static BattlePyramid_Text_SevenItemsRemaining3: u8;
    static BattlePyramid_Text_SevenItemsRemaining4: u8;
    static BattlePyramid_Text_SevenItemsRemaining5: u8;
    static BattlePyramid_Text_SevenItemsRemaining6: u8;
    static BattlePyramid_Text_SevenTrainersRemaining1: u8;
    static BattlePyramid_Text_SevenTrainersRemaining2: u8;
    static BattlePyramid_Text_SevenTrainersRemaining3: u8;
    static BattlePyramid_Text_SevenTrainersRemaining4: u8;
    static BattlePyramid_Text_SevenTrainersRemaining5: u8;
    static BattlePyramid_Text_SevenTrainersRemaining6: u8;
    static BattlePyramid_Text_SixItemsRemaining1: u8;
    static BattlePyramid_Text_SixItemsRemaining2: u8;
    static BattlePyramid_Text_SixItemsRemaining3: u8;
    static BattlePyramid_Text_SixItemsRemaining4: u8;
    static BattlePyramid_Text_SixItemsRemaining5: u8;
    static BattlePyramid_Text_SixItemsRemaining6: u8;
    static BattlePyramid_Text_SixTrainersRemaining1: u8;
    static BattlePyramid_Text_SixTrainersRemaining2: u8;
    static BattlePyramid_Text_SixTrainersRemaining3: u8;
    static BattlePyramid_Text_SixTrainersRemaining4: u8;
    static BattlePyramid_Text_SixTrainersRemaining5: u8;
    static BattlePyramid_Text_SixTrainersRemaining6: u8;
    static BattlePyramid_Text_ThreeItemsRemaining1: u8;
    static BattlePyramid_Text_ThreeItemsRemaining2: u8;
    static BattlePyramid_Text_ThreeItemsRemaining3: u8;
    static BattlePyramid_Text_ThreeItemsRemaining4: u8;
    static BattlePyramid_Text_ThreeItemsRemaining5: u8;
    static BattlePyramid_Text_ThreeItemsRemaining6: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining1: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining2: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining3: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining4: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining5: u8;
    static BattlePyramid_Text_ThreeTrainersRemaining6: u8;
    static BattlePyramid_Text_TwoItemsRemaining1: u8;
    static BattlePyramid_Text_TwoItemsRemaining2: u8;
    static BattlePyramid_Text_TwoItemsRemaining3: u8;
    static BattlePyramid_Text_TwoItemsRemaining4: u8;
    static BattlePyramid_Text_TwoItemsRemaining5: u8;
    static BattlePyramid_Text_TwoItemsRemaining6: u8;
    static BattlePyramid_Text_TwoTrainersRemaining1: u8;
    static BattlePyramid_Text_TwoTrainersRemaining2: u8;
    static BattlePyramid_Text_TwoTrainersRemaining3: u8;
    static BattlePyramid_Text_TwoTrainersRemaining4: u8;
    static BattlePyramid_Text_TwoTrainersRemaining5: u8;
    static BattlePyramid_Text_TwoTrainersRemaining6: u8;
    static BattlePyramid_Text_ZeroItemsRemaining1: u8;
    static BattlePyramid_Text_ZeroItemsRemaining2: u8;
    static BattlePyramid_Text_ZeroItemsRemaining3: u8;
    static BattlePyramid_Text_ZeroItemsRemaining4: u8;
    static BattlePyramid_Text_ZeroItemsRemaining5: u8;
    static BattlePyramid_Text_ZeroItemsRemaining6: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining1: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining2: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining3: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining4: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining5: u8;
    static BattlePyramid_Text_ZeroTrainersRemaining6: u8;
}

pub(crate) static sLevel50WildMons_Round1: RomBytes<96> = RomBytes([97, 1, 35, 2, 86, 0, 209, 0, 227, 0, 0, 0, 98, 1, 35, 2, 86, 0, 85, 0, 98, 0, 0, 0, 25, 0, 37, 2, 86, 0, 85, 0, 21, 0, 0, 0, 125, 0, 37, 2, 9, 0, 129, 0, 103, 0, 0, 0, 45, 0, 39, 2, 78, 0, 202, 0, 182, 0, 0, 0, 82, 1, 39, 2, 86, 0, 87, 0, 98, 0, 0, 0, 51, 1, 40, 2, 78, 0, 8, 1, 202, 0, 183, 0, 135, 0, 40, 2, 86, 0, 87, 0, 42, 0, 98, 0]);

pub(crate) static sLevel50WildMons_Round2: RomBytes<96> = RomBytes([111, 1, 36, 2, 92, 0, 124, 0, 182, 0, 0, 0, 107, 1, 36, 2, 92, 0, 202, 0, 89, 1, 80, 0, 12, 0, 38, 2, 77, 0, 16, 0, 60, 0, 0, 0, 123, 1, 38, 2, 49, 1, 207, 0, 242, 0, 86, 1, 227, 0, 40, 2, 92, 0, 19, 0, 211, 0, 0, 0, 41, 1, 40, 1, 92, 0, 182, 0, 35, 1, 240, 0, 169, 0, 41, 2, 92, 0, 109, 0, 212, 0, 44, 0, 94, 0, 41, 2, 92, 0, 69, 1, 101, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round3: RomBytes<96> = RomBytes([58, 0, 37, 2, 172, 0, 36, 0, 0, 0, 0, 0, 37, 0, 37, 2, 5, 1, 53, 0, 0, 0, 0, 0, 219, 0, 39, 1, 53, 0, 157, 0, 182, 0, 0, 0, 38, 0, 39, 2, 5, 1, 98, 0, 53, 0, 0, 0, 101, 1, 41, 2, 7, 0, 136, 0, 0, 0, 0, 0, 110, 0, 41, 2, 5, 1, 53, 0, 182, 0, 0, 0, 106, 1, 42, 2, 5, 1, 109, 0, 212, 0, 69, 1, 229, 0, 42, 2, 53, 0, 44, 0, 76, 0, 59, 1]);

pub(crate) static sLevel50WildMons_Round4: RomBytes<96> = RomBytes([206, 0, 42, 2, 180, 0, 92, 0, 182, 0, 0, 0, 122, 1, 41, 2, 32, 1, 5, 1, 101, 0, 0, 0, 200, 0, 42, 2, 32, 1, 180, 0, 247, 0, 0, 0, 38, 0, 42, 2, 32, 1, 5, 1, 59, 1, 0, 0, 120, 1, 44, 2, 44, 0, 76, 1, 247, 0, 182, 0, 106, 1, 44, 2, 5, 1, 182, 0, 92, 0, 247, 0, 47, 1, 45, 2, 32, 1, 92, 0, 180, 0, 0, 0, 94, 0, 45, 2, 32, 1, 180, 0, 101, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round5: RomBytes<96> = RomBytes([93, 0, 41, 2, 101, 0, 85, 0, 188, 0, 0, 0, 155, 1, 41, 2, 38, 0, 92, 0, 94, 0, 182, 0, 93, 1, 42, 2, 89, 0, 157, 0, 126, 0, 92, 0, 200, 0, 42, 2, 94, 0, 180, 0, 247, 0, 220, 0, 63, 1, 44, 2, 89, 0, 246, 0, 120, 0, 94, 0, 110, 0, 44, 2, 188, 0, 120, 0, 182, 0, 0, 0, 78, 1, 45, 2, 89, 0, 242, 0, 81, 1, 225, 0, 94, 0, 45, 2, 85, 0, 94, 0, 202, 0, 101, 0]);

pub(crate) static sLevel50WildMons_Round6: RomBytes<96> = RomBytes([50, 0, 41, 2, 157, 0, 163, 0, 91, 0, 0, 0, 76, 1, 41, 2, 157, 0, 89, 0, 202, 0, 0, 0, 104, 1, 42, 0, 194, 0, 150, 0, 68, 0, 243, 0, 50, 0, 42, 2, 89, 0, 157, 0, 222, 0, 92, 0, 76, 1, 44, 2, 157, 0, 89, 0, 202, 0, 182, 0, 104, 1, 44, 0, 68, 0, 243, 0, 194, 0, 0, 0, 202, 0, 45, 0, 68, 0, 243, 0, 194, 0, 0, 0, 51, 0, 45, 1, 157, 0, 188, 0, 89, 0, 182, 0]);

pub(crate) static sLevel50WildMons_Round7: RomBytes<96> = RomBytes([91, 1, 41, 2, 58, 0, 242, 0, 182, 0, 0, 0, 215, 0, 41, 2, 58, 0, 50, 1, 180, 0, 0, 0, 87, 0, 42, 2, 59, 0, 38, 0, 57, 0, 0, 0, 221, 0, 42, 2, 58, 0, 89, 0, 92, 0, 0, 0, 124, 0, 44, 2, 59, 0, 142, 0, 94, 0, 0, 0, 91, 0, 44, 2, 58, 0, 57, 0, 182, 0, 0, 0, 87, 1, 45, 2, 59, 0, 34, 0, 57, 0, 0, 0, 131, 0, 45, 2, 47, 0, 34, 0, 58, 0, 94, 0]);

pub(crate) static sLevel50WildMons_Round8: RomBytes<96> = RomBytes([110, 0, 41, 2, 120, 0, 188, 0, 126, 0, 0, 0, 101, 0, 41, 2, 120, 0, 85, 0, 205, 0, 0, 0, 94, 0, 42, 2, 194, 0, 122, 0, 247, 0, 0, 0, 76, 0, 42, 2, 120, 0, 182, 0, 89, 0, 0, 0, 204, 0, 44, 2, 153, 0, 38, 0, 202, 0, 0, 0, 93, 1, 44, 2, 153, 0, 83, 0, 149, 0, 0, 0, 205, 0, 45, 2, 153, 0, 92, 0, 157, 0, 0, 0, 44, 1, 45, 2, 153, 0, 202, 0, 76, 0, 182, 0]);

pub(crate) static sLevel50WildMons_Round9: RomBytes<96> = RomBytes([202, 0, 41, 2, 68, 0, 243, 0, 219, 0, 194, 0, 143, 1, 41, 2, 89, 0, 92, 0, 188, 0, 94, 0, 103, 0, 42, 2, 121, 0, 94, 0, 95, 0, 0, 0, 199, 0, 42, 2, 247, 0, 57, 0, 58, 0, 53, 0, 178, 0, 44, 2, 109, 0, 247, 0, 94, 0, 211, 0, 65, 0, 44, 2, 94, 0, 7, 0, 8, 0, 92, 0, 121, 0, 45, 2, 94, 0, 85, 0, 57, 0, 58, 0, 196, 0, 45, 2, 94, 0, 91, 0, 247, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round10: RomBytes<96> = RomBytes([76, 0, 41, 2, 120, 0, 89, 0, 182, 0, 0, 0, 208, 0, 41, 2, 231, 0, 242, 0, 89, 0, 0, 0, 139, 0, 42, 2, 57, 0, 85, 1, 246, 0, 0, 0, 92, 1, 42, 2, 95, 0, 149, 0, 153, 0, 0, 0, 213, 0, 44, 2, 92, 0, 182, 0, 35, 0, 0, 0, 135, 1, 44, 2, 246, 0, 182, 0, 76, 1, 0, 0, 133, 1, 45, 2, 188, 0, 202, 0, 109, 0, 0, 0, 142, 0, 45, 2, 63, 0, 157, 0, 44, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round11: RomBytes<96> = RomBytes([62, 0, 41, 2, 66, 0, 8, 1, 57, 0, 0, 0, 80, 1, 41, 2, 252, 0, 57, 0, 8, 1, 0, 0, 51, 1, 42, 2, 147, 0, 8, 1, 182, 0, 0, 0, 101, 1, 42, 2, 9, 0, 7, 0, 8, 0, 8, 1, 107, 0, 44, 2, 9, 0, 7, 0, 8, 0, 8, 1, 106, 0, 44, 2, 25, 0, 8, 1, 0, 0, 0, 0, 214, 0, 45, 2, 224, 0, 89, 0, 8, 1, 157, 0, 68, 0, 50, 2, 157, 0, 89, 0, 8, 1, 69, 0]);

pub(crate) static sLevel50WildMons_Round12: RomBytes<96> = RomBytes([195, 0, 41, 2, 240, 0, 57, 0, 182, 0, 0, 0, 113, 1, 41, 2, 241, 0, 76, 0, 0, 0, 0, 0, 247, 0, 42, 2, 201, 0, 89, 0, 157, 0, 0, 0, 131, 0, 42, 2, 2, 1, 58, 0, 0, 0, 0, 0, 89, 1, 44, 2, 201, 0, 202, 0, 76, 0, 0, 0, 136, 0, 44, 2, 241, 0, 53, 0, 182, 0, 0, 0, 87, 1, 45, 2, 2, 1, 58, 0, 0, 0, 0, 0, 130, 0, 50, 2, 240, 0, 87, 0, 56, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round13: RomBytes<96> = RomBytes([204, 0, 42, 2, 153, 0, 36, 0, 0, 0, 0, 0, 213, 0, 42, 2, 92, 0, 89, 0, 182, 0, 0, 0, 49, 0, 46, 2, 62, 1, 77, 0, 79, 0, 94, 0, 212, 0, 46, 2, 98, 0, 232, 0, 210, 0, 228, 0, 214, 0, 48, 2, 224, 0, 24, 1, 89, 0, 157, 0, 205, 0, 48, 2, 153, 0, 89, 0, 182, 0, 0, 0, 135, 1, 50, 2, 96, 1, 182, 0, 157, 0, 0, 0, 47, 1, 50, 2, 247, 0, 92, 0, 180, 0, 32, 1]);

pub(crate) static sLevel50WildMons_Round14: RomBytes<96> = RomBytes([66, 1, 42, 2, 101, 0, 94, 0, 76, 1, 0, 0, 215, 0, 42, 2, 58, 0, 13, 1, 185, 0, 98, 0, 71, 1, 46, 2, 152, 0, 58, 0, 57, 0, 0, 0, 44, 1, 46, 2, 153, 0, 247, 0, 76, 1, 202, 0, 89, 1, 48, 2, 92, 0, 202, 0, 46, 1, 0, 0, 120, 1, 48, 2, 44, 0, 182, 0, 163, 0, 0, 0, 229, 0, 50, 2, 59, 1, 242, 0, 247, 0, 182, 0, 197, 0, 50, 2, 94, 0, 247, 0, 231, 0, 98, 0]);

pub(crate) static sLevel50WildMons_Round15: RomBytes<96> = RomBytes([224, 0, 42, 2, 190, 0, 58, 0, 126, 0, 0, 0, 87, 0, 42, 2, 96, 1, 58, 0, 29, 0, 0, 0, 54, 1, 46, 2, 182, 0, 48, 0, 57, 0, 0, 0, 195, 0, 46, 2, 89, 0, 61, 1, 57, 0, 0, 0, 41, 1, 48, 2, 182, 0, 76, 0, 92, 0, 58, 0, 199, 0, 48, 2, 94, 0, 29, 0, 207, 0, 0, 0, 121, 0, 50, 2, 96, 1, 85, 0, 109, 0, 59, 0, 9, 0, 50, 2, 56, 0, 44, 0, 58, 0, 0, 0]);

pub(crate) static sLevel50WildMons_Round16: RomBytes<96> = RomBytes([105, 1, 42, 2, 101, 0, 5, 1, 247, 0, 182, 0, 93, 0, 42, 2, 92, 0, 180, 0, 95, 0, 247, 0, 122, 1, 46, 2, 247, 0, 180, 0, 5, 1, 0, 0, 200, 0, 46, 2, 195, 0, 180, 0, 212, 0, 0, 0, 66, 1, 48, 2, 247, 0, 212, 0, 91, 0, 101, 0, 106, 1, 48, 2, 5, 1, 92, 0, 247, 0, 0, 0, 47, 1, 50, 2, 247, 0, 180, 0, 32, 1, 182, 0, 94, 0, 50, 2, 94, 0, 194, 0, 180, 0, 101, 0]);

pub(crate) static sLevel50WildMons_Round17: RomBytes<96> = RomBytes([99, 1, 42, 2, 242, 0, 92, 0, 58, 0, 0, 0, 82, 0, 42, 2, 85, 0, 86, 0, 0, 0, 0, 0, 208, 0, 46, 2, 88, 0, 38, 0, 89, 0, 0, 0, 212, 0, 46, 2, 232, 0, 163, 0, 0, 0, 0, 0, 205, 0, 48, 2, 153, 0, 92, 0, 0, 0, 0, 0, 227, 0, 48, 2, 211, 0, 92, 0, 19, 0, 182, 0, 128, 1, 50, 2, 89, 0, 36, 0, 57, 0, 58, 0, 144, 1, 50, 2, 89, 0, 94, 0, 247, 0, 24, 1]);

pub(crate) static sLevel50WildMons_Round18: RomBytes<96> = RomBytes([148, 0, 42, 2, 86, 0, 92, 0, 58, 0, 0, 0, 77, 1, 42, 2, 89, 0, 225, 0, 242, 0, 211, 0, 103, 1, 46, 2, 89, 0, 81, 1, 47, 0, 182, 0, 78, 1, 46, 2, 89, 0, 81, 1, 126, 0, 0, 0, 142, 0, 48, 2, 89, 0, 157, 0, 81, 1, 0, 0, 130, 0, 48, 2, 89, 0, 57, 0, 37, 0, 44, 0, 230, 0, 50, 2, 56, 0, 58, 0, 182, 0, 0, 0, 6, 0, 50, 2, 53, 0, 8, 1, 126, 0, 231, 0]);

pub(crate) static sLevel50WildMons_Round19: RomBytes<96> = RomBytes([59, 0, 42, 2, 126, 0, 36, 0, 0, 0, 0, 0, 62, 0, 42, 2, 56, 0, 58, 0, 0, 0, 0, 0, 26, 0, 46, 2, 87, 0, 86, 0, 21, 0, 0, 0, 134, 0, 46, 2, 57, 0, 58, 0, 0, 0, 0, 0, 135, 0, 48, 2, 85, 0, 42, 0, 0, 0, 0, 0, 136, 0, 48, 2, 53, 0, 44, 0, 0, 0, 0, 0, 38, 0, 50, 2, 53, 0, 5, 1, 182, 0, 0, 0, 121, 0, 50, 2, 58, 0, 57, 0, 85, 0, 94, 0]);

pub(crate) static sLevel50WildMons_Round20: RomBytes<96> = RomBytes([115, 0, 42, 2, 63, 0, 53, 0, 57, 0, 146, 0, 49, 1, 42, 2, 76, 1, 63, 0, 92, 0, 0, 0, 217, 0, 46, 2, 63, 0, 89, 0, 8, 1, 182, 0, 233, 0, 46, 2, 60, 0, 63, 0, 247, 0, 58, 0, 128, 0, 48, 2, 89, 0, 63, 0, 57, 0, 85, 0, 22, 0, 48, 2, 63, 0, 19, 0, 119, 0, 182, 0, 143, 0, 50, 2, 63, 0, 34, 0, 247, 0, 89, 0, 110, 1, 50, 2, 63, 0, 89, 0, 247, 0, 58, 0]);

pub(crate) static sLevel50WildMonPointers: [RomPtr<u8>; 20] = [
    RomPtr(sLevel50WildMons_Round1.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round2.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round3.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round4.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round5.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round6.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round7.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round8.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round9.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round10.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round11.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round12.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round13.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round14.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round15.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round16.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round17.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round18.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round19.as_ptr().cast::<u8>()),
    RomPtr(sLevel50WildMons_Round20.as_ptr().cast::<u8>()),
];

pub(crate) static sOpenLevelWildMons_Round1: RomBytes<96> = RomBytes([97, 1, 15, 2, 86, 0, 209, 0, 227, 0, 0, 0, 98, 1, 15, 2, 86, 0, 85, 0, 98, 0, 0, 0, 25, 0, 13, 2, 86, 0, 85, 0, 21, 0, 0, 0, 125, 0, 13, 2, 9, 0, 129, 0, 103, 0, 0, 0, 45, 0, 8, 2, 78, 0, 202, 0, 182, 0, 0, 0, 82, 1, 8, 2, 86, 0, 87, 0, 98, 0, 0, 0, 51, 1, 6, 2, 78, 0, 8, 1, 202, 0, 183, 0, 135, 0, 6, 2, 86, 0, 87, 0, 42, 0, 98, 0]);

pub(crate) static sOpenLevelWildMons_Round2: RomBytes<96> = RomBytes([111, 1, 14, 2, 92, 0, 124, 0, 182, 0, 0, 0, 107, 1, 14, 2, 92, 0, 202, 0, 89, 1, 80, 0, 12, 0, 12, 2, 77, 0, 16, 0, 60, 0, 0, 0, 123, 1, 12, 2, 49, 1, 207, 0, 242, 0, 86, 1, 227, 0, 7, 2, 92, 0, 19, 0, 211, 0, 0, 0, 41, 1, 7, 1, 92, 0, 182, 0, 35, 1, 240, 0, 169, 0, 5, 2, 92, 0, 109, 0, 212, 0, 44, 0, 94, 0, 5, 2, 92, 0, 69, 1, 101, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round3: RomBytes<96> = RomBytes([58, 0, 13, 2, 172, 0, 36, 0, 0, 0, 0, 0, 37, 0, 13, 2, 5, 1, 53, 0, 0, 0, 0, 0, 219, 0, 11, 1, 53, 0, 157, 0, 182, 0, 0, 0, 38, 0, 11, 2, 5, 1, 98, 0, 53, 0, 0, 0, 101, 1, 6, 2, 7, 0, 136, 0, 0, 0, 0, 0, 110, 0, 6, 2, 5, 1, 53, 0, 182, 0, 0, 0, 106, 1, 5, 2, 5, 1, 109, 0, 212, 0, 69, 1, 229, 0, 5, 2, 53, 0, 44, 0, 76, 0, 59, 1]);

pub(crate) static sOpenLevelWildMons_Round4: RomBytes<96> = RomBytes([206, 0, 10, 2, 180, 0, 92, 0, 182, 0, 0, 0, 122, 1, 8, 2, 32, 1, 5, 1, 101, 0, 0, 0, 200, 0, 8, 2, 32, 1, 180, 0, 247, 0, 0, 0, 38, 0, 6, 2, 32, 1, 5, 1, 59, 1, 0, 0, 120, 1, 10, 2, 44, 0, 76, 1, 247, 0, 182, 0, 106, 1, 6, 2, 5, 1, 182, 0, 92, 0, 247, 0, 47, 1, 5, 2, 32, 1, 92, 0, 180, 0, 0, 0, 94, 0, 5, 2, 32, 1, 180, 0, 101, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round5: RomBytes<96> = RomBytes([93, 0, 10, 2, 101, 0, 85, 0, 188, 0, 0, 0, 155, 1, 10, 2, 38, 0, 92, 0, 94, 0, 182, 0, 93, 1, 8, 2, 89, 0, 157, 0, 126, 0, 92, 0, 200, 0, 8, 2, 94, 0, 180, 0, 247, 0, 220, 0, 63, 1, 6, 2, 89, 0, 246, 0, 120, 0, 94, 0, 110, 0, 6, 2, 188, 0, 120, 0, 182, 0, 0, 0, 78, 1, 5, 2, 89, 0, 242, 0, 81, 1, 225, 0, 94, 0, 5, 2, 85, 0, 94, 0, 202, 0, 101, 0]);

pub(crate) static sOpenLevelWildMons_Round6: RomBytes<96> = RomBytes([50, 0, 10, 2, 157, 0, 163, 0, 91, 0, 0, 0, 76, 1, 10, 2, 157, 0, 89, 0, 202, 0, 0, 0, 104, 1, 8, 0, 194, 0, 150, 0, 68, 0, 243, 0, 50, 0, 8, 1, 89, 0, 157, 0, 222, 0, 92, 0, 76, 1, 6, 1, 157, 0, 89, 0, 202, 0, 182, 0, 104, 1, 6, 0, 68, 0, 243, 0, 194, 0, 0, 0, 202, 0, 5, 0, 68, 0, 243, 0, 194, 0, 0, 0, 51, 0, 5, 1, 157, 0, 188, 0, 89, 0, 182, 0]);

pub(crate) static sOpenLevelWildMons_Round7: RomBytes<96> = RomBytes([91, 1, 10, 2, 58, 0, 242, 0, 182, 0, 0, 0, 215, 0, 10, 2, 58, 0, 50, 1, 180, 0, 0, 0, 87, 0, 8, 2, 59, 0, 38, 0, 57, 0, 0, 0, 221, 0, 8, 2, 58, 0, 89, 0, 92, 0, 0, 0, 124, 0, 6, 2, 59, 0, 142, 0, 94, 0, 0, 0, 91, 0, 6, 2, 58, 0, 57, 0, 182, 0, 0, 0, 87, 1, 5, 2, 59, 0, 34, 0, 57, 0, 0, 0, 131, 0, 5, 2, 47, 0, 34, 0, 58, 0, 94, 0]);

pub(crate) static sOpenLevelWildMons_Round8: RomBytes<96> = RomBytes([110, 0, 10, 2, 120, 0, 188, 0, 126, 0, 0, 0, 101, 0, 10, 2, 120, 0, 85, 0, 205, 0, 0, 0, 94, 0, 8, 2, 194, 0, 122, 0, 247, 0, 0, 0, 76, 0, 8, 2, 120, 0, 182, 0, 89, 0, 0, 0, 204, 0, 6, 2, 153, 0, 38, 0, 202, 0, 0, 0, 93, 1, 5, 2, 153, 0, 83, 0, 149, 0, 0, 0, 205, 0, 5, 2, 153, 0, 92, 0, 157, 0, 0, 0, 44, 1, 5, 2, 153, 0, 202, 0, 76, 0, 182, 0]);

pub(crate) static sOpenLevelWildMons_Round9: RomBytes<96> = RomBytes([202, 0, 10, 2, 68, 0, 243, 0, 219, 0, 194, 0, 143, 1, 10, 2, 89, 0, 92, 0, 188, 0, 94, 0, 103, 0, 8, 2, 121, 0, 94, 0, 95, 0, 0, 0, 199, 0, 8, 2, 247, 0, 57, 0, 58, 0, 53, 0, 178, 0, 6, 2, 109, 0, 247, 0, 94, 0, 211, 0, 65, 0, 6, 2, 94, 0, 7, 0, 8, 0, 92, 0, 121, 0, 5, 2, 94, 0, 85, 0, 57, 0, 58, 0, 196, 0, 5, 2, 94, 0, 91, 0, 247, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round10: RomBytes<96> = RomBytes([76, 0, 10, 2, 120, 0, 89, 0, 182, 0, 0, 0, 208, 0, 10, 2, 231, 0, 242, 0, 89, 0, 0, 0, 139, 0, 8, 2, 57, 0, 85, 1, 246, 0, 0, 0, 92, 1, 8, 2, 95, 0, 149, 0, 153, 0, 0, 0, 213, 0, 6, 2, 92, 0, 182, 0, 35, 0, 0, 0, 135, 1, 6, 2, 246, 0, 182, 0, 76, 1, 0, 0, 133, 1, 5, 2, 188, 0, 202, 0, 109, 0, 0, 0, 142, 0, 5, 2, 63, 0, 157, 0, 44, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round11: RomBytes<96> = RomBytes([62, 0, 10, 2, 66, 0, 8, 1, 57, 0, 0, 0, 80, 1, 10, 2, 252, 0, 57, 0, 8, 1, 0, 0, 51, 1, 8, 2, 147, 0, 8, 1, 182, 0, 0, 0, 101, 1, 8, 2, 9, 0, 7, 0, 8, 0, 8, 1, 107, 0, 6, 2, 9, 0, 7, 0, 8, 0, 8, 1, 106, 0, 6, 2, 25, 0, 8, 1, 0, 0, 0, 0, 214, 0, 5, 2, 224, 0, 89, 0, 8, 1, 157, 0, 68, 0, 5, 2, 157, 0, 89, 0, 8, 1, 69, 0]);

pub(crate) static sOpenLevelWildMons_Round12: RomBytes<96> = RomBytes([195, 0, 10, 2, 240, 0, 57, 0, 182, 0, 0, 0, 113, 1, 10, 2, 241, 0, 76, 0, 0, 0, 0, 0, 247, 0, 8, 2, 201, 0, 89, 0, 157, 0, 0, 0, 131, 0, 8, 2, 2, 1, 58, 0, 0, 0, 0, 0, 89, 1, 6, 2, 201, 0, 202, 0, 76, 0, 0, 0, 136, 0, 6, 2, 241, 0, 53, 0, 182, 0, 0, 0, 87, 1, 5, 2, 2, 1, 58, 0, 0, 0, 0, 0, 130, 0, 5, 2, 240, 0, 87, 0, 56, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round13: RomBytes<96> = RomBytes([204, 0, 10, 2, 153, 0, 36, 0, 0, 0, 0, 0, 213, 0, 8, 2, 92, 0, 89, 0, 182, 0, 0, 0, 49, 0, 8, 2, 62, 1, 77, 0, 79, 0, 94, 0, 212, 0, 6, 2, 98, 0, 232, 0, 210, 0, 228, 0, 214, 0, 6, 2, 224, 0, 24, 1, 89, 0, 157, 0, 205, 0, 5, 2, 153, 0, 89, 0, 182, 0, 0, 0, 135, 1, 5, 2, 96, 1, 182, 0, 157, 0, 0, 0, 47, 1, 5, 2, 247, 0, 92, 0, 180, 0, 32, 1]);

pub(crate) static sOpenLevelWildMons_Round14: RomBytes<96> = RomBytes([66, 1, 10, 2, 101, 0, 94, 0, 76, 1, 0, 0, 215, 0, 10, 2, 58, 0, 13, 1, 185, 0, 98, 0, 71, 1, 8, 2, 152, 0, 58, 0, 57, 0, 0, 0, 44, 1, 8, 2, 153, 0, 247, 0, 76, 1, 202, 0, 89, 1, 6, 2, 92, 0, 202, 0, 46, 1, 0, 0, 120, 1, 6, 2, 44, 0, 182, 0, 163, 0, 0, 0, 229, 0, 5, 2, 59, 1, 242, 0, 247, 0, 182, 0, 197, 0, 5, 2, 94, 0, 247, 0, 231, 0, 98, 0]);

pub(crate) static sOpenLevelWildMons_Round15: RomBytes<96> = RomBytes([224, 0, 10, 2, 190, 0, 58, 0, 126, 0, 0, 0, 87, 0, 10, 2, 96, 1, 58, 0, 29, 0, 0, 0, 54, 1, 8, 2, 182, 0, 48, 0, 57, 0, 0, 0, 195, 0, 8, 2, 89, 0, 61, 1, 57, 0, 0, 0, 41, 1, 6, 2, 182, 0, 76, 0, 92, 0, 58, 0, 199, 0, 6, 2, 94, 0, 29, 0, 207, 0, 0, 0, 121, 0, 5, 2, 96, 1, 85, 0, 109, 0, 59, 0, 9, 0, 5, 2, 56, 0, 44, 0, 58, 0, 0, 0]);

pub(crate) static sOpenLevelWildMons_Round16: RomBytes<96> = RomBytes([105, 1, 10, 2, 101, 0, 5, 1, 247, 0, 182, 0, 93, 0, 10, 2, 92, 0, 180, 0, 95, 0, 247, 0, 122, 1, 8, 2, 247, 0, 180, 0, 5, 1, 0, 0, 200, 0, 8, 2, 195, 0, 180, 0, 212, 0, 0, 0, 66, 1, 6, 2, 247, 0, 212, 0, 91, 0, 101, 0, 106, 1, 6, 2, 5, 1, 92, 0, 247, 0, 0, 0, 47, 1, 5, 2, 247, 0, 180, 0, 32, 1, 182, 0, 94, 0, 5, 2, 94, 0, 194, 0, 180, 0, 101, 0]);

pub(crate) static sOpenLevelWildMons_Round17: RomBytes<96> = RomBytes([99, 1, 10, 2, 242, 0, 92, 0, 58, 0, 0, 0, 82, 0, 10, 2, 85, 0, 86, 0, 0, 0, 0, 0, 208, 0, 8, 2, 88, 0, 38, 0, 89, 0, 0, 0, 212, 0, 8, 2, 232, 0, 163, 0, 0, 0, 0, 0, 205, 0, 6, 2, 153, 0, 92, 0, 0, 0, 0, 0, 227, 0, 6, 2, 211, 0, 92, 0, 19, 0, 182, 0, 128, 1, 5, 2, 89, 0, 36, 0, 57, 0, 58, 0, 144, 1, 5, 2, 89, 0, 94, 0, 247, 0, 24, 1]);

pub(crate) static sOpenLevelWildMons_Round18: RomBytes<96> = RomBytes([148, 0, 10, 2, 86, 0, 92, 0, 58, 0, 0, 0, 77, 1, 10, 2, 89, 0, 225, 0, 242, 0, 211, 0, 103, 1, 8, 2, 89, 0, 81, 1, 47, 0, 182, 0, 78, 1, 8, 2, 89, 0, 81, 1, 126, 0, 0, 0, 142, 0, 6, 2, 89, 0, 157, 0, 81, 1, 0, 0, 130, 0, 6, 2, 89, 0, 57, 0, 37, 0, 44, 0, 230, 0, 5, 2, 56, 0, 58, 0, 182, 0, 0, 0, 6, 0, 5, 2, 53, 0, 8, 1, 126, 0, 231, 0]);

pub(crate) static sOpenLevelWildMons_Round19: RomBytes<96> = RomBytes([59, 0, 10, 2, 126, 0, 36, 0, 0, 0, 0, 0, 62, 0, 10, 2, 56, 0, 58, 0, 0, 0, 0, 0, 26, 0, 8, 2, 87, 0, 86, 0, 21, 0, 0, 0, 134, 0, 8, 2, 57, 0, 58, 0, 0, 0, 0, 0, 135, 0, 6, 2, 85, 0, 42, 0, 0, 0, 0, 0, 136, 0, 6, 2, 53, 0, 44, 0, 0, 0, 0, 0, 38, 0, 5, 2, 53, 0, 5, 1, 182, 0, 0, 0, 121, 0, 5, 2, 58, 0, 57, 0, 85, 0, 94, 0]);

pub(crate) static sOpenLevelWildMons_Round20: RomBytes<96> = RomBytes([115, 0, 10, 2, 63, 0, 53, 0, 57, 0, 146, 0, 49, 1, 10, 2, 76, 1, 63, 0, 92, 0, 0, 0, 217, 0, 8, 2, 63, 0, 89, 0, 8, 1, 182, 0, 233, 0, 8, 2, 60, 0, 63, 0, 247, 0, 58, 0, 128, 0, 6, 2, 89, 0, 63, 0, 57, 0, 85, 0, 22, 0, 6, 2, 63, 0, 19, 0, 119, 0, 182, 0, 143, 0, 5, 2, 63, 0, 34, 0, 247, 0, 89, 0, 110, 1, 5, 2, 63, 0, 89, 0, 247, 0, 58, 0]);

pub(crate) static sOpenLevelWildMonPointers: [RomPtr<u8>; 20] = [
    RomPtr(sOpenLevelWildMons_Round1.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round2.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round3.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round4.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round5.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round6.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round7.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round8.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round9.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round10.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round11.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round12.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round13.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round14.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round15.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round16.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round17.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round18.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round19.as_ptr().cast::<u8>()),
    RomPtr(sOpenLevelWildMons_Round20.as_ptr().cast::<u8>()),
];

pub(crate) static sPyramidFloorTemplates: RomBytes<256> = RomBytes([7, 3, 0, 0, 128, 0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 0, 6, 3, 0, 0, 128, 1, 1, 2, 2, 3, 3, 4, 4, 0, 0, 0, 5, 3, 0, 0, 120, 2, 2, 3, 3, 4, 4, 5, 5, 0, 0, 0, 4, 4, 0, 0, 120, 3, 3, 4, 4, 5, 5, 6, 6, 0, 0, 0, 4, 4, 0, 1, 112, 4, 4, 5, 5, 6, 6, 7, 7, 0, 0, 0, 3, 5, 0, 2, 112, 5, 6, 7, 8, 9, 10, 11, 12, 0, 0, 0, 3, 5, 0, 0, 104, 6, 7, 8, 9, 10, 11, 12, 13, 0, 0, 0, 2, 4, 0, 1, 104, 7, 8, 9, 10, 11, 12, 13, 14, 0, 0, 0, 4, 5, 0, 2, 96, 8, 9, 10, 11, 12, 13, 14, 15, 0, 0, 0, 3, 6, 0, 4, 96, 8, 9, 10, 11, 12, 13, 14, 15, 0, 0, 0, 2, 3, 0, 0, 88, 12, 13, 14, 12, 13, 14, 12, 13, 0, 0, 0, 4, 5, 0, 0, 88, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 3, 7, 0, 0, 80, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 2, 4, 0, 0, 80, 13, 13, 13, 13, 13, 13, 13, 13, 0, 0, 0, 3, 6, 0, 0, 80, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 3, 8, 0, 0, 80, 15, 15, 15, 15, 15, 15, 15, 15, 0, 0, 0]);

pub(crate) static sPyramidFloorTemplateOptions: RomBytes<68> = RomBytes([40, 0, 70, 1, 90, 2, 100, 3, 35, 1, 55, 2, 75, 3, 90, 4, 100, 10, 35, 2, 55, 3, 75, 4, 90, 5, 100, 11, 35, 3, 55, 4, 75, 5, 90, 6, 100, 12, 35, 4, 55, 5, 75, 6, 90, 7, 100, 13, 35, 5, 55, 6, 75, 7, 90, 8, 100, 14, 35, 6, 55, 7, 75, 8, 90, 9, 100, 15]);

pub(crate) static sFloorTemplateOffsets: RomBytes<7> = RomBytes([0, 4, 9, 14, 19, 24, 29]);

pub(crate) static sPickupItemsLvl50: RomBytes<400> = RomBytes([21, 0, 81, 0, 133, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 135, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 136, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 77, 0, 134, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 78, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 79, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 73, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 81, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 77, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 78, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 79, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 73, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 81, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0]);

pub(crate) static sPickupItemsLvlOpen: RomBytes<400> = RomBytes([21, 0, 81, 0, 133, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 135, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 136, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 77, 0, 134, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 78, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 79, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 73, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 81, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 77, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 78, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 79, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 73, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0, 21, 0, 81, 0, 141, 0, 34, 0, 141, 0, 24, 0, 179, 0, 219, 0, 25, 0, 45, 0, 21, 0, 74, 0, 141, 0, 34, 0, 138, 0, 24, 0, 200, 0, 186, 0, 19, 0, 37, 0, 21, 0, 75, 0, 141, 0, 34, 0, 141, 0, 24, 0, 198, 0, 196, 0, 25, 0, 45, 0, 21, 0, 76, 0, 141, 0, 34, 0, 138, 0, 24, 0, 183, 0, 187, 0, 19, 0, 37, 0]);

pub(crate) static sPickupItemSlots: RomBytes<126> = RomBytes([31, 0, 46, 1, 61, 2, 71, 3, 81, 4, 91, 5, 94, 6, 97, 7, 100, 8, 15, 0, 46, 1, 61, 2, 71, 3, 81, 4, 91, 5, 94, 6, 97, 8, 100, 9, 15, 0, 30, 1, 61, 2, 71, 3, 81, 4, 91, 5, 94, 6, 97, 7, 100, 8, 28, 0, 43, 1, 58, 2, 68, 3, 78, 4, 88, 5, 92, 7, 96, 8, 100, 9, 15, 0, 43, 1, 58, 2, 68, 3, 78, 4, 88, 5, 92, 6, 96, 7, 100, 9, 15, 0, 30, 1, 58, 2, 68, 3, 78, 4, 88, 5, 92, 6, 96, 7, 100, 8, 28, 0, 43, 1, 58, 2, 68, 3, 78, 4, 88, 5, 92, 6, 96, 8, 100, 9]);

pub(crate) static sPickupItemOffsets: RomBytes<7> = RomBytes([0, 9, 18, 27, 36, 45, 54]);

pub(crate) static sTrainerClassEncounterMusic: RomBytes<216> = RomBytes([3, 6, 0, 0, 11, 6, 0, 0, 13, 6, 0, 0, 15, 1, 0, 0, 43, 4, 0, 0, 45, 1, 0, 0, 36, 9, 0, 0, 41, 4, 0, 0, 5, 5, 0, 0, 24, 4, 0, 0, 47, 0, 0, 0, 46, 9, 0, 0, 17, 12, 0, 0, 16, 11, 0, 0, 30, 13, 0, 0, 8, 1, 0, 0, 23, 3, 0, 0, 12, 4, 0, 0, 56, 4, 0, 0, 28, 3, 0, 0, 26, 0, 0, 0, 25, 11, 0, 0, 9, 7, 0, 0, 49, 7, 0, 0, 53, 7, 0, 0, 54, 1, 0, 0, 51, 0, 0, 0, 42, 3, 0, 0, 22, 13, 0, 0, 14, 3, 0, 0, 21, 1, 0, 0, 20, 1, 0, 0, 44, 1, 0, 0, 27, 2, 0, 0, 4, 1, 0, 0, 7, 3, 0, 0, 52, 5, 0, 0, 50, 0, 0, 0, 55, 2, 0, 0, 29, 4, 0, 0, 34, 9, 0, 0, 31, 1, 0, 0, 37, 0, 0, 0, 10, 4, 0, 0, 40, 0, 0, 0, 6, 5, 0, 0, 39, 11, 0, 0, 38, 0, 0, 0, 19, 0, 0, 0, 18, 2, 0, 0, 57, 8, 0, 0, 2, 11, 0, 0, 32, 1, 0, 0, 33, 0, 0, 0]);

pub(crate) static sTrainerTextGroups: RomBytes<100> = RomBytes([13, 3, 14, 4, 16, 1, 17, 0, 3, 2, 18, 3, 12, 3, 19, 3, 20, 3, 21, 2, 23, 2, 7, 2, 10, 4, 25, 2, 26, 2, 27, 0, 29, 2, 30, 2, 31, 3, 32, 4, 38, 0, 39, 1, 41, 4, 42, 5, 9, 4, 22, 5, 43, 0, 45, 4, 46, 2, 48, 2, 50, 2, 49, 3, 47, 3, 51, 3, 52, 2, 4, 2, 53, 0, 54, 3, 55, 3, 56, 3, 28, 1, 58, 2, 5, 2, 66, 2, 2, 3, 68, 2, 69, 3, 71, 3, 67, 0, 0, 4]);

pub(crate) static sExitDirectionHintTexts1: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp1)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft1)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight1)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown1)),
];

pub(crate) static sRemainingItemsHintTexts1: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining1)),
];

pub(crate) static sRemainingTrainersHintTexts1: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining1)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining1)),
];

pub(crate) static sExitDirectionHintTexts2: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp2)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft2)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight2)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown2)),
];

pub(crate) static sRemainingItemsHintTexts2: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining2)),
];

pub(crate) static sRemainingTrainersHintTexts2: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining2)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining2)),
];

pub(crate) static sExitDirectionHintTexts3: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp3)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft3)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight3)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown3)),
];

pub(crate) static sRemainingItemsHintTexts3: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining3)),
];

pub(crate) static sRemainingTrainersHintTexts3: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining3)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining3)),
];

pub(crate) static sExitDirectionHintTexts4: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp4)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft4)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight4)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown4)),
];

pub(crate) static sRemainingItemsHintTexts4: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining4)),
];

pub(crate) static sRemainingTrainersHintTexts4: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining4)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining4)),
];

pub(crate) static sExitDirectionHintTexts5: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp5)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft5)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight5)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown5)),
];

pub(crate) static sRemainingItemsHintTexts5: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining5)),
];

pub(crate) static sRemainingTrainersHintTexts5: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining5)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining5)),
];

pub(crate) static sExitDirectionHintTexts6: [RomPtr<u8>; 4] = [
    RomPtr((&raw const BattlePyramid_Text_ExitHintUp6)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintLeft6)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintRight6)),
    RomPtr((&raw const BattlePyramid_Text_ExitHintDown6)),
];

pub(crate) static sRemainingItemsHintTexts6: [RomPtr<u8>; 9] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_OneItemRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_TwoItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_ThreeItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_FourItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_FiveItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_SixItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_SevenItemsRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_EightItemsRemaining6)),
];

pub(crate) static sRemainingTrainersHintTexts6: [RomPtr<u8>; 8] = [
    RomPtr((&raw const BattlePyramid_Text_ZeroTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_OneTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_TwoTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_ThreeTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_FourTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_FiveTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_SixTrainersRemaining6)),
    RomPtr((&raw const BattlePyramid_Text_SevenTrainersRemaining6)),
];

pub(crate) static sPostBattleHintTexts1: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts1.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts1.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts1.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleHintTexts2: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts2.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts2.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts2.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleHintTexts3: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts3.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts3.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts3.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleHintTexts4: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts4.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts4.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts4.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleHintTexts5: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts5.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts5.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts5.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleHintTexts6: [RomPtr<u8>; 3] = [
    RomPtr(sExitDirectionHintTexts6.as_ptr().cast::<u8>()),
    RomPtr(sRemainingItemsHintTexts6.as_ptr().cast::<u8>()),
    RomPtr(sRemainingTrainersHintTexts6.as_ptr().cast::<u8>()),
];

pub(crate) static sPostBattleTexts: [RomPtr<u8>; 6] = [
    RomPtr(sPostBattleHintTexts1.as_ptr().cast::<u8>()),
    RomPtr(sPostBattleHintTexts2.as_ptr().cast::<u8>()),
    RomPtr(sPostBattleHintTexts3.as_ptr().cast::<u8>()),
    RomPtr(sPostBattleHintTexts4.as_ptr().cast::<u8>()),
    RomPtr(sPostBattleHintTexts5.as_ptr().cast::<u8>()),
    RomPtr(sPostBattleHintTexts6.as_ptr().cast::<u8>()),
];

pub(crate) static sHintTextTypes: RomBytes<8> = RomBytes([3, 4, 5, 6, 7, 8, 3, 4]);

pub(crate) static sBattlePyramidFunctions: [RomPtr<u8>; 18] = [
    RomPtr(crate::battle_pyramid::InitPyramidChallenge as *const u8),
    RomPtr(crate::battle_pyramid::GetBattlePyramidData as *const u8),
    RomPtr(crate::battle_pyramid::SetBattlePyramidData as *const u8),
    RomPtr(crate::battle_pyramid::SavePyramidChallenge as *const u8),
    RomPtr(crate::battle_pyramid::SetBattlePyramidPrize as *const u8),
    RomPtr(crate::battle_pyramid::GiveBattlePyramidPrize as *const u8),
    RomPtr(crate::battle_pyramid::SeedPyramidFloor as *const u8),
    RomPtr(crate::battle_pyramid::SetPickupItem as *const u8),
    RomPtr(crate::battle_pyramid::HidePyramidItem as *const u8),
    RomPtr(crate::battle_pyramid::SetPyramidFacilityTrainers as *const u8),
    RomPtr(crate::battle_pyramid::ShowPostBattleHintText as *const u8),
    RomPtr(crate::battle_pyramid::UpdatePyramidWinStreak as *const u8),
    RomPtr(crate::battle_pyramid::GetCurrentBattlePyramidLocation as *const u8),
    RomPtr(crate::battle_pyramid::UpdatePyramidLightRadius as *const u8),
    RomPtr(crate::battle_pyramid::ClearPyramidPartyHeldItems as *const u8),
    RomPtr(crate::battle_pyramid::SetPyramidFloorPalette as *const u8),
    RomPtr(crate::battle_pyramid::BattlePyramidStartMenu as *const u8),
    RomPtr(crate::battle_pyramid::RestorePyramidPlayerParty as *const u8),
];

pub(crate) static sShortStreakRewardItems: RomBytes<12> = RomBytes([63, 0, 64, 0, 65, 0, 67, 0, 66, 0, 70, 0]);

pub(crate) static sLongStreakRewardItems: RomBytes<18> = RomBytes([179, 0, 180, 0, 183, 0, 200, 0, 185, 0, 187, 0, 196, 0, 198, 0, 186, 0]);

pub(crate) static sBorderedSquareIds: RomBytes<64> = RomBytes([1, 4, 255, 255, 0, 2, 5, 255, 1, 3, 6, 255, 2, 7, 255, 255, 0, 5, 8, 255, 1, 4, 6, 9, 2, 5, 7, 10, 3, 6, 11, 255, 4, 9, 12, 255, 5, 8, 10, 13, 6, 9, 11, 14, 7, 10, 15, 255, 8, 13, 255, 255, 9, 12, 14, 255, 10, 13, 15, 255, 11, 14, 255, 255]);

pub(crate) static sPickupPercentages: RomBytes<10> = RomBytes([30, 40, 50, 60, 70, 80, 85, 90, 95, 100]);

