// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sAffineAnim_PsychUpSpiral: RomBytes<24> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 254, 255, 254, 255, 246, 120, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_PsychUpSpiral: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_PsychUpSpiral.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_ReflectSparkle: RomBytes<24> = RomBytes([0, 0, 3, 0, 16, 0, 3, 0, 32, 0, 3, 0, 48, 0, 3, 0, 64, 0, 3, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_ReflectSparkle: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_ReflectSparkle.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_SpecialScreenSparkle: RomBytes<20> = RomBytes([0, 0, 5, 0, 4, 0, 5, 0, 8, 0, 5, 0, 12, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_SpecialScreenSparkle: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_SpecialScreenSparkle.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_BentSpoon_0: RomBytes<64> = RomBytes([8, 0, 124, 0, 16, 0, 69, 0, 8, 0, 69, 0, 0, 0, 69, 0, 8, 0, 86, 0, 253, 255, 0, 0, 16, 0, 69, 0, 8, 0, 69, 0, 0, 0, 69, 0, 8, 0, 69, 0, 253, 255, 1, 0, 8, 0, 86, 0, 24, 0, 67, 0, 32, 0, 67, 0, 40, 0, 86, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_BentSpoon_1: RomBytes<64> = RomBytes([8, 0, 60, 0, 16, 0, 5, 0, 8, 0, 5, 0, 0, 0, 5, 0, 8, 0, 22, 0, 253, 255, 0, 0, 16, 0, 5, 0, 8, 0, 5, 0, 0, 0, 5, 0, 8, 0, 5, 0, 253, 255, 1, 0, 8, 0, 22, 0, 24, 0, 3, 0, 32, 0, 3, 0, 40, 0, 22, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_BentSpoon: [RomPtr<u8>; 2] = [
    RomPtr(sAnim_BentSpoon_0.as_ptr().cast::<u8>()),
    RomPtr(sAnim_BentSpoon_1.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_QuestionMark: RomBytes<32> = RomBytes([0, 0, 6, 0, 16, 0, 6, 0, 32, 0, 6, 0, 48, 0, 6, 0, 64, 0, 6, 0, 80, 0, 6, 0, 96, 0, 18, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_QuestionMark: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_QuestionMark.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_QuestionMark: RomBytes<40> = RomBytes([0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 252, 8, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 253, 127, 2, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_QuestionMark: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_QuestionMark.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_MeditateStretchAttacker: RomBytes<32> = RomBytes([248, 255, 10, 0, 0, 16, 0, 0, 18, 0, 238, 255, 0, 16, 0, 0, 236, 255, 16, 0, 0, 8, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_Teleport: RomBytes<24> = RomBytes([64, 0, 252, 255, 0, 20, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_SkillSwapOrb_0: RomBytes<24> = RomBytes([248, 255, 248, 255, 0, 8, 0, 0, 8, 0, 8, 0, 0, 8, 0, 0, 254, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_SkillSwapOrb_1: RomBytes<40> = RomBytes([240, 0, 240, 0, 0, 0, 0, 0, 248, 255, 248, 255, 0, 6, 0, 0, 8, 0, 8, 0, 0, 8, 0, 0, 248, 255, 248, 255, 0, 2, 0, 0, 254, 127, 1, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_SkillSwapOrb_2: RomBytes<40> = RomBytes([208, 0, 208, 0, 0, 0, 0, 0, 248, 255, 248, 255, 0, 4, 0, 0, 8, 0, 8, 0, 0, 8, 0, 0, 248, 255, 248, 255, 0, 4, 0, 0, 254, 127, 1, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_SkillSwapOrb_3: RomBytes<40> = RomBytes([176, 0, 176, 0, 0, 0, 0, 0, 248, 255, 248, 255, 0, 2, 0, 0, 8, 0, 8, 0, 0, 8, 0, 0, 248, 255, 248, 255, 0, 6, 0, 0, 254, 127, 1, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_SkillSwapOrb: [RomPtr<u8>; 4] = [
    RomPtr(sAffineAnim_SkillSwapOrb_0.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_SkillSwapOrb_1.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_SkillSwapOrb_2.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_SkillSwapOrb_3.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_LusterPurgeCircle: RomBytes<24> = RomBytes([32, 0, 32, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 120, 0, 0, 255, 127, 1, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_LusterPurgeCircle: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_LusterPurgeCircle.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_PsychoBoostOrb_0: RomBytes<88> = RomBytes([32, 0, 32, 0, 0, 0, 0, 0, 16, 0, 16, 0, 0, 17, 0, 0, 253, 127, 0, 0, 0, 0, 0, 0, 248, 255, 248, 255, 0, 10, 0, 0, 8, 0, 8, 0, 0, 10, 0, 0, 253, 127, 4, 0, 0, 0, 0, 0, 253, 127, 0, 0, 0, 0, 0, 0, 240, 255, 240, 255, 0, 5, 0, 0, 16, 0, 16, 0, 0, 5, 0, 0, 253, 127, 7, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_PsychoBoostOrb_1: RomBytes<16> = RomBytes([236, 255, 24, 0, 0, 15, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_PsychoBoostOrb: [RomPtr<u8>; 2] = [
    RomPtr(sAffineAnim_PsychoBoostOrb_0.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_PsychoBoostOrb_1.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gPsychUpSpiralSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27d427d4 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_PsychUpSpiral.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_mons::AnimSpriteOnMonPos as *const u8),
];

#[unsafe(no_mangle)]
pub static gLightScreenWallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27b627b6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimDefensiveWall as *const u8),
];

#[unsafe(no_mangle)]
pub static gReflectWallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27b727b7 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimDefensiveWall as *const u8),
];

#[unsafe(no_mangle)]
pub static gMirrorCoatWallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27b827b8 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimDefensiveWall as *const u8),
];

#[unsafe(no_mangle)]
pub static gBarrierWallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27b927b9 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimDefensiveWall as *const u8),
];

#[unsafe(no_mangle)]
pub static gMagicCoatWallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27ba27ba as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimDefensiveWall as *const u8),
];

#[unsafe(no_mangle)]
pub static gReflectSparkleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27572757 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_ReflectSparkle.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimWallSparkle as *const u8),
];

#[unsafe(no_mangle)]
pub static gSpecialScreenSparkleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27562756 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_SpecialScreenSparkle.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimWallSparkle as *const u8),
];

#[unsafe(no_mangle)]
pub static gGoldRingSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27b327b3 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x32).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_mons::TranslateAnimSpriteToTargetMonLocation as *const u8),
];

#[unsafe(no_mangle)]
pub static gBentSpoonSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27712771 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x32).cast::<u8>()),
    RomPtr(sAnims_BentSpoon.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimBentSpoon as *const u8),
];

#[unsafe(no_mangle)]
pub static gQuestionMarkSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x276d276d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_QuestionMark.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimQuestionMark as *const u8),
];

#[unsafe(no_mangle)]
pub static gImprisonOrbSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x28092809 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjBlend_16x16).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

#[unsafe(no_mangle)]
pub static gRedXSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x280a280a as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimRedX as *const u8),
];

#[unsafe(no_mangle)]
pub static gSkillSwapOrbSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x280b280b as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjNormal_16x16).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_SkillSwapOrb.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimSkillSwapOrb as *const u8),
];

#[unsafe(no_mangle)]
pub static gLusterPurgeCircleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x281b281b as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineDouble_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_LusterPurgeCircle.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_mons::AnimSpriteOnMonPos as *const u8),
];

#[unsafe(no_mangle)]
pub static gPsychoBoostOrbSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27e427e4 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineDouble_ObjBlend_64x64).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_PsychoBoostOrb.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_psychic::AnimPsychoBoost as *const u8),
];

