// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sRotatingBall_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/bag/rotating_ball.png.gbapal")));

pub(crate) static sRotatingBall_Gfx: RomBytes<128> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/bag/rotating_ball.png.4bpp")));

pub(crate) static sCherryUnused: RomBytes<1152> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/unused/cherry.png.4bpp")));

pub(crate) static sCherryUnused_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/unused/cherry.png.gbapal")));

pub(crate) static sBagOamData: RomBytes<8> = RomBytes([0, 1, 0, 192, 0, 4, 0, 0]);

pub(crate) static sSpriteAnim_Bag_Closed: RomBytes<8> = RomBytes([0, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Bag_Items: RomBytes<8> = RomBytes([64, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Bag_KeyItems: RomBytes<8> = RomBytes([128, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Bag_Pokeballs: RomBytes<8> = RomBytes([192, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Bag_TMsHMs: RomBytes<8> = RomBytes([0, 1, 4, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Bag_Berries: RomBytes<8> = RomBytes([64, 1, 4, 0, 255, 255, 0, 0]);

pub(crate) static sBagSpriteAnimTable: [RomPtr<u8>; 6] = [
    RomPtr(sSpriteAnim_Bag_Closed.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Bag_Items.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Bag_Pokeballs.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Bag_TMsHMs.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Bag_Berries.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Bag_KeyItems.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteAffineAnim_BagNormal: RomBytes<16> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sSpriteAffineAnim_BagShake: RomBytes<40> = RomBytes([0, 0, 0, 0, 254, 2, 0, 0, 0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 254, 4, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sBagAffineAnimCmds: [RomPtr<u8>; 2] = [
    RomPtr(sSpriteAffineAnim_BagNormal.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAffineAnim_BagShake.as_ptr().cast::<u8>()),
];

pub(crate) static sBagSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x640064 as *const u8),
    RomPtr(sBagOamData.as_ptr().cast::<u8>()),
    RomPtr(sBagSpriteAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sBagAffineAnimCmds.as_ptr().cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sRotatingBallOamData: RomBytes<8> = RomBytes([0, 0, 0, 72, 0, 8, 0, 0]);

pub(crate) static sSpriteAffineAnim_RotatingBallStationary: RomBytes<8> = RomBytes([0, 0, 0, 0, 255, 255, 0, 0]);

pub(crate) static sRotatingBallSpriteAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sSpriteAffineAnim_RotatingBallStationary.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteAffineAnim_RotatingBallRotation1: RomBytes<16> = RomBytes([0, 0, 0, 0, 8, 16, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sSpriteAffineAnim_RotatingBallRotation2: RomBytes<16> = RomBytes([0, 0, 0, 0, 248, 16, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sRotatingBallAnimCmds: [RomPtr<u8>; 1] = [
    RomPtr(sSpriteAffineAnim_RotatingBallRotation1.as_ptr().cast::<u8>()),
];

pub(crate) static sRotatingBallAnimCmds_FullRotation: [RomPtr<u8>; 1] = [
    RomPtr(sSpriteAffineAnim_RotatingBallRotation2.as_ptr().cast::<u8>()),
];

pub(crate) static sRotatingBallTable: [RomPtr<u8>; 2] = [
    RomPtr(sRotatingBall_Gfx.as_ptr().cast::<u8>()),
    RomPtr(0x650080 as *const u8),
];

pub(crate) static sRotatingBallPaletteTable: [RomPtr<u8>; 2] = [
    RomPtr(sRotatingBall_Pal.as_ptr().cast::<u8>()),
    RomPtr(0x65 as *const u8),
];

pub(crate) static sRotatingBallSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x650065 as *const u8),
    RomPtr(sRotatingBallOamData.as_ptr().cast::<u8>()),
    RomPtr(sRotatingBallSpriteAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sRotatingBallAnimCmds.as_ptr().cast::<u8>()),
    RomPtr(crate::item_menu_icons::SpriteCB_SwitchPocketRotatingBallInit as *const u8),
];

pub(crate) static sBerryPicOamData: RomBytes<8> = RomBytes([0, 0, 0, 192, 0, 116, 0, 0]);

pub(crate) static sBerryPicRotatingOamData: RomBytes<8> = RomBytes([0, 3, 0, 192, 0, 112, 0, 0]);

pub(crate) static sAnim_BerryPic: RomBytes<8> = RomBytes([0, 0, 0, 0, 255, 255, 0, 0]);

pub(crate) static sBerryPicSpriteAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_BerryPic.as_ptr().cast::<u8>()),
];

pub(crate) static sBerryPicSpriteImageTable: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::decompress::gDecompressionBuffer).cast::<u8>()),
    RomPtr(0x800 as *const u8),
];

pub(crate) static sBerryPicSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x7544ffff as *const u8),
    RomPtr(sBerryPicOamData.as_ptr().cast::<u8>()),
    RomPtr(sBerryPicSpriteAnimTable.as_ptr().cast::<u8>()),
    RomPtr(sBerryPicSpriteImageTable.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sSpriteAffineAnim_BerryPicRotation1: RomBytes<56> = RomBytes([255, 255, 255, 255, 253, 96, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 254, 255, 254, 255, 255, 64, 0, 0, 248, 255, 0, 0, 0, 16, 0, 0, 0, 0, 248, 255, 0, 16, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 254, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sSpriteAffineAnim_BerryPicRotation2: RomBytes<56> = RomBytes([255, 255, 255, 255, 3, 96, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 254, 255, 254, 255, 1, 64, 0, 0, 248, 255, 0, 0, 0, 16, 0, 0, 0, 0, 248, 255, 0, 16, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 254, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sBerryPicRotatingAnimCmds: [RomPtr<u8>; 2] = [
    RomPtr(sSpriteAffineAnim_BerryPicRotation1.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAffineAnim_BerryPicRotation2.as_ptr().cast::<u8>()),
];

pub(crate) static sBerryPicRotatingSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x7544ffff as *const u8),
    RomPtr(sBerryPicRotatingOamData.as_ptr().cast::<u8>()),
    RomPtr(sBerryPicSpriteAnimTable.as_ptr().cast::<u8>()),
    RomPtr(sBerryPicSpriteImageTable.as_ptr().cast::<u8>()),
    RomPtr(sBerryPicRotatingAnimCmds.as_ptr().cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sBerryPicTable: [RomPtr<u8>; 86] = [
    RomPtr((&raw const crate::data::graphics::gBerryPic_Cheri).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Cheri).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Chesto).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Chesto).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Pecha).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Pecha).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Rawst).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Rawst).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Aspear).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Aspear).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Leppa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Leppa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Oran).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Oran).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Persim).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Persim).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Lum).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Lum).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Sitrus).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Sitrus).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Figy).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Figy).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Wiki).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Wiki).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Mago).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Mago).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Aguav).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Aguav).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Iapapa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Iapapa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Razz).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Razz).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Bluk).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Bluk).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Nanab).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Nanab).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Wepear).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Wepear).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Pinap).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Pinap).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Pomeg).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Pomeg).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Kelpsy).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Kelpsy).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Qualot).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Qualot).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Hondew).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Hondew).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Grepa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Grepa).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Tamato).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Tamato).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Cornn).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Cornn).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Magost).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Magost).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Rabuta).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Rabuta).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Nomel).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Nomel).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Spelon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Spelon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Pamtre).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Pamtre).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Watmel).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Watmel).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Durin).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Durin).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Belue).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Belue).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Liechi).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Liechi).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Ganlon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Ganlon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Salac).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Salac).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Petaya).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Petaya).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Apicot).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Apicot).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Lansat).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Lansat).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Starf).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Starf).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPic_Enigma).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gBerryPalette_Enigma).cast::<u8>()),
];

pub(crate) static sBerryCheckCircleOamData: RomBytes<8> = RomBytes([0, 0, 0, 192, 0, 4, 0, 0]);

pub(crate) static sSpriteAnim_BerryCheckCircle: RomBytes<8> = RomBytes([0, 0, 0, 0, 255, 255, 0, 0]);

pub(crate) static sBerryCheckCircleSpriteAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sSpriteAnim_BerryCheckCircle.as_ptr().cast::<u8>()),
];

pub(crate) static sBerryCheckCircleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27102710 as *const u8),
    RomPtr(sBerryCheckCircleOamData.as_ptr().cast::<u8>()),
    RomPtr(sBerryCheckCircleSpriteAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

#[unsafe(no_mangle)]
pub static gBagMaleSpriteSheet: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::data::graphics::gBagMaleTiles).cast::<u8>()),
    RomPtr(0x643000 as *const u8),
];

#[unsafe(no_mangle)]
pub static gBagFemaleSpriteSheet: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::data::graphics::gBagFemaleTiles).cast::<u8>()),
    RomPtr(0x643000 as *const u8),
];

#[unsafe(no_mangle)]
pub static gBagPaletteTable: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::data::graphics::gBagPalette).cast::<u8>()),
    RomPtr(0x64 as *const u8),
];

#[unsafe(no_mangle)]
pub static gBerryCheckCircleSpriteSheet: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::data::graphics::gBerryCheckCircle_Gfx).cast::<u8>()),
    RomPtr(0x27100800 as *const u8),
];

#[unsafe(no_mangle)]
pub static gBerryCheckCirclePaletteTable: [RomPtr<u8>; 2] = [
    RomPtr((&raw const crate::data::graphics::gBerryCheck_Pal).cast::<u8>()),
    RomPtr(0x2710 as *const u8),
];

