// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static Sio32ConnectionData: RomBytes<8> = RomBytes([78, 73, 78, 84, 69, 78, 68, 79]);

pub(crate) static Sio32IDLib_Var: RomBytes<15> = RomBytes([83, 105, 111, 51, 50, 73, 68, 95, 48, 51, 48, 56, 50, 48, 0]);

