// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sMonMarkings_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/interface/mon_markings.png.gbapal")));

pub(crate) static sMonMarkings_Gfx: RomBytes<2048> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/interface/mon_markings.png.4bpp")));

pub(crate) static sOamData_MenuWindow: RomBytes<8> = RomBytes([0, 0, 0, 192, 0, 0, 0, 0]);

pub(crate) static sOamData_8x8: RomBytes<8> = RomBytes([0, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAnim_Marking_CircleOff: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_CircleOn: RomBytes<8> = RomBytes([1, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_SquareOff: RomBytes<8> = RomBytes([2, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_SquareOn: RomBytes<8> = RomBytes([3, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_TriangleOff: RomBytes<8> = RomBytes([4, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_TriangleOn: RomBytes<8> = RomBytes([5, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_HeartOff: RomBytes<8> = RomBytes([6, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Marking_HeartOn: RomBytes<8> = RomBytes([7, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Cursor: RomBytes<8> = RomBytes([8, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_OKCancelText: RomBytes<8> = RomBytes([9, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_MenuSprite: [RomPtr<u8>; 10] = [
    RomPtr(sAnim_Marking_CircleOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_CircleOn.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_SquareOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_SquareOn.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_TriangleOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_TriangleOn.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_HeartOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Marking_HeartOn.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Cursor.as_ptr().cast::<u8>()),
    RomPtr(sAnim_OKCancelText.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_MenuWindow_UpperHalf: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MenuWindow_LowerHalf: RomBytes<8> = RomBytes([64, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_MenuWindow: [RomPtr<u8>; 2] = [
    RomPtr(sAnim_MenuWindow_UpperHalf.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MenuWindow_LowerHalf.as_ptr().cast::<u8>()),
];

pub(crate) static sOamData_MarkingCombo: RomBytes<8> = RomBytes([0, 64, 0, 64, 0, 0, 0, 0]);

pub(crate) static sAnim_MarkingCombo_AllOff: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_Circle: RomBytes<8> = RomBytes([4, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_Square: RomBytes<8> = RomBytes([8, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleSquare: RomBytes<8> = RomBytes([12, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_Triangle: RomBytes<8> = RomBytes([16, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleTriangle: RomBytes<8> = RomBytes([20, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_SquareTriangle: RomBytes<8> = RomBytes([24, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleSquareTriangle: RomBytes<8> = RomBytes([28, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_Heart: RomBytes<8> = RomBytes([32, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleHeart: RomBytes<8> = RomBytes([36, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_SquareHeart: RomBytes<8> = RomBytes([40, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleSquareHeart: RomBytes<8> = RomBytes([44, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_TriangleHeart: RomBytes<8> = RomBytes([48, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_CircleTriangleHeart: RomBytes<8> = RomBytes([52, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_SquareTriangleHeart: RomBytes<8> = RomBytes([56, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_MarkingCombo_AllOn: RomBytes<8> = RomBytes([60, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_MarkingCombo: [RomPtr<u8>; 16] = [
    RomPtr(sAnim_MarkingCombo_AllOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_Circle.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_Square.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleSquare.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_Triangle.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleTriangle.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_SquareTriangle.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleSquareTriangle.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_Heart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_SquareHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleSquareHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_TriangleHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_CircleTriangleHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_SquareTriangleHeart.as_ptr().cast::<u8>()),
    RomPtr(sAnim_MarkingCombo_AllOn.as_ptr().cast::<u8>()),
];

