// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sItemStorage_OptionDescriptions: [RomPtr<u8>; 4] = [
    RomPtr((&raw const crate::data::strings::gText_TakeOutItemsFromPC).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_StoreItemsInPC).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ThrowAwayItemsInPC).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_GoBackPrevMenu).cast::<u8>()),
];

pub(crate) static sPlayerPCMenuActions: [RomPtr<u8>; 8] = [
    RomPtr((&raw const crate::data::strings::gText_ItemStorage).cast::<u8>()),
    RomPtr(crate::player_pc::PlayerPC_ItemStorage as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Mailbox).cast::<u8>()),
    RomPtr(crate::player_pc::PlayerPC_Mailbox as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Decoration).cast::<u8>()),
    RomPtr(crate::player_pc::PlayerPC_Decoration as *const u8),
    RomPtr((&raw const crate::data::strings::gText_TurnOff).cast::<u8>()),
    RomPtr(crate::player_pc::PlayerPC_TurnOff as *const u8),
];

pub(crate) static sBedroomPC_OptionOrder: RomBytes<4> = RomBytes([0, 1, 2, 3]);

pub(crate) static sPlayerPC_OptionOrder: RomBytes<3> = RomBytes([0, 1, 3]);

pub(crate) static sItemStorage_MenuActions: [RomPtr<u8>; 8] = [
    RomPtr((&raw const crate::data::strings::gText_WithdrawItem).cast::<u8>()),
    RomPtr(crate::player_pc::ItemStorage_Withdraw as *const u8),
    RomPtr((&raw const crate::data::strings::gText_DepositItem).cast::<u8>()),
    RomPtr(crate::player_pc::ItemStorage_Deposit as *const u8),
    RomPtr((&raw const crate::data::strings::gText_TossItem).cast::<u8>()),
    RomPtr(crate::player_pc::ItemStorage_Toss as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Cancel).cast::<u8>()),
    RomPtr(crate::player_pc::ItemStorage_Exit as *const u8),
];

pub(crate) static sNewGamePCItems: RomBytes<8> = RomBytes([13, 0, 1, 0, 0, 0, 0, 0]);

pub(crate) static sWindowTemplates_MainMenus: RomBytes<24> = RomBytes([0, 1, 1, 9, 6, 15, 1, 0, 0, 1, 1, 9, 8, 15, 1, 0, 0, 1, 1, 10, 8, 15, 1, 0]);

pub(crate) static ItemTossYesNoFuncs: [RomPtr<u8>; 2] = [
    RomPtr(crate::player_pc::ItemStorage_TossItemYes as *const u8),
    RomPtr(crate::player_pc::ItemStorage_TossItemNo as *const u8),
];

pub(crate) static sListMenuTemplate_ItemStorage: [RomPtr<u8>; 6] = [
    RomPtr(0x0 as *const u8),
    RomPtr(crate::player_pc::ItemStorage_MoveCursor as *const u8),
    RomPtr(crate::player_pc::ItemStorage_PrintMenuItem as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x80000 as *const u8),
    RomPtr(0x7003129 as *const u8),
];

pub(crate) static sWindowTemplates_ItemStorage: RomBytes<48> = RomBytes([0, 16, 1, 13, 18, 15, 1, 0, 0, 1, 13, 13, 6, 15, 235, 0, 0, 1, 8, 3, 3, 15, 83, 1, 0, 1, 1, 13, 2, 15, 57, 1, 0, 8, 9, 6, 2, 15, 92, 1, 0, 9, 7, 5, 4, 15, 104, 1]);

pub(crate) static sSwapArrowTextColors: RomBytes<3> = RomBytes([1, 3, 2]);

pub(crate) static CSWTCH_150: [RomPtr<u8>; 9] = [
    RomPtr((&raw const crate::data::strings::gText_MoveVar1Where).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ConfirmTossItems).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_TooImportantToToss).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_NoRoomInBag).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ThrewAwayVar2Var1s).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_TossHowManyVar1s).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WithdrawXItems).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WithdrawHowManyItems).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_GoBackPrevMenu).cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gMailboxMailOptions: [RomPtr<u8>; 8] = [
    RomPtr((&raw const crate::data::strings::gText_Read).cast::<u8>()),
    RomPtr(crate::player_pc::Mailbox_DoMailRead as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MoveToBag).cast::<u8>()),
    RomPtr(crate::player_pc::Mailbox_MoveToBag as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Give2).cast::<u8>()),
    RomPtr(crate::player_pc::Mailbox_Give as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Cancel2).cast::<u8>()),
    RomPtr(crate::player_pc::Mailbox_Cancel as *const u8),
];

