// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sRibbonData: RomBytes<68> = RomBytes([1, 1, 0, 0, 3, 4, 1, 0, 3, 4, 5, 0, 3, 4, 9, 0, 3, 4, 13, 0, 3, 4, 17, 0, 1, 1, 21, 0, 1, 1, 22, 0, 1, 1, 23, 0, 1, 1, 24, 0, 1, 1, 25, 1, 1, 1, 26, 1, 1, 1, 27, 1, 1, 1, 28, 1, 1, 1, 29, 1, 1, 1, 30, 1, 1, 1, 31, 1]);

pub(crate) static sRibbonIcons1_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons1.pal.gbapal")));

pub(crate) static sRibbonIcons2_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons2.pal.gbapal")));

pub(crate) static sRibbonIcons3_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons3.pal.gbapal")));

pub(crate) static sRibbonIcons4_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons4.pal.gbapal")));

pub(crate) static sRibbonIcons5_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons5.pal.gbapal")));

pub(crate) static sMonInfo_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/mon_info.pal.gbapal")));

pub(crate) static sRibbonIconsSmall_Gfx: RomBytes<456> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons.png.4bpp.lz")));

pub(crate) static sRibbonIconsBig_Gfx: RomBytes<2328> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokenav/ribbons/icons_big.png.4bpp.lz")));

pub(crate) static sBgTemplates: RomBytes<8> = RomBytes([125, 16, 0, 0, 102, 32, 0, 0]);

pub(crate) static sRibbonsSummaryMenuLoopTaskFuncs: [RomPtr<u8>; 6] = [
    RomPtr(0x0 as *const u8),
    RomPtr(crate::pokenav_ribbons_summary::LoopedTask_SwitchRibbonsSummaryMon as *const u8),
    RomPtr(crate::pokenav_ribbons_summary::LoopedTask_ExpandSelectedRibbon as *const u8),
    RomPtr(crate::pokenav_ribbons_summary::LoopedTask_MoveRibbonsCursorExpanded as *const u8),
    RomPtr(crate::pokenav_ribbons_summary::LoopedTask_ShrinkExpandedRibbon as *const u8),
    RomPtr(crate::pokenav_ribbons_summary::LoopedTask_ExitRibbonsSummaryMenu as *const u8),
];

pub(crate) static sRibbonCountWindowTemplate: RomBytes<8> = RomBytes([2, 12, 13, 16, 4, 1, 20, 0]);

pub(crate) static sRibbonSummaryMonNameWindowTemplate: RomBytes<8> = RomBytes([2, 14, 1, 13, 2, 10, 84, 0]);

pub(crate) static sRibbonMonListIndexWindowTemplate: RomBytes<16> = RomBytes([2, 1, 5, 7, 2, 1, 110, 0, 0, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sSpriteSheet_RibbonIconsBig: [RomPtr<u8>; 2] = [
    RomPtr(sRibbonIconsBig_Gfx.as_ptr().cast::<u8>()),
    RomPtr(0x91800 as *const u8),
];

pub(crate) static sSpritePalettes_RibbonIcons: [RomPtr<u8>; 12] = [
    RomPtr(sRibbonIcons1_Pal.as_ptr().cast::<u8>()),
    RomPtr(0xf as *const u8),
    RomPtr(sRibbonIcons2_Pal.as_ptr().cast::<u8>()),
    RomPtr(0x10 as *const u8),
    RomPtr(sRibbonIcons3_Pal.as_ptr().cast::<u8>()),
    RomPtr(0x11 as *const u8),
    RomPtr(sRibbonIcons4_Pal.as_ptr().cast::<u8>()),
    RomPtr(0x12 as *const u8),
    RomPtr(sRibbonIcons5_Pal.as_ptr().cast::<u8>()),
    RomPtr(0x13 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sSpriteTemplate_RibbonIconBig: [RomPtr<u8>; 6] = [
    RomPtr(0xf0009 as *const u8),
    RomPtr(sOamData_RibbonIconBig.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_RibbonIconBig.as_ptr().cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sText_MaleSymbol: RomBytes<12> = RomBytes([252, 4, 5, 1, 6, 181, 252, 4, 2, 1, 3, 255]);

pub(crate) static sText_FemaleSymbol: RomBytes<12> = RomBytes([252, 4, 7, 1, 8, 182, 252, 4, 2, 1, 3, 255]);

pub(crate) static sGenderlessIconString: RomBytes<2> = RomBytes([119, 255]);

pub(crate) static sRibbonGfxData: RomBytes<128> = RomBytes([0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 4, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 0, 3, 0, 2, 0, 4, 0, 2, 0, 1, 0, 3, 0, 2, 0, 3, 0, 3, 0, 3, 0, 4, 0, 3, 0, 1, 0, 4, 0, 2, 0, 4, 0, 3, 0, 4, 0, 4, 0, 4, 0, 5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 1, 0, 8, 0, 2, 0, 9, 0, 1, 0, 9, 0, 3, 0, 9, 0, 4, 0, 10, 0, 3, 0, 10, 0, 4, 0, 11, 0, 0, 0, 11, 0, 1, 0]);

pub(crate) static sOamData_RibbonIconBig: RomBytes<8> = RomBytes([0, 1, 0, 128, 0, 4, 0, 0]);

pub(crate) static sAffineAnim_RibbonIconBig_Normal: RomBytes<16> = RomBytes([128, 0, 128, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_RibbonIconBig_ZoomIn: RomBytes<24> = RomBytes([128, 0, 128, 0, 0, 0, 0, 0, 32, 0, 32, 0, 0, 4, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_RibbonIconBig_ZoomOut: RomBytes<24> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 224, 255, 224, 255, 0, 4, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_RibbonIconBig: [RomPtr<u8>; 3] = [
    RomPtr(sAffineAnim_RibbonIconBig_Normal.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_RibbonIconBig_ZoomIn.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_RibbonIconBig_ZoomOut.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_Champion: RomBytes<23> = RomBytes([189, 194, 187, 199, 202, 195, 201, 200, 174, 214, 217, 213, 232, 221, 226, 219, 184, 0, 194, 187, 198, 198, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_Champion: RomBytes<22> = RomBytes([201, 192, 0, 192, 187, 199, 191, 0, 199, 217, 225, 214, 217, 230, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_CoolContest: RomBytes<13> = RomBytes([189, 201, 201, 198, 0, 189, 201, 200, 206, 191, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_BeautyContest: RomBytes<15> = RomBytes([188, 191, 187, 207, 206, 211, 0, 189, 201, 200, 206, 191, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_CuteContest: RomBytes<13> = RomBytes([189, 207, 206, 191, 0, 189, 201, 200, 206, 191, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_SmartContest: RomBytes<14> = RomBytes([205, 199, 187, 204, 206, 0, 189, 201, 200, 206, 191, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_ToughContest: RomBytes<14> = RomBytes([206, 201, 207, 193, 194, 0, 189, 201, 200, 206, 191, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_NormalRank: RomBytes<20> = RomBytes([200, 227, 230, 225, 213, 224, 0, 204, 213, 226, 223, 0, 235, 221, 226, 226, 217, 230, 171, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_SuperRank: RomBytes<19> = RomBytes([205, 233, 228, 217, 230, 0, 204, 213, 226, 223, 0, 235, 221, 226, 226, 217, 230, 171, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_HyperRank: RomBytes<19> = RomBytes([194, 237, 228, 217, 230, 0, 204, 213, 226, 223, 0, 235, 221, 226, 226, 217, 230, 171, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_MasterRank: RomBytes<20> = RomBytes([199, 213, 231, 232, 217, 230, 0, 204, 213, 226, 223, 0, 235, 221, 226, 226, 217, 230, 171, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_Winning: RomBytes<18> = RomBytes([192, 227, 230, 0, 215, 224, 217, 213, 230, 221, 226, 219, 0, 198, 208, 166, 161, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_Winning: RomBytes<21> = RomBytes([213, 232, 0, 232, 220, 217, 0, 188, 187, 206, 206, 198, 191, 0, 206, 201, 209, 191, 204, 173, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_Victory: RomBytes<24> = RomBytes([192, 227, 230, 0, 215, 224, 217, 213, 230, 221, 226, 219, 0, 201, 228, 217, 226, 0, 198, 217, 234, 217, 224, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_Victory: RomBytes<21> = RomBytes([213, 232, 0, 232, 220, 217, 0, 188, 187, 206, 206, 198, 191, 0, 206, 201, 209, 191, 204, 173, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_Artist: RomBytes<24> = RomBytes([204, 195, 188, 188, 201, 200, 0, 218, 227, 230, 0, 214, 217, 221, 226, 219, 0, 215, 220, 227, 231, 217, 226, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_Artist: RomBytes<25> = RomBytes([213, 231, 0, 213, 0, 231, 233, 228, 217, 230, 0, 231, 223, 217, 232, 215, 220, 0, 225, 227, 216, 217, 224, 173, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart1_Effort: RomBytes<19> = RomBytes([204, 195, 188, 188, 201, 200, 0, 213, 235, 213, 230, 216, 217, 216, 0, 218, 227, 230, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPart2_Effort: RomBytes<21> = RomBytes([214, 217, 221, 226, 219, 0, 213, 0, 220, 213, 230, 216, 0, 235, 227, 230, 223, 217, 230, 173, 255]);

#[unsafe(no_mangle)]
pub static gRibbonDescriptionPointers: [RomPtr<u8>; 50] = [
    RomPtr(gRibbonDescriptionPart1_Champion.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CoolContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_NormalRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CoolContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_SuperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CoolContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_HyperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CoolContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_MasterRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_BeautyContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_NormalRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_BeautyContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_SuperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_BeautyContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_HyperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_BeautyContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_MasterRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CuteContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_NormalRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CuteContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_SuperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CuteContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_HyperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_CuteContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_MasterRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_SmartContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_NormalRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_SmartContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_SuperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_SmartContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_HyperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_SmartContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_MasterRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_ToughContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_NormalRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_ToughContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_SuperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_ToughContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_HyperRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_ToughContest.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_MasterRank.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_Winning.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_Winning.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_Victory.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_Victory.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_Artist.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_Artist.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart1_Effort.as_ptr().cast::<u8>()),
    RomPtr(gRibbonDescriptionPart2_Effort.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2003RegionalTourney: RomBytes<22> = RomBytes([163, 161, 161, 164, 0, 204, 191, 193, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_Champion: RomBytes<16> = RomBytes([189, 194, 187, 199, 202, 195, 201, 200, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2003NationalTourney: RomBytes<22> = RomBytes([163, 161, 161, 164, 0, 200, 187, 206, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2003GlobalCup: RomBytes<16> = RomBytes([163, 161, 161, 164, 0, 193, 198, 201, 188, 187, 198, 0, 189, 207, 202, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_RunnerUp: RomBytes<17> = RomBytes([204, 233, 226, 226, 217, 230, 174, 233, 228, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_Semifinalist: RomBytes<20> = RomBytes([205, 217, 225, 221, 218, 221, 226, 213, 224, 221, 231, 232, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2004RegionalTourney: RomBytes<22> = RomBytes([163, 161, 161, 165, 0, 204, 191, 193, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2004NationalTourney: RomBytes<22> = RomBytes([163, 161, 161, 165, 0, 200, 187, 206, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2004GlobalCup: RomBytes<16> = RomBytes([163, 161, 161, 165, 0, 193, 198, 201, 188, 187, 198, 0, 189, 207, 202, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2005RegionalTourney: RomBytes<22> = RomBytes([163, 161, 161, 166, 0, 204, 191, 193, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2005NationalTourney: RomBytes<22> = RomBytes([163, 161, 161, 166, 0, 200, 187, 206, 195, 201, 200, 187, 198, 0, 206, 201, 207, 204, 200, 191, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_2005GlobalCup: RomBytes<16> = RomBytes([163, 161, 161, 166, 0, 193, 198, 201, 188, 187, 198, 0, 189, 207, 202, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonBattleCup: RomBytes<19> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 188, 187, 206, 206, 198, 191, 0, 189, 207, 202, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_Participation: RomBytes<21> = RomBytes([202, 213, 230, 232, 221, 215, 221, 228, 213, 232, 221, 227, 226, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonLeague: RomBytes<15> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 198, 191, 187, 193, 207, 191, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_AdvanceCup: RomBytes<12> = RomBytes([187, 190, 208, 187, 200, 189, 191, 0, 189, 207, 202, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonTournament: RomBytes<19> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 206, 227, 233, 230, 226, 213, 225, 217, 226, 232, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_Participation2: RomBytes<21> = RomBytes([202, 213, 230, 232, 221, 215, 221, 228, 213, 232, 221, 227, 226, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonEvent: RomBytes<14> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 191, 234, 217, 226, 232, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonFestival: RomBytes<17> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 192, 217, 231, 232, 221, 234, 213, 224, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_DifficultyClearing: RomBytes<20> = RomBytes([190, 221, 218, 218, 221, 215, 233, 224, 232, 237, 174, 215, 224, 217, 213, 230, 221, 226, 219, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_Commemorative: RomBytes<21> = RomBytes([189, 227, 225, 225, 217, 225, 227, 230, 213, 232, 221, 234, 217, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_ClearingAllChallenges: RomBytes<19> = RomBytes([204, 195, 188, 188, 201, 200, 0, 213, 235, 213, 230, 216, 217, 216, 0, 218, 227, 230, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_ClearingAllChallenges: RomBytes<25> = RomBytes([215, 224, 217, 213, 230, 221, 226, 219, 0, 213, 224, 224, 0, 215, 220, 213, 224, 224, 217, 226, 219, 217, 231, 173, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_100StraightWin: RomBytes<17> = RomBytes([162, 161, 161, 174, 231, 232, 230, 213, 221, 219, 220, 232, 0, 209, 221, 226, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_DarknessTower: RomBytes<21> = RomBytes([190, 187, 204, 197, 200, 191, 205, 205, 0, 206, 201, 209, 191, 204, 0, 189, 224, 217, 213, 230, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_RedTower: RomBytes<16> = RomBytes([204, 191, 190, 0, 206, 201, 209, 191, 204, 0, 189, 224, 217, 213, 230, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_BlackironTower: RomBytes<22> = RomBytes([188, 198, 187, 189, 197, 195, 204, 201, 200, 0, 206, 201, 209, 191, 204, 0, 189, 224, 217, 213, 230, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_FinalTower: RomBytes<18> = RomBytes([192, 195, 200, 187, 198, 0, 206, 201, 209, 191, 204, 0, 189, 224, 217, 213, 230, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_LegendMaking: RomBytes<14> = RomBytes([198, 217, 219, 217, 226, 216, 174, 225, 213, 223, 221, 226, 219, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonCenterTokyo: RomBytes<21> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 189, 191, 200, 206, 191, 204, 0, 206, 201, 197, 211, 201, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonCenterOsaka: RomBytes<21> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 189, 191, 200, 206, 191, 204, 0, 201, 205, 187, 197, 187, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonCenterNagoya: RomBytes<22> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 189, 191, 200, 206, 191, 204, 0, 200, 187, 193, 201, 211, 187, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_PokemonCenterNY: RomBytes<18> = RomBytes([202, 201, 197, 27, 199, 201, 200, 0, 189, 191, 200, 206, 191, 204, 0, 200, 211, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_SummerHolidays: RomBytes<23> = RomBytes([205, 233, 225, 225, 217, 230, 0, 194, 227, 224, 221, 216, 213, 237, 231, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_EmptyString: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_WinterHolidays: RomBytes<23> = RomBytes([209, 221, 226, 232, 217, 230, 0, 194, 227, 224, 221, 216, 213, 237, 231, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_SpringHolidays: RomBytes<23> = RomBytes([205, 228, 230, 221, 226, 219, 0, 194, 227, 224, 221, 216, 213, 237, 231, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_Evergreen: RomBytes<17> = RomBytes([191, 234, 217, 230, 219, 230, 217, 217, 226, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_SpecialHoliday: RomBytes<23> = RomBytes([205, 228, 217, 215, 221, 213, 224, 0, 194, 227, 224, 221, 216, 213, 237, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_HardWorker: RomBytes<19> = RomBytes([194, 213, 230, 216, 0, 209, 227, 230, 223, 217, 230, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_LotsOfFriends: RomBytes<23> = RomBytes([198, 227, 232, 231, 0, 227, 218, 0, 192, 230, 221, 217, 226, 216, 231, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_FullOfEnergy: RomBytes<22> = RomBytes([192, 233, 224, 224, 0, 227, 218, 0, 191, 226, 217, 230, 219, 237, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_LovedPokemon: RomBytes<23> = RomBytes([187, 0, 215, 227, 225, 225, 217, 225, 227, 230, 213, 232, 221, 234, 217, 0, 204, 195, 188, 188, 201, 200, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_LovedPokemon: RomBytes<21> = RomBytes([218, 227, 230, 0, 213, 0, 224, 227, 234, 217, 216, 0, 202, 201, 197, 27, 199, 201, 200, 173, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart1_LoveForPokemon: RomBytes<18> = RomBytes([204, 195, 188, 188, 201, 200, 0, 232, 220, 213, 232, 0, 231, 220, 227, 235, 231, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPart2_LoveForPokemon: RomBytes<18> = RomBytes([224, 227, 234, 217, 0, 218, 227, 230, 0, 202, 201, 197, 27, 199, 201, 200, 173, 255]);

#[unsafe(no_mangle)]
pub static gGiftRibbonDescriptionPointers: [RomPtr<u8>; 128] = [
    RomPtr(gGiftRibbonDescriptionPart1_2003RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2003GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2004GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005RegionalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005NationalTourney.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_2005GlobalCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonBattleCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonBattleCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonBattleCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonBattleCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonLeague.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonLeague.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonLeague.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonLeague.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_AdvanceCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Champion.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_AdvanceCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_RunnerUp.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_AdvanceCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Semifinalist.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_AdvanceCup.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonTournament.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation2.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonEvent.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation2.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonFestival.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Participation2.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_DifficultyClearing.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_ClearingAllChallenges.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_ClearingAllChallenges.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_100StraightWin.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_DarknessTower.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_RedTower.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_BlackironTower.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_FinalTower.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_LegendMaking.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonCenterTokyo.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonCenterOsaka.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonCenterNagoya.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_PokemonCenterNY.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_Commemorative.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_SummerHolidays.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_WinterHolidays.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_SpringHolidays.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_Evergreen.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_SpecialHoliday.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_HardWorker.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_LotsOfFriends.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_FullOfEnergy.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_EmptyString.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_LovedPokemon.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_LovedPokemon.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart1_LoveForPokemon.as_ptr().cast::<u8>()),
    RomPtr(gGiftRibbonDescriptionPart2_LoveForPokemon.as_ptr().cast::<u8>()),
];

