// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};


pub(crate) static sMrStoneTextScripts: [RomPtr<u8>; 24] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone1.cast::<u8>()))),
    RomPtr(0x158ffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone2.cast::<u8>()))),
    RomPtr(0xffff0158 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone3.cast::<u8>()))),
    RomPtr(0xffff00bd as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone4.cast::<u8>()))),
    RomPtr(0xffff0110 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone5.cast::<u8>()))),
    RomPtr(0xffff006a as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone6.cast::<u8>()))),
    RomPtr(0xffff04f4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone7.cast::<u8>()))),
    RomPtr(0xffff0097 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone8.cast::<u8>()))),
    RomPtr(0xffff006f as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone9.cast::<u8>()))),
    RomPtr(0xffff0070 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone10.cast::<u8>()))),
    RomPtr(0xffff04f7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_MrStone11.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sMrStoneMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0xffff0a00 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MrStoneMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MrStoneMatchCallName).cast::<u8>()),
    RomPtr(sMrStoneTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sNormanTextScripts: [RomPtr<u8>; 20] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman1.cast::<u8>()))),
    RomPtr(0xffff0132 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman2.cast::<u8>()))),
    RomPtr(0xffff04f1 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman3.cast::<u8>()))),
    RomPtr(0xffff04f3 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman4.cast::<u8>()))),
    RomPtr(0xffff04f4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman5.cast::<u8>()))),
    RomPtr(0xffff00d4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman_RematchReady.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Norman_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sNormanMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1320705 as *const u8),
    RomPtr(0x45 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_NormanMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_NormanMatchCallName).cast::<u8>()),
    RomPtr(sNormanTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sProfBirchMatchCallHeader: [RomPtr<u8>; 3] = [
    RomPtr(0x1190003 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ProfBirchMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ProfBirchMatchCallName).cast::<u8>()),
];

pub(crate) static sMomTextScripts: [RomPtr<u8>; 8] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Mom1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Mom2.cast::<u8>()))),
    RomPtr(0xffff04f4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Mom3.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sMomMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0xd80000 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MomMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MomMatchCallName).cast::<u8>()),
    RomPtr(sMomTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sStevenTextScripts: [RomPtr<u8>; 16] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven2.cast::<u8>()))),
    RomPtr(0xffff00c7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven3.cast::<u8>()))),
    RomPtr(0xffff00d4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven4.cast::<u8>()))),
    RomPtr(0xffff0070 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven5.cast::<u8>()))),
    RomPtr(0xffff04f6 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven6.cast::<u8>()))),
    RomPtr(0xffff0081 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Steven7.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sStevenMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0x131d500 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_StevenMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_StevenMatchCallName).cast::<u8>()),
    RomPtr(sStevenTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sMayTextScripts: [RomPtr<u8>; 32] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May2.cast::<u8>()))),
    RomPtr(0xffff04f1 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May3.cast::<u8>()))),
    RomPtr(0xffff0095 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May4.cast::<u8>()))),
    RomPtr(0xffff0324 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May5.cast::<u8>()))),
    RomPtr(0xffff006a as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May6.cast::<u8>()))),
    RomPtr(0xffff04f3 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May7.cast::<u8>()))),
    RomPtr(0xffff04f4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May8.cast::<u8>()))),
    RomPtr(0xffff0097 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May9.cast::<u8>()))),
    RomPtr(0xffff00d4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May10.cast::<u8>()))),
    RomPtr(0xffff006f as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May11.cast::<u8>()))),
    RomPtr(0xffff0061 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May12.cast::<u8>()))),
    RomPtr(0xffff0070 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May13.cast::<u8>()))),
    RomPtr(0xffff0081 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May14.cast::<u8>()))),
    RomPtr(0xffff04f7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_May15.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sMayMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0xfd0004 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MayBrendanMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ExpandedPlaceholder_May).cast::<u8>()),
    RomPtr(sMayTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sBrendanTextScripts: [RomPtr<u8>; 32] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan2.cast::<u8>()))),
    RomPtr(0xffff04f1 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan3.cast::<u8>()))),
    RomPtr(0xffff0095 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan4.cast::<u8>()))),
    RomPtr(0xffff0324 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan5.cast::<u8>()))),
    RomPtr(0xffff006a as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan6.cast::<u8>()))),
    RomPtr(0xffff04f3 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan7.cast::<u8>()))),
    RomPtr(0xffff04f4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan8.cast::<u8>()))),
    RomPtr(0xffff0097 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan9.cast::<u8>()))),
    RomPtr(0xffff00d4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan10.cast::<u8>()))),
    RomPtr(0xffff006f as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan11.cast::<u8>()))),
    RomPtr(0xffff0061 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan12.cast::<u8>()))),
    RomPtr(0xffff0070 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan13.cast::<u8>()))),
    RomPtr(0xffff0081 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan14.cast::<u8>()))),
    RomPtr(0xffff04f7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brendan15.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sBrendanMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0xfd0104 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MayBrendanMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ExpandedPlaceholder_Brendan).cast::<u8>()),
    RomPtr(sBrendanTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sWallyTextScripts: [RomPtr<u8>; 16] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally2.cast::<u8>()))),
    RomPtr(0xffff00c7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally3.cast::<u8>()))),
    RomPtr(0xffff04f3 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally4.cast::<u8>()))),
    RomPtr(0xffff0097 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally5.cast::<u8>()))),
    RomPtr(0xffff006f as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally6.cast::<u8>()))),
    RomPtr(0xffff0081 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wally7.cast::<u8>()))),
    RomPtr(0xffff007e as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sWallyLocationData: RomBytes<16> = RomBytes([36, 3, 5, 0, 111, 0, 213, 0, 90, 3, 70, 0, 255, 255, 213, 0]);

pub(crate) static sWallyMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0xd60002 as *const u8),
    RomPtr(0x40 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WallyMatchCallDesc).cast::<u8>()),
    RomPtr(sWallyTextScripts.as_ptr().cast::<u8>()),
    RomPtr(sWallyLocationData.as_ptr().cast::<u8>()),
];

pub(crate) static sScottTextScripts: [RomPtr<u8>; 16] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott1.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott2.cast::<u8>()))),
    RomPtr(0xffff008b as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott3.cast::<u8>()))),
    RomPtr(0xffff0097 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott4.cast::<u8>()))),
    RomPtr(0xffff00d4 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott5.cast::<u8>()))),
    RomPtr(0xffff0070 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott6.cast::<u8>()))),
    RomPtr(0xffff04f7 as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Scott7.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sScottMatchCallHeader: [RomPtr<u8>; 4] = [
    RomPtr(0xd7d500 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ScottMatchCallDesc).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ScottMatchCallName).cast::<u8>()),
    RomPtr(sScottTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sRoxanneTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Roxanne_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Roxanne_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Roxanne_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Roxanne_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sRoxanneMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d30a05 as *const u8),
    RomPtr(0x41 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_RoxanneMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sRoxanneTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sBrawlyTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brawly_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brawly_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brawly_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Brawly_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sBrawlyMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d40205 as *const u8),
    RomPtr(0x42 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BrawlyMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sBrawlyTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sWattsonTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wattson_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wattson_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wattson_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wattson_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sWattsonMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d50905 as *const u8),
    RomPtr(0x43 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WattsonMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sWattsonTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sFlanneryTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Flannery_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Flannery_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Flannery_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Flannery_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sFlanneryMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d60305 as *const u8),
    RomPtr(0x44 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_FlanneryMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sFlanneryTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sWinonaTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Winona_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Winona_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Winona_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Winona_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sWinonaMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d70b05 as *const u8),
    RomPtr(0x46 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WinonaMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sWinonaTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sTateLizaTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_TateLiza_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_TateLiza_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_TateLiza_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_TateLiza_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sTateLizaMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d80d05 as *const u8),
    RomPtr(0x47 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_TateLizaMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sTateLizaTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sJuanTextScripts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Juan_Preparing.cast::<u8>()))),
    RomPtr(0xfffffffe as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Juan_PreparingPostGame.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Juan_RematchReady.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Juan_PostRematch.cast::<u8>()))),
    RomPtr(0xffff0864 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sJuanMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1d90e05 as *const u8),
    RomPtr(0x48 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_JuanMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sJuanTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sSidneyTextScripts: [RomPtr<u8>; 4] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Sidney.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sSidneyMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1a50f05 as *const u8),
    RomPtr(0x49 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_EliteFourMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sSidneyTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sPhoebeTextScripts: [RomPtr<u8>; 4] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Phoebe.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sPhoebeMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1a60f05 as *const u8),
    RomPtr(0x4a as *const u8),
    RomPtr((&raw const crate::data::strings::gText_EliteFourMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sPhoebeTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sGlaciaTextScripts: [RomPtr<u8>; 4] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Glacia.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sGlaciaMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1a70f05 as *const u8),
    RomPtr(0x4b as *const u8),
    RomPtr((&raw const crate::data::strings::gText_EliteFourMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sGlaciaTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sDrakeTextScripts: [RomPtr<u8>; 4] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Drake.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sDrakeMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1a80f05 as *const u8),
    RomPtr(0x4c as *const u8),
    RomPtr((&raw const crate::data::strings::gText_EliteFourMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sDrakeTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sWallaceTextScripts: [RomPtr<u8>; 4] = [
    RomPtr((&raw const (*crate::asmdata::MatchCall_Text_Wallace.cast::<u8>()))),
    RomPtr(0xffffffff as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xffffffff as *const u8),
];

pub(crate) static sWallaceMatchCallHeader: [RomPtr<u8>; 5] = [
    RomPtr(0x1a90f05 as *const u8),
    RomPtr(0x4d as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ChampionMatchCallDesc).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sWallaceTextScripts.as_ptr().cast::<u8>()),
];

pub(crate) static sMatchCallHeaders: [RomPtr<u8>; 21] = [
    RomPtr(sMrStoneMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sProfBirchMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sBrendanMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sMayMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sWallyMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sNormanMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sMomMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sStevenMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sScottMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sRoxanneMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sBrawlyMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sWattsonMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sFlanneryMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sWinonaMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sTateLizaMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sJuanMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sSidneyMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sPhoebeMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sGlaciaMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sDrakeMatchCallHeader.as_ptr().cast::<u8>()),
    RomPtr(sWallaceMatchCallHeader.as_ptr().cast::<u8>()),
];

pub(crate) static sMatchCallGetEnabledFuncs: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetEnabled_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetEnabled_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetEnabled_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetEnabled_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetEnabled_Birch as *const u8),
];

pub(crate) static sMatchCallGetMapSecFuncs: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMapSec_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMapSec_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMapSec_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMapSec_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMapSec_Birch as *const u8),
];

pub(crate) static sMatchCall_IsRematchableFunctions: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_IsRematchable_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_IsRematchable_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_IsRematchable_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_IsRematchable_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_IsRematchable_Birch as *const u8),
];

pub(crate) static sMatchCall_HasCheckPageFunctions: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_HasCheckPage_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_HasCheckPage_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_HasCheckPage_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_HasCheckPage_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_HasCheckPage_Birch as *const u8),
];

pub(crate) static sMatchCall_GetRematchTableIdxFunctions: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetRematchTableIdx_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetRematchTableIdx_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetRematchTableIdx_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetRematchTableIdx_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetRematchTableIdx_Birch as *const u8),
];

pub(crate) static sMatchCall_GetMessageFunctions: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMessage_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMessage_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMessage_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMessage_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetMessage_Birch as *const u8),
];

pub(crate) static sMatchCall_GetNameAndDescFunctions: [RomPtr<u8>; 5] = [
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetNameAndDesc_NPC as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetNameAndDesc_Trainer as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetNameAndDesc_Wally as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetNameAndDesc_Rival as *const u8),
    RomPtr(crate::pokenav_match_call_data::MatchCall_GetNameAndDesc_Birch as *const u8),
];

pub(crate) static sCheckPageOverrides: [RomPtr<u8>; 24] = [
    RomPtr(0x4b0007 as *const u8),
    RomPtr(0xffff as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Strategy).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Pokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Intro1_BeforeMeteorFallsBattle).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Intro2_BeforeMeteorFallsBattle).cast::<u8>()),
    RomPtr(0x4b0007 as *const u8),
    RomPtr(0x4f6 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Strategy).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Pokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Intro1_AfterMeteorFallsBattle).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallSteven_Intro2_AfterMeteorFallsBattle).cast::<u8>()),
    RomPtr(0x3c0002 as *const u8),
    RomPtr(0xffff as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MatchCallBrendan_Strategy).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallBrendan_Pokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallBrendan_Intro1).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallBrendan_Intro2).cast::<u8>()),
    RomPtr(0x3f0003 as *const u8),
    RomPtr(0xffff as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MatchCallMay_Strategy).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallMay_Pokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallMay_Intro1).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MatchCallMay_Intro2).cast::<u8>()),
];

pub(crate) static CSWTCH_48: RomBytes<20> = RomBytes([1, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0]);

