// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
// Command: tools/rustport/cdata.py --all src/text_input_strings.c
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

#[unsafe(no_mangle)]
pub static gText_EasyChatKeyboard_ABCDEFothers: RomBytes<34> = RomBytes([252, 17, 11, 187, 252, 17, 6, 188, 252, 17, 6, 189, 252, 17, 26, 190, 252, 17, 6, 191, 252, 17, 6, 192, 252, 17, 26, 227, 232, 220, 217, 230, 231, 255]);

#[unsafe(no_mangle)]
pub static gText_EasyChatKeyboard_GHIJKL: RomBytes<25> = RomBytes([252, 17, 11, 193, 252, 17, 6, 194, 252, 17, 6, 195, 252, 17, 26, 196, 252, 17, 6, 197, 252, 17, 6, 198, 255]);

#[unsafe(no_mangle)]
pub static gText_EasyChatKeyboard_MNOPQRS: RomBytes<33> = RomBytes([252, 17, 11, 199, 252, 17, 6, 200, 252, 17, 6, 201, 252, 17, 26, 202, 252, 17, 6, 203, 252, 17, 6, 204, 252, 17, 6, 205, 252, 17, 26, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_EasyChatKeyboard_TUVWXYZ: RomBytes<33> = RomBytes([252, 17, 11, 206, 252, 17, 6, 207, 252, 17, 6, 208, 252, 17, 26, 209, 252, 17, 6, 210, 252, 17, 6, 211, 252, 17, 6, 212, 252, 17, 26, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_abcdef: RomBytes<33> = RomBytes([252, 17, 11, 213, 252, 17, 6, 214, 252, 17, 6, 215, 252, 17, 26, 216, 252, 17, 6, 217, 252, 17, 6, 218, 252, 17, 6, 0, 252, 17, 30, 173, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_ghijkl: RomBytes<33> = RomBytes([252, 17, 11, 219, 252, 17, 6, 220, 252, 17, 7, 221, 252, 17, 27, 222, 252, 17, 7, 223, 252, 17, 7, 224, 252, 17, 7, 0, 252, 17, 30, 184, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_mnopqrs: RomBytes<33> = RomBytes([252, 17, 11, 225, 252, 17, 6, 226, 252, 17, 6, 227, 252, 17, 26, 228, 252, 17, 6, 229, 252, 17, 7, 230, 252, 17, 6, 231, 252, 17, 27, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_tuvwxyz: RomBytes<33> = RomBytes([252, 17, 11, 232, 252, 17, 6, 233, 252, 17, 6, 234, 252, 17, 26, 235, 252, 17, 6, 236, 252, 17, 6, 237, 252, 17, 6, 238, 252, 17, 26, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_ABCDEF: RomBytes<33> = RomBytes([252, 17, 11, 187, 252, 17, 6, 188, 252, 17, 6, 189, 252, 17, 26, 190, 252, 17, 6, 191, 252, 17, 6, 192, 252, 17, 6, 0, 252, 17, 30, 173, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_GHIJKL: RomBytes<33> = RomBytes([252, 17, 11, 193, 252, 17, 6, 194, 252, 17, 6, 195, 252, 17, 26, 196, 252, 17, 6, 197, 252, 17, 6, 198, 252, 17, 6, 0, 252, 17, 30, 184, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_MNOPQRS: RomBytes<33> = RomBytes([252, 17, 11, 199, 252, 17, 6, 200, 252, 17, 6, 201, 252, 17, 26, 202, 252, 17, 6, 203, 252, 17, 6, 204, 252, 17, 6, 205, 252, 17, 26, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_TUVWXYZ: RomBytes<33> = RomBytes([252, 17, 11, 206, 252, 17, 6, 207, 252, 17, 6, 208, 252, 17, 26, 209, 252, 17, 6, 210, 252, 17, 6, 211, 252, 17, 6, 212, 252, 17, 26, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_01234: RomBytes<25> = RomBytes([252, 17, 11, 161, 252, 17, 16, 162, 252, 17, 16, 163, 252, 17, 16, 164, 252, 17, 16, 165, 252, 17, 16, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_56789: RomBytes<25> = RomBytes([252, 17, 11, 166, 252, 17, 16, 167, 252, 17, 16, 168, 252, 17, 16, 169, 252, 17, 16, 170, 252, 17, 16, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_Symbols1: RomBytes<25> = RomBytes([252, 17, 12, 171, 252, 17, 17, 172, 252, 17, 16, 181, 252, 17, 16, 182, 252, 17, 16, 186, 252, 17, 17, 174, 255]);

#[unsafe(no_mangle)]
pub static gText_NamingScreenKeyboard_Symbols2: RomBytes<25> = RomBytes([252, 17, 11, 176, 252, 17, 16, 177, 252, 17, 16, 178, 252, 17, 18, 179, 252, 17, 19, 180, 252, 17, 18, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_ABCDE: RomBytes<6> = RomBytes([187, 188, 189, 190, 191, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_FGHIJ: RomBytes<6> = RomBytes([192, 193, 194, 195, 196, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_KLMNO: RomBytes<6> = RomBytes([197, 198, 199, 200, 201, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_PQRST: RomBytes<6> = RomBytes([202, 203, 204, 205, 206, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_UVWXY: RomBytes<6> = RomBytes([207, 208, 209, 210, 211, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Z: RomBytes<6> = RomBytes([212, 0, 0, 0, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_01234Upper: RomBytes<6> = RomBytes([161, 162, 163, 164, 165, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_56789Upper: RomBytes<6> = RomBytes([166, 167, 168, 169, 170, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_PunctuationUpper: RomBytes<6> = RomBytes([173, 184, 171, 172, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_SymbolsUpper: RomBytes<6> = RomBytes([174, 186, 45, 176, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_abcde: RomBytes<6> = RomBytes([213, 214, 215, 216, 217, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_fghij: RomBytes<6> = RomBytes([218, 219, 220, 221, 222, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_klmno: RomBytes<6> = RomBytes([223, 224, 225, 226, 227, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_pqrst: RomBytes<6> = RomBytes([228, 229, 230, 231, 232, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_uvwxy: RomBytes<6> = RomBytes([233, 234, 235, 236, 237, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_z: RomBytes<6> = RomBytes([238, 0, 0, 0, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_01234Lower: RomBytes<6> = RomBytes([161, 162, 163, 164, 165, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_56789Lower: RomBytes<6> = RomBytes([166, 167, 168, 169, 170, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_PunctuationLower: RomBytes<6> = RomBytes([173, 184, 171, 172, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_SymbolsLower: RomBytes<6> = RomBytes([174, 186, 45, 176, 0, 255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput1: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput2: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput3: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput4: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput5: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput6: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput7: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_EmptyTextInput8: RomBytes<1> = RomBytes([255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji1: RomBytes<11> = RomBytes([249, 245, 249, 246, 249, 247, 249, 248, 249, 254, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji2: RomBytes<11> = RomBytes([249, 249, 249, 250, 249, 252, 249, 251, 249, 253, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji3: RomBytes<11> = RomBytes([249, 236, 249, 237, 249, 238, 249, 235, 249, 234, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji4: RomBytes<9> = RomBytes([181, 182, 249, 212, 249, 213, 249, 211, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji5: RomBytes<11> = RomBytes([249, 216, 249, 217, 249, 242, 249, 243, 249, 244, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji6: RomBytes<11> = RomBytes([249, 218, 249, 241, 249, 224, 249, 226, 249, 227, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji7: RomBytes<11> = RomBytes([249, 240, 249, 239, 249, 225, 249, 214, 249, 215, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji8: RomBytes<11> = RomBytes([249, 228, 249, 229, 249, 230, 249, 231, 249, 232, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji9: RomBytes<11> = RomBytes([249, 233, 249, 220, 249, 221, 249, 222, 249, 209, 255]);

#[unsafe(no_mangle)]
pub static gText_UnionRoomChatKeyboard_Emoji10: RomBytes<8> = RomBytes([249, 210, 249, 208, 54, 240, 0, 255]);

