// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sUnusedUnknownPal: RomBytes<224> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/title_screen/unused.pal.gbapal")));

pub(crate) static sTitleScreenRayquazaGfx: RomBytes<2020> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/title_screen/rayquaza.png.4bpp.lz")));

pub(crate) static sTitleScreenRayquazaTilemap: RomBytes<768> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/title_screen/rayquaza.bin.lz")));

pub(crate) static sTitleScreenLogoShineGfx: RomBytes<336> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/title_screen/logo_shine.png.4bpp.lz")));

pub(crate) static sTitleScreenCloudsGfx: RomBytes<740> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/title_screen/clouds.png.4bpp.lz")));

pub(crate) static sVersionBannerLeftOamData: RomBytes<8> = RomBytes([160, 96, 0, 192, 0, 0, 0, 0]);

pub(crate) static sVersionBannerRightOamData: RomBytes<8> = RomBytes([160, 96, 0, 192, 0, 0, 0, 0]);

pub(crate) static sVersionBannerLeftAnimSequence: RomBytes<8> = RomBytes([0, 0, 30, 0, 255, 255, 0, 0]);

pub(crate) static sVersionBannerRightAnimSequence: RomBytes<8> = RomBytes([64, 0, 30, 0, 255, 255, 0, 0]);

pub(crate) static sVersionBannerLeftAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sVersionBannerLeftAnimSequence.as_ptr().cast::<u8>()),
];

pub(crate) static sVersionBannerRightAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sVersionBannerRightAnimSequence.as_ptr().cast::<u8>()),
];

pub(crate) static sVersionBannerLeftSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x3e803e8 as *const u8),
    RomPtr(sVersionBannerLeftOamData.as_ptr().cast::<u8>()),
    RomPtr(sVersionBannerLeftAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::title_screen::SpriteCB_VersionBannerLeft as *const u8),
];

pub(crate) static sVersionBannerRightSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x3e803e8 as *const u8),
    RomPtr(sVersionBannerRightOamData.as_ptr().cast::<u8>()),
    RomPtr(sVersionBannerRightAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::title_screen::SpriteCB_VersionBannerRight as *const u8),
];

pub(crate) static sSpriteSheet_EmeraldVersion: [RomPtr<u8>; 4] = [
    RomPtr((&raw const crate::data::graphics::gTitleScreenEmeraldVersionGfx).cast::<u8>()),
    RomPtr(0x3e81000 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sOamData_CopyrightBanner: RomBytes<8> = RomBytes([160, 64, 0, 64, 0, 0, 0, 0]);

pub(crate) static sAnim_PressStart_0: RomBytes<8> = RomBytes([1, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_PressStart_1: RomBytes<8> = RomBytes([5, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_PressStart_2: RomBytes<8> = RomBytes([9, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_PressStart_3: RomBytes<8> = RomBytes([13, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_PressStart_4: RomBytes<8> = RomBytes([17, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Copyright_0: RomBytes<8> = RomBytes([21, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Copyright_1: RomBytes<8> = RomBytes([25, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Copyright_2: RomBytes<8> = RomBytes([29, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Copyright_3: RomBytes<8> = RomBytes([33, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Copyright_4: RomBytes<8> = RomBytes([37, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sStartCopyrightBannerAnimTable: [RomPtr<u8>; 10] = [
    RomPtr(sAnim_PressStart_0.as_ptr().cast::<u8>()),
    RomPtr(sAnim_PressStart_1.as_ptr().cast::<u8>()),
    RomPtr(sAnim_PressStart_2.as_ptr().cast::<u8>()),
    RomPtr(sAnim_PressStart_3.as_ptr().cast::<u8>()),
    RomPtr(sAnim_PressStart_4.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Copyright_0.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Copyright_1.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Copyright_2.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Copyright_3.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Copyright_4.as_ptr().cast::<u8>()),
];

pub(crate) static sStartCopyrightBannerSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x3e903e9 as *const u8),
    RomPtr(sOamData_CopyrightBanner.as_ptr().cast::<u8>()),
    RomPtr(sStartCopyrightBannerAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::title_screen::SpriteCB_PressStartCopyrightBanner as *const u8),
];

pub(crate) static sSpriteSheet_PressStart: [RomPtr<u8>; 4] = [
    RomPtr((&raw const crate::data::graphics::gTitleScreenPressStartGfx).cast::<u8>()),
    RomPtr(0x3e90520 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sSpritePalette_PressStart: [RomPtr<u8>; 4] = [
    RomPtr((&raw const crate::data::graphics::gTitleScreenPressStartPal).cast::<u8>()),
    RomPtr(0x3e9 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sPokemonLogoShineOamData: RomBytes<8> = RomBytes([160, 0, 0, 192, 0, 0, 0, 0]);

pub(crate) static sPokemonLogoShineAnimSequence: RomBytes<8> = RomBytes([0, 0, 4, 0, 255, 255, 0, 0]);

pub(crate) static sPokemonLogoShineAnimTable: [RomPtr<u8>; 1] = [
    RomPtr(sPokemonLogoShineAnimSequence.as_ptr().cast::<u8>()),
];

pub(crate) static sPokemonLogoShineSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x3e903ea as *const u8),
    RomPtr(sPokemonLogoShineOamData.as_ptr().cast::<u8>()),
    RomPtr(sPokemonLogoShineAnimTable.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::title_screen::SpriteCB_PokemonLogoShine as *const u8),
];

pub(crate) static sPokemonLogoShineSpriteSheet: [RomPtr<u8>; 4] = [
    RomPtr(sTitleScreenLogoShineGfx.as_ptr().cast::<u8>()),
    RomPtr(0x3ea0800 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

#[unsafe(no_mangle)]
pub static gTitleScreenAlphaBlend: RomBytes<128> = RomBytes([16, 0, 16, 1, 16, 2, 16, 3, 16, 4, 16, 5, 16, 6, 16, 7, 16, 8, 16, 9, 16, 10, 16, 11, 16, 12, 16, 13, 16, 14, 16, 15, 15, 16, 14, 16, 13, 16, 12, 16, 11, 16, 10, 16, 9, 16, 8, 16, 7, 16, 6, 16, 5, 16, 4, 16, 3, 16, 2, 16, 1, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16, 0, 16]);

