# @generated by tools/rustport/cdata.py for src/cable_car.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/cable_car/bg_mountains.bin.lz
build/assets/graphics/cable_car/bg_mountains.bin.lz := defined
build/assets/graphics/cable_car/bg_mountains.bin.lz: graphics/cable_car/bg_mountains.bin
	@mkdir -p 'build/assets/graphics/cable_car'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/cable_car/ground.bin.lz
build/assets/graphics/cable_car/ground.bin.lz := defined
build/assets/graphics/cable_car/ground.bin.lz: graphics/cable_car/ground.bin
	@mkdir -p 'build/assets/graphics/cable_car'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/cable_car/pylon_pole.bin.lz
build/assets/graphics/cable_car/pylon_pole.bin.lz := defined
build/assets/graphics/cable_car/pylon_pole.bin.lz: graphics/cable_car/pylon_pole.bin
	@mkdir -p 'build/assets/graphics/cable_car'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/cable_car/trees.bin.lz
build/assets/graphics/cable_car/trees.bin.lz := defined
build/assets/graphics/cable_car/trees.bin.lz: graphics/cable_car/trees.bin
	@mkdir -p 'build/assets/graphics/cable_car'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/cable_car/ground.bin.lz \
	build/assets/graphics/cable_car/trees.bin.lz \
	build/assets/graphics/cable_car/bg_mountains.bin.lz \
	graphics/cable_car/pylon_top.bin \
	build/assets/graphics/cable_car/pylon_pole.bin.lz
