# @generated by tools/rustport/cdata.py for src/dodrio_berry_picking.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/dodrio_berry_picking/berries.png.4bpp
build/assets/graphics/dodrio_berry_picking/berries.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/berries.png.4bpp: graphics/dodrio_berry_picking/berries.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/berries.png.gbapal
build/assets/graphics/dodrio_berry_picking/berries.png.gbapal := defined
build/assets/graphics/dodrio_berry_picking/berries.png.gbapal: graphics/dodrio_berry_picking/berries.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/bg.bin.lz
build/assets/graphics/dodrio_berry_picking/bg.bin.lz := defined
build/assets/graphics/dodrio_berry_picking/bg.bin.lz: graphics/dodrio_berry_picking/bg.bin
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/bg.png.4bpp
build/assets/graphics/dodrio_berry_picking/bg.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/bg.png.4bpp: graphics/dodrio_berry_picking/bg.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/cloud.png.4bpp
build/assets/graphics/dodrio_berry_picking/cloud.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/cloud.png.4bpp: graphics/dodrio_berry_picking/cloud.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/cloud.png.gbapal
build/assets/graphics/dodrio_berry_picking/cloud.png.gbapal := defined
build/assets/graphics/dodrio_berry_picking/cloud.png.gbapal: graphics/dodrio_berry_picking/cloud.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/dodrio.png.4bpp
build/assets/graphics/dodrio_berry_picking/dodrio.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/dodrio.png.4bpp: graphics/dodrio_berry_picking/dodrio.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/dodrio.png.gbapal
build/assets/graphics/dodrio_berry_picking/dodrio.png.gbapal := defined
build/assets/graphics/dodrio_berry_picking/dodrio.png.gbapal: graphics/dodrio_berry_picking/dodrio.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/shiny.pal.gbapal
build/assets/graphics/dodrio_berry_picking/shiny.pal.gbapal := defined
build/assets/graphics/dodrio_berry_picking/shiny.pal.gbapal: graphics/dodrio_berry_picking/shiny.pal
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/status.png.4bpp
build/assets/graphics/dodrio_berry_picking/status.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/status.png.4bpp: graphics/dodrio_berry_picking/status.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/status.png.gbapal
build/assets/graphics/dodrio_berry_picking/status.png.gbapal := defined
build/assets/graphics/dodrio_berry_picking/status.png.gbapal: graphics/dodrio_berry_picking/status.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/tree_border.png.4bpp
build/assets/graphics/dodrio_berry_picking/tree_border.png.4bpp := defined
build/assets/graphics/dodrio_berry_picking/tree_border.png.4bpp: graphics/dodrio_berry_picking/tree_border.png
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/tree_border_left.bin.lz
build/assets/graphics/dodrio_berry_picking/tree_border_left.bin.lz := defined
build/assets/graphics/dodrio_berry_picking/tree_border_left.bin.lz: graphics/dodrio_berry_picking/tree_border_left.bin
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/dodrio_berry_picking/tree_border_right.bin.lz
build/assets/graphics/dodrio_berry_picking/tree_border_right.bin.lz := defined
build/assets/graphics/dodrio_berry_picking/tree_border_right.bin.lz: graphics/dodrio_berry_picking/tree_border_right.bin
	@mkdir -p 'build/assets/graphics/dodrio_berry_picking'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/dodrio_berry_picking/dodrio.png.gbapal \
	build/assets/graphics/dodrio_berry_picking/shiny.pal.gbapal \
	build/assets/graphics/dodrio_berry_picking/status.png.gbapal \
	build/assets/graphics/dodrio_berry_picking/berries.png.gbapal \
	build/assets/graphics/dodrio_berry_picking/berries.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/cloud.png.gbapal \
	build/assets/graphics/dodrio_berry_picking/bg.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/tree_border.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/status.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/cloud.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/dodrio.png.4bpp.lz \
	build/assets/graphics/dodrio_berry_picking/bg.bin.lz \
	build/assets/graphics/dodrio_berry_picking/tree_border_right.bin.lz \
	build/assets/graphics/dodrio_berry_picking/tree_border_left.bin.lz
