# @generated by tools/rustport/cdata.py for src/link.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/link/comm_error_bg.png.4bpp
build/assets/graphics/link/comm_error_bg.png.4bpp := defined
build/assets/graphics/link/comm_error_bg.png.4bpp: graphics/link/comm_error_bg.png
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/link/test_digits.png.4bpp
build/assets/graphics/link/test_digits.png.4bpp := defined
build/assets/graphics/link/test_digits.png.4bpp: graphics/link/test_digits.png
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/link/test_digits.png.gbapal
build/assets/graphics/link/test_digits.png.gbapal := defined
build/assets/graphics/link/test_digits.png.gbapal: graphics/link/test_digits.png
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/link/wireless_display.bin.lz
build/assets/graphics/link/wireless_display.bin.lz := defined
build/assets/graphics/link/wireless_display.bin.lz: graphics/link/wireless_display.bin
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/link/wireless_display.png.4bpp
build/assets/graphics/link/wireless_display.png.4bpp := defined
build/assets/graphics/link/wireless_display.png.4bpp: graphics/link/wireless_display.png
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/link/wireless_display.png.gbapal
build/assets/graphics/link/wireless_display.png.gbapal := defined
build/assets/graphics/link/wireless_display.png.gbapal: graphics/link/wireless_display.png
	@mkdir -p 'build/assets/graphics/link'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/link/wireless_display.png.gbapal \
	build/assets/graphics/link/wireless_display.png.4bpp.lz \
	build/assets/graphics/link/wireless_display.bin.lz \
	build/assets/graphics/link/test_digits.png.gbapal \
	build/assets/graphics/link/test_digits.png.4bpp \
	build/assets/graphics/link/comm_error_bg.png.4bpp
