# @generated by tools/rustport/cdata.py for src/map_name_popup.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/map_popup/brick.png.4bpp
build/assets/graphics/map_popup/brick.png.4bpp := defined
build/assets/graphics/map_popup/brick.png.4bpp: graphics/map_popup/brick.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/brick_outline.png.4bpp
build/assets/graphics/map_popup/brick_outline.png.4bpp := defined
build/assets/graphics/map_popup/brick_outline.png.4bpp: graphics/map_popup/brick_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/brick_outline.png.gbapal
build/assets/graphics/map_popup/brick_outline.png.gbapal := defined
build/assets/graphics/map_popup/brick_outline.png.gbapal: graphics/map_popup/brick_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/marble.png.4bpp
build/assets/graphics/map_popup/marble.png.4bpp := defined
build/assets/graphics/map_popup/marble.png.4bpp: graphics/map_popup/marble.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/marble_outline.png.4bpp
build/assets/graphics/map_popup/marble_outline.png.4bpp := defined
build/assets/graphics/map_popup/marble_outline.png.4bpp: graphics/map_popup/marble_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/marble_outline.png.gbapal
build/assets/graphics/map_popup/marble_outline.png.gbapal := defined
build/assets/graphics/map_popup/marble_outline.png.gbapal: graphics/map_popup/marble_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone.png.4bpp
build/assets/graphics/map_popup/stone.png.4bpp := defined
build/assets/graphics/map_popup/stone.png.4bpp: graphics/map_popup/stone.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone2.png.4bpp
build/assets/graphics/map_popup/stone2.png.4bpp := defined
build/assets/graphics/map_popup/stone2.png.4bpp: graphics/map_popup/stone2.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone2_outline.png.4bpp
build/assets/graphics/map_popup/stone2_outline.png.4bpp := defined
build/assets/graphics/map_popup/stone2_outline.png.4bpp: graphics/map_popup/stone2_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone2_outline.png.gbapal
build/assets/graphics/map_popup/stone2_outline.png.gbapal := defined
build/assets/graphics/map_popup/stone2_outline.png.gbapal: graphics/map_popup/stone2_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone_outline.png.4bpp
build/assets/graphics/map_popup/stone_outline.png.4bpp := defined
build/assets/graphics/map_popup/stone_outline.png.4bpp: graphics/map_popup/stone_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/stone_outline.png.gbapal
build/assets/graphics/map_popup/stone_outline.png.gbapal := defined
build/assets/graphics/map_popup/stone_outline.png.gbapal: graphics/map_popup/stone_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/underwater.pal.gbapal
build/assets/graphics/map_popup/underwater.pal.gbapal := defined
build/assets/graphics/map_popup/underwater.pal.gbapal: graphics/map_popup/underwater.pal
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/underwater.png.4bpp
build/assets/graphics/map_popup/underwater.png.4bpp := defined
build/assets/graphics/map_popup/underwater.png.4bpp: graphics/map_popup/underwater.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/underwater_outline.png.4bpp
build/assets/graphics/map_popup/underwater_outline.png.4bpp := defined
build/assets/graphics/map_popup/underwater_outline.png.4bpp: graphics/map_popup/underwater_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/underwater_outline.png.gbapal
build/assets/graphics/map_popup/underwater_outline.png.gbapal := defined
build/assets/graphics/map_popup/underwater_outline.png.gbapal: graphics/map_popup/underwater_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/wood.png.4bpp
build/assets/graphics/map_popup/wood.png.4bpp := defined
build/assets/graphics/map_popup/wood.png.4bpp: graphics/map_popup/wood.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/wood.png.gbapal
build/assets/graphics/map_popup/wood.png.gbapal := defined
build/assets/graphics/map_popup/wood.png.gbapal: graphics/map_popup/wood.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/map_popup/wood_outline.png.4bpp
build/assets/graphics/map_popup/wood_outline.png.4bpp := defined
build/assets/graphics/map_popup/wood_outline.png.4bpp: graphics/map_popup/wood_outline.png
	@mkdir -p 'build/assets/graphics/map_popup'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/map_popup/underwater.pal.gbapal
