# @generated by tools/rustport/cdata.py for src/naming_screen.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/naming_screen/keyboard.pal.gbapal
build/assets/graphics/naming_screen/keyboard.pal.gbapal := defined
build/assets/graphics/naming_screen/keyboard.pal.gbapal: graphics/naming_screen/keyboard.pal
	@mkdir -p 'build/assets/graphics/naming_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/naming_screen/pc_icon_off.png.4bpp
build/assets/graphics/naming_screen/pc_icon_off.png.4bpp := defined
build/assets/graphics/naming_screen/pc_icon_off.png.4bpp: graphics/naming_screen/pc_icon_off.png
	@mkdir -p 'build/assets/graphics/naming_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/naming_screen/pc_icon_on.png.4bpp
build/assets/graphics/naming_screen/pc_icon_on.png.4bpp := defined
build/assets/graphics/naming_screen/pc_icon_on.png.4bpp: graphics/naming_screen/pc_icon_on.png
	@mkdir -p 'build/assets/graphics/naming_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/naming_screen/rival.pal.gbapal
build/assets/graphics/naming_screen/rival.pal.gbapal := defined
build/assets/graphics/naming_screen/rival.pal.gbapal: graphics/naming_screen/rival.pal
	@mkdir -p 'build/assets/graphics/naming_screen'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/naming_screen/pc_icon_off.png.4bpp \
	build/assets/graphics/naming_screen/pc_icon_on.png.4bpp \
	build/assets/graphics/naming_screen/keyboard.pal.gbapal \
	build/assets/graphics/naming_screen/rival.pal.gbapal
