# @generated by tools/rustport/cdata.py for src/pokenav_match_call_gfx.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/pokenav/match_call/call_window.pal.gbapal
build/assets/graphics/pokenav/match_call/call_window.pal.gbapal := defined
build/assets/graphics/pokenav/match_call/call_window.pal.gbapal: graphics/pokenav/match_call/call_window.pal
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/list_window.pal.gbapal
build/assets/graphics/pokenav/match_call/list_window.pal.gbapal := defined
build/assets/graphics/pokenav/match_call/list_window.pal.gbapal: graphics/pokenav/match_call/list_window.pal
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/options_cursor.png.4bpp
build/assets/graphics/pokenav/match_call/options_cursor.png.4bpp := defined
build/assets/graphics/pokenav/match_call/options_cursor.png.4bpp: graphics/pokenav/match_call/options_cursor.png
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/options_cursor.png.gbapal
build/assets/graphics/pokenav/match_call/options_cursor.png.gbapal := defined
build/assets/graphics/pokenav/match_call/options_cursor.png.gbapal: graphics/pokenav/match_call/options_cursor.png
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/pokeball.pal.gbapal
build/assets/graphics/pokenav/match_call/pokeball.pal.gbapal := defined
build/assets/graphics/pokenav/match_call/pokeball.pal.gbapal: graphics/pokenav/match_call/pokeball.pal
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/pokeball.png.4bpp
build/assets/graphics/pokenav/match_call/pokeball.png.4bpp := defined
build/assets/graphics/pokenav/match_call/pokeball.png.4bpp: graphics/pokenav/match_call/pokeball.png
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/ui.bin.lz
build/assets/graphics/pokenav/match_call/ui.bin.lz := defined
build/assets/graphics/pokenav/match_call/ui.bin.lz: graphics/pokenav/match_call/ui.bin
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/ui.png.gbapal
build/assets/graphics/pokenav/match_call/ui.png.gbapal := defined
build/assets/graphics/pokenav/match_call/ui.png.gbapal: graphics/pokenav/match_call/ui.png
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/match_call/ui.png_num_tiles_13__Wnum_tiles.4bpp
build/assets/graphics/pokenav/match_call/ui.png_num_tiles_13__Wnum_tiles.4bpp := defined
build/assets/graphics/pokenav/match_call/ui.png_num_tiles_13__Wnum_tiles.4bpp: graphics/pokenav/match_call/ui.png
	@mkdir -p 'build/assets/graphics/pokenav/match_call'
	$(GFX) $< $@ -num_tiles 13 -Wnum_tiles
endif

RUST_ASSETS += \
	build/assets/graphics/pokenav/match_call/ui.png.gbapal \
	build/assets/graphics/pokenav/match_call/ui.png_num_tiles_13__Wnum_tiles.4bpp.lz \
	build/assets/graphics/pokenav/match_call/ui.bin.lz \
	build/assets/graphics/pokenav/match_call/options_cursor.png.gbapal \
	build/assets/graphics/pokenav/match_call/options_cursor.png.4bpp.lz \
	build/assets/graphics/pokenav/match_call/call_window.pal.gbapal \
	build/assets/graphics/pokenav/match_call/list_window.pal.gbapal \
	build/assets/graphics/pokenav/match_call/pokeball.pal.gbapal \
	build/assets/graphics/pokenav/match_call/pokeball.png.4bpp.lz
