# @generated by tools/rustport/cdata.py for src/pokemon_summary_screen.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/summary_screen/a_button.png.4bpp
build/assets/graphics/summary_screen/a_button.png.4bpp := defined
build/assets/graphics/summary_screen/a_button.png.4bpp: graphics/summary_screen/a_button.png
	@mkdir -p 'build/assets/graphics/summary_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/summary_screen/b_button.png.4bpp
build/assets/graphics/summary_screen/b_button.png.4bpp := defined
build/assets/graphics/summary_screen/b_button.png.4bpp: graphics/summary_screen/b_button.png
	@mkdir -p 'build/assets/graphics/summary_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/summary_screen/markings.pal.gbapal
build/assets/graphics/summary_screen/markings.pal.gbapal := defined
build/assets/graphics/summary_screen/markings.pal.gbapal: graphics/summary_screen/markings.pal
	@mkdir -p 'build/assets/graphics/summary_screen'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	graphics/summary_screen/status_tilemap.bin \
	build/assets/graphics/summary_screen/markings.pal.gbapal
