# @generated by tools/rustport/cdata.py for src/pokenav_menu_handler_gfx.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/pokenav/bg_dots.bin.lz
build/assets/graphics/pokenav/bg_dots.bin.lz := defined
build/assets/graphics/pokenav/bg_dots.bin.lz: graphics/pokenav/bg_dots.bin
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/bg_dots.png.4bpp
build/assets/graphics/pokenav/bg_dots.png.4bpp := defined
build/assets/graphics/pokenav/bg_dots.png.4bpp: graphics/pokenav/bg_dots.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/bg_dots.png.gbapal
build/assets/graphics/pokenav/bg_dots.png.gbapal := defined
build/assets/graphics/pokenav/bg_dots.png.gbapal: graphics/pokenav/bg_dots.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/blue_light.png.4bpp
build/assets/graphics/pokenav/blue_light.png.4bpp := defined
build/assets/graphics/pokenav/blue_light.png.4bpp: graphics/pokenav/blue_light.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/blue_light.png.gbapal
build/assets/graphics/pokenav/blue_light.png.gbapal := defined
build/assets/graphics/pokenav/blue_light.png.gbapal: graphics/pokenav/blue_light.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/device_outline.png.gbapal
build/assets/graphics/pokenav/device_outline.png.gbapal := defined
build/assets/graphics/pokenav/device_outline.png.gbapal: graphics/pokenav/device_outline.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/device_outline.png_num_tiles_53__Wnum_tiles.4bpp
build/assets/graphics/pokenav/device_outline.png_num_tiles_53__Wnum_tiles.4bpp := defined
build/assets/graphics/pokenav/device_outline.png_num_tiles_53__Wnum_tiles.4bpp: graphics/pokenav/device_outline.png
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ -num_tiles 53 -Wnum_tiles
endif
ifndef build/assets/graphics/pokenav/device_outline_map.bin.lz
build/assets/graphics/pokenav/device_outline_map.bin.lz := defined
build/assets/graphics/pokenav/device_outline_map.bin.lz: graphics/pokenav/device_outline_map.bin
	@mkdir -p 'build/assets/graphics/pokenav'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/pokenav/bg_dots.png.gbapal \
	build/assets/graphics/pokenav/bg_dots.png.4bpp.lz \
	build/assets/graphics/pokenav/bg_dots.bin.lz \
	build/assets/graphics/pokenav/device_outline.png.gbapal \
	build/assets/graphics/pokenav/device_outline.png_num_tiles_53__Wnum_tiles.4bpp.lz \
	build/assets/graphics/pokenav/device_outline_map.bin.lz \
	build/assets/graphics/pokenav/blue_light.png.gbapal \
	build/assets/graphics/pokenav/blue_light.png.4bpp.lz
