# @generated by tools/rustport/cdata.py for src/region_map.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/pokenav/region_map/brendan_icon.png.4bpp
build/assets/graphics/pokenav/region_map/brendan_icon.png.4bpp := defined
build/assets/graphics/pokenav/region_map/brendan_icon.png.4bpp: graphics/pokenav/region_map/brendan_icon.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/brendan_icon.png.gbapal
build/assets/graphics/pokenav/region_map/brendan_icon.png.gbapal := defined
build/assets/graphics/pokenav/region_map/brendan_icon.png.gbapal: graphics/pokenav/region_map/brendan_icon.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/cursor.pal.gbapal
build/assets/graphics/pokenav/region_map/cursor.pal.gbapal := defined
build/assets/graphics/pokenav/region_map/cursor.pal.gbapal: graphics/pokenav/region_map/cursor.pal
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/cursor_large.png.4bpp
build/assets/graphics/pokenav/region_map/cursor_large.png.4bpp := defined
build/assets/graphics/pokenav/region_map/cursor_large.png.4bpp: graphics/pokenav/region_map/cursor_large.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/cursor_small.png.4bpp
build/assets/graphics/pokenav/region_map/cursor_small.png.4bpp := defined
build/assets/graphics/pokenav/region_map/cursor_small.png.4bpp: graphics/pokenav/region_map/cursor_small.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/fly_target_icons.png.4bpp
build/assets/graphics/pokenav/region_map/fly_target_icons.png.4bpp := defined
build/assets/graphics/pokenav/region_map/fly_target_icons.png.4bpp: graphics/pokenav/region_map/fly_target_icons.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/fly_target_icons.png.gbapal
build/assets/graphics/pokenav/region_map/fly_target_icons.png.gbapal := defined
build/assets/graphics/pokenav/region_map/fly_target_icons.png.gbapal: graphics/pokenav/region_map/fly_target_icons.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/frame.bin.lz
build/assets/graphics/pokenav/region_map/frame.bin.lz := defined
build/assets/graphics/pokenav/region_map/frame.bin.lz: graphics/pokenav/region_map/frame.bin
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/frame.png.4bpp
build/assets/graphics/pokenav/region_map/frame.png.4bpp := defined
build/assets/graphics/pokenav/region_map/frame.png.4bpp: graphics/pokenav/region_map/frame.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/frame.png.gbapal
build/assets/graphics/pokenav/region_map/frame.png.gbapal := defined
build/assets/graphics/pokenav/region_map/frame.png.gbapal: graphics/pokenav/region_map/frame.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/map.bin.lz
build/assets/graphics/pokenav/region_map/map.bin.lz := defined
build/assets/graphics/pokenav/region_map/map.bin.lz: graphics/pokenav/region_map/map.bin
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/map.pal.gbapal
build/assets/graphics/pokenav/region_map/map.pal.gbapal := defined
build/assets/graphics/pokenav/region_map/map.pal.gbapal: graphics/pokenav/region_map/map.pal
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/map.png_num_tiles_233__Wnum_tiles.8bpp
build/assets/graphics/pokenav/region_map/map.png_num_tiles_233__Wnum_tiles.8bpp := defined
build/assets/graphics/pokenav/region_map/map.png_num_tiles_233__Wnum_tiles.8bpp: graphics/pokenav/region_map/map.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ -num_tiles 233 -Wnum_tiles
endif
ifndef build/assets/graphics/pokenav/region_map/may_icon.png.4bpp
build/assets/graphics/pokenav/region_map/may_icon.png.4bpp := defined
build/assets/graphics/pokenav/region_map/may_icon.png.4bpp: graphics/pokenav/region_map/may_icon.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/pokenav/region_map/may_icon.png.gbapal
build/assets/graphics/pokenav/region_map/may_icon.png.gbapal := defined
build/assets/graphics/pokenav/region_map/may_icon.png.gbapal: graphics/pokenav/region_map/may_icon.png
	@mkdir -p 'build/assets/graphics/pokenav/region_map'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/pokenav/region_map/cursor.pal.gbapal \
	build/assets/graphics/pokenav/region_map/cursor_small.png.4bpp.lz \
	build/assets/graphics/pokenav/region_map/cursor_large.png.4bpp.lz \
	build/assets/graphics/pokenav/region_map/map.pal.gbapal \
	build/assets/graphics/pokenav/region_map/map.png_num_tiles_233__Wnum_tiles.8bpp.lz \
	build/assets/graphics/pokenav/region_map/map.bin.lz \
	build/assets/graphics/pokenav/region_map/brendan_icon.png.gbapal \
	build/assets/graphics/pokenav/region_map/brendan_icon.png.4bpp \
	build/assets/graphics/pokenav/region_map/may_icon.png.gbapal \
	build/assets/graphics/pokenav/region_map/may_icon.png.4bpp \
	build/assets/graphics/pokenav/region_map/frame.png.gbapal \
	build/assets/graphics/pokenav/region_map/frame.png.4bpp.lz \
	build/assets/graphics/pokenav/region_map/frame.bin.lz \
	build/assets/graphics/pokenav/region_map/fly_target_icons.png.gbapal \
	build/assets/graphics/pokenav/region_map/fly_target_icons.png.4bpp.lz
