# @generated by tools/rustport/cdata.py for src/rotating_gate.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/rotating_gates/l1.png.4bpp
build/assets/graphics/rotating_gates/l1.png.4bpp := defined
build/assets/graphics/rotating_gates/l1.png.4bpp: graphics/rotating_gates/l1.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/l2.png.4bpp
build/assets/graphics/rotating_gates/l2.png.4bpp := defined
build/assets/graphics/rotating_gates/l2.png.4bpp: graphics/rotating_gates/l2.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/l3.png.4bpp
build/assets/graphics/rotating_gates/l3.png.4bpp := defined
build/assets/graphics/rotating_gates/l3.png.4bpp: graphics/rotating_gates/l3.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/l4.png.4bpp
build/assets/graphics/rotating_gates/l4.png.4bpp := defined
build/assets/graphics/rotating_gates/l4.png.4bpp: graphics/rotating_gates/l4.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/t1.png.4bpp
build/assets/graphics/rotating_gates/t1.png.4bpp := defined
build/assets/graphics/rotating_gates/t1.png.4bpp: graphics/rotating_gates/t1.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/t2.png.4bpp
build/assets/graphics/rotating_gates/t2.png.4bpp := defined
build/assets/graphics/rotating_gates/t2.png.4bpp: graphics/rotating_gates/t2.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/t3.png.4bpp
build/assets/graphics/rotating_gates/t3.png.4bpp := defined
build/assets/graphics/rotating_gates/t3.png.4bpp: graphics/rotating_gates/t3.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/rotating_gates/t4.png.4bpp
build/assets/graphics/rotating_gates/t4.png.4bpp := defined
build/assets/graphics/rotating_gates/t4.png.4bpp: graphics/rotating_gates/t4.png
	@mkdir -p 'build/assets/graphics/rotating_gates'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/rotating_gates/l1.png.4bpp \
	build/assets/graphics/rotating_gates/l2.png.4bpp \
	build/assets/graphics/rotating_gates/l3.png.4bpp \
	build/assets/graphics/rotating_gates/l4.png.4bpp \
	build/assets/graphics/rotating_gates/t1.png.4bpp \
	build/assets/graphics/rotating_gates/t2.png.4bpp \
	build/assets/graphics/rotating_gates/t3.png.4bpp \
	build/assets/graphics/rotating_gates/t4.png.4bpp
