# @generated by tools/rustport/cdata.py for src/trainer_card.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/trainer_card/badges.png.4bpp
build/assets/graphics/trainer_card/badges.png.4bpp := defined
build/assets/graphics/trainer_card/badges.png.4bpp: graphics/trainer_card/badges.png
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/badges.png.gbapal
build/assets/graphics/trainer_card/badges.png.gbapal := defined
build/assets/graphics/trainer_card/badges.png.gbapal: graphics/trainer_card/badges.png
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/bronze.pal.gbapal
build/assets/graphics/trainer_card/bronze.pal.gbapal := defined
build/assets/graphics/trainer_card/bronze.pal.gbapal: graphics/trainer_card/bronze.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/copper.pal.gbapal
build/assets/graphics/trainer_card/copper.pal.gbapal := defined
build/assets/graphics/trainer_card/copper.pal.gbapal: graphics/trainer_card/copper.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/female_bg.pal.gbapal
build/assets/graphics/trainer_card/female_bg.pal.gbapal := defined
build/assets/graphics/trainer_card/female_bg.pal.gbapal: graphics/trainer_card/female_bg.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/badges.png.4bpp
build/assets/graphics/trainer_card/frlg/badges.png.4bpp := defined
build/assets/graphics/trainer_card/frlg/badges.png.4bpp: graphics/trainer_card/frlg/badges.png
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/badges.png.gbapal
build/assets/graphics/trainer_card/frlg/badges.png.gbapal := defined
build/assets/graphics/trainer_card/frlg/badges.png.gbapal: graphics/trainer_card/frlg/badges.png
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/bronze.pal.gbapal
build/assets/graphics/trainer_card/frlg/bronze.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/bronze.pal.gbapal: graphics/trainer_card/frlg/bronze.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/female_bg.pal.gbapal
build/assets/graphics/trainer_card/frlg/female_bg.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/female_bg.pal.gbapal: graphics/trainer_card/frlg/female_bg.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/gold.pal.gbapal
build/assets/graphics/trainer_card/frlg/gold.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/gold.pal.gbapal: graphics/trainer_card/frlg/gold.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/green.pal.gbapal
build/assets/graphics/trainer_card/frlg/green.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/green.pal.gbapal: graphics/trainer_card/frlg/green.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/silver.pal.gbapal
build/assets/graphics/trainer_card/frlg/silver.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/silver.pal.gbapal: graphics/trainer_card/frlg/silver.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/stickers.png.4bpp
build/assets/graphics/trainer_card/frlg/stickers.png.4bpp := defined
build/assets/graphics/trainer_card/frlg/stickers.png.4bpp: graphics/trainer_card/frlg/stickers.png
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/stickers1.pal.gbapal
build/assets/graphics/trainer_card/frlg/stickers1.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/stickers1.pal.gbapal: graphics/trainer_card/frlg/stickers1.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/stickers2.pal.gbapal
build/assets/graphics/trainer_card/frlg/stickers2.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/stickers2.pal.gbapal: graphics/trainer_card/frlg/stickers2.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/stickers3.pal.gbapal
build/assets/graphics/trainer_card/frlg/stickers3.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/stickers3.pal.gbapal: graphics/trainer_card/frlg/stickers3.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/frlg/stickers4.pal.gbapal
build/assets/graphics/trainer_card/frlg/stickers4.pal.gbapal := defined
build/assets/graphics/trainer_card/frlg/stickers4.pal.gbapal: graphics/trainer_card/frlg/stickers4.pal
	@mkdir -p 'build/assets/graphics/trainer_card/frlg'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/gold.pal.gbapal
build/assets/graphics/trainer_card/gold.pal.gbapal := defined
build/assets/graphics/trainer_card/gold.pal.gbapal: graphics/trainer_card/gold.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/silver.pal.gbapal
build/assets/graphics/trainer_card/silver.pal.gbapal := defined
build/assets/graphics/trainer_card/silver.pal.gbapal: graphics/trainer_card/silver.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/star.pal.gbapal
build/assets/graphics/trainer_card/star.pal.gbapal := defined
build/assets/graphics/trainer_card/star.pal.gbapal: graphics/trainer_card/star.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/trainer_card/unused.pal.gbapal
build/assets/graphics/trainer_card/unused.pal.gbapal := defined
build/assets/graphics/trainer_card/unused.pal.gbapal: graphics/trainer_card/unused.pal
	@mkdir -p 'build/assets/graphics/trainer_card'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/trainer_card/frlg/stickers.png.4bpp.lz \
	build/assets/graphics/trainer_card/unused.pal.gbapal \
	build/assets/graphics/trainer_card/bronze.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/green.pal.gbapal \
	build/assets/graphics/trainer_card/copper.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/bronze.pal.gbapal \
	build/assets/graphics/trainer_card/silver.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/silver.pal.gbapal \
	build/assets/graphics/trainer_card/gold.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/gold.pal.gbapal \
	build/assets/graphics/trainer_card/female_bg.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/female_bg.pal.gbapal \
	build/assets/graphics/trainer_card/badges.png.gbapal \
	build/assets/graphics/trainer_card/frlg/badges.png.gbapal \
	build/assets/graphics/trainer_card/star.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/stickers1.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/stickers2.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/stickers3.pal.gbapal \
	build/assets/graphics/trainer_card/frlg/stickers4.pal.gbapal \
	build/assets/graphics/trainer_card/badges.png.4bpp.lz \
	build/assets/graphics/trainer_card/frlg/badges.png.4bpp.lz
