# @generated by tools/rustport/cdata.py for src/trainer_hill.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/trainer_hill/ereader.pal.gbapal
build/assets/graphics/trainer_hill/ereader.pal.gbapal := defined
build/assets/graphics/trainer_hill/ereader.pal.gbapal: graphics/trainer_hill/ereader.pal
	@mkdir -p 'build/assets/graphics/trainer_hill'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/trainer_hill/ereader.pal.gbapal
