# @generated by tools/rustport/cdata.py for src/wireless_communication_status_screen.c
# Asset rules copied from scaninc's output for the original C file.

ifndef build/assets/graphics/wireless_status_screen/anim_00.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_00.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_00.pal.gbapal: graphics/wireless_status_screen/anim_00.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_01.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_01.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_01.pal.gbapal: graphics/wireless_status_screen/anim_01.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_02.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_02.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_02.pal.gbapal: graphics/wireless_status_screen/anim_02.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_03.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_03.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_03.pal.gbapal: graphics/wireless_status_screen/anim_03.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_04.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_04.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_04.pal.gbapal: graphics/wireless_status_screen/anim_04.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_05.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_05.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_05.pal.gbapal: graphics/wireless_status_screen/anim_05.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_06.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_06.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_06.pal.gbapal: graphics/wireless_status_screen/anim_06.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_07.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_07.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_07.pal.gbapal: graphics/wireless_status_screen/anim_07.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_08.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_08.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_08.pal.gbapal: graphics/wireless_status_screen/anim_08.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_09.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_09.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_09.pal.gbapal: graphics/wireless_status_screen/anim_09.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_10.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_10.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_10.pal.gbapal: graphics/wireless_status_screen/anim_10.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_11.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_11.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_11.pal.gbapal: graphics/wireless_status_screen/anim_11.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_12.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_12.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_12.pal.gbapal: graphics/wireless_status_screen/anim_12.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/anim_13.pal.gbapal
build/assets/graphics/wireless_status_screen/anim_13.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/anim_13.pal.gbapal: graphics/wireless_status_screen/anim_13.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/bg.bin.lz
build/assets/graphics/wireless_status_screen/bg.bin.lz := defined
build/assets/graphics/wireless_status_screen/bg.bin.lz: graphics/wireless_status_screen/bg.bin
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/bg.png.4bpp
build/assets/graphics/wireless_status_screen/bg.png.4bpp := defined
build/assets/graphics/wireless_status_screen/bg.png.4bpp: graphics/wireless_status_screen/bg.png
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif
ifndef build/assets/graphics/wireless_status_screen/default.pal.gbapal
build/assets/graphics/wireless_status_screen/default.pal.gbapal := defined
build/assets/graphics/wireless_status_screen/default.pal.gbapal: graphics/wireless_status_screen/default.pal
	@mkdir -p 'build/assets/graphics/wireless_status_screen'
	$(GFX) $< $@ 
endif

RUST_ASSETS += \
	build/assets/graphics/wireless_status_screen/bg.png.4bpp.lz \
	build/assets/graphics/wireless_status_screen/bg.bin.lz
