// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

#[unsafe(no_mangle)]
pub static mxMaxTime: RomBytes<24> = RomBytes([10, 0, 189, 255, 194, 0, 10, 0, 189, 255, 194, 0, 208, 7, 189, 255, 194, 0, 208, 7, 189, 255, 194, 0]);

#[unsafe(no_mangle)]
pub static MX29L010: [RomPtr<u8>; 12] = [
    RomPtr(crate::agb_flash_mx::ProgramFlashByte_MX as *const u8),
    RomPtr(crate::agb_flash_mx::ProgramFlashSector_MX as *const u8),
    RomPtr(crate::agb_flash_mx::EraseFlashChip_MX as *const u8),
    RomPtr(crate::agb_flash_mx::EraseFlashSector_MX as *const u8),
    RomPtr(crate::agb_flash_1m::WaitForFlashWrite_Common as *const u8),
    RomPtr(mxMaxTime.as_ptr().cast::<u8>()),
    RomPtr(0x20000 as *const u8),
    RomPtr(0x1000 as *const u8),
    RomPtr(0x20000c as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x10003 as *const u8),
    RomPtr(0x9c2 as *const u8),
];

#[unsafe(no_mangle)]
pub static DefaultFlash: [RomPtr<u8>; 12] = [
    RomPtr(crate::agb_flash_mx::ProgramFlashByte_MX as *const u8),
    RomPtr(crate::agb_flash_mx::ProgramFlashSector_MX as *const u8),
    RomPtr(crate::agb_flash_mx::EraseFlashChip_MX as *const u8),
    RomPtr(crate::agb_flash_mx::EraseFlashSector_MX as *const u8),
    RomPtr(crate::agb_flash_1m::WaitForFlashWrite_Common as *const u8),
    RomPtr(mxMaxTime.as_ptr().cast::<u8>()),
    RomPtr(0x20000 as *const u8),
    RomPtr(0x1000 as *const u8),
    RomPtr(0x20000c as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x10003 as *const u8),
    RomPtr(0x0 as *const u8),
];

