// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sAnim_ToxicBubble: RomBytes<20> = RomBytes([0, 0, 5, 0, 8, 0, 5, 0, 16, 0, 5, 0, 24, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_ToxicBubble: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_ToxicBubble.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_PoisonProjectile: RomBytes<8> = RomBytes([0, 0, 1, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_AcidPoisonDroplet: RomBytes<8> = RomBytes([4, 0, 1, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_SludgeBombHit: RomBytes<8> = RomBytes([8, 0, 1, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_PoisonProjectile: [RomPtr<u8>; 3] = [
    RomPtr(sAnim_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(sAnim_AcidPoisonDroplet.as_ptr().cast::<u8>()),
    RomPtr(sAnim_SludgeBombHit.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_PoisonProjectile: RomBytes<32> = RomBytes([96, 1, 96, 1, 0, 0, 0, 0, 246, 255, 246, 255, 0, 10, 0, 0, 10, 0, 10, 0, 0, 10, 0, 0, 254, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_SludgeBombHit: RomBytes<16> = RomBytes([236, 0, 236, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_PoisonProjectile: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_PoisonProjectile.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnims_SludgeBombHit: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_SludgeBombHit.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_AcidPoisonDroplet: RomBytes<24> = RomBytes([240, 255, 16, 0, 0, 6, 0, 0, 16, 0, 240, 255, 0, 6, 0, 0, 254, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_Bubble: RomBytes<24> = RomBytes([156, 0, 156, 0, 0, 0, 0, 0, 5, 0, 5, 0, 0, 20, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_Bubble: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_Bubble.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gToxicBubbleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a727a7 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x32).cast::<u8>()),
    RomPtr(sAnims_ToxicBubble.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_mons::AnimSpriteOnMonPos as *const u8),
];

#[unsafe(no_mangle)]
pub static gSludgeProjectileSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a627a6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineDouble_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimSludgeProjectile as *const u8),
];

#[unsafe(no_mangle)]
pub static gAcidPoisonBubbleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a627a6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineDouble_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimAcidPoisonBubble as *const u8),
];

#[unsafe(no_mangle)]
pub static gSludgeBombHitParticleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a627a6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_PoisonProjectile.as_ptr().cast::<u8>().wrapping_byte_offset(8)),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_SludgeBombHit.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimSludgeBombHitParticle as *const u8),
];

#[unsafe(no_mangle)]
pub static gAffineAnims_Droplet: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_AcidPoisonDroplet.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gAcidPoisonDropletSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a627a6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineDouble_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_PoisonProjectile.as_ptr().cast::<u8>().wrapping_byte_offset(4)),
    RomPtr(0x0 as *const u8),
    RomPtr(gAffineAnims_Droplet.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimAcidPoisonDroplet as *const u8),
];

#[unsafe(no_mangle)]
pub static gPoisonBubbleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27a627a6 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_PoisonProjectile.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_Bubble.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimBubbleEffect as *const u8),
];

#[unsafe(no_mangle)]
pub static gWaterBubbleSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27ab27ab as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjBlend_16x16).cast::<u8>()),
    RomPtr((&raw const crate::data::battle_anim_water::gAnims_WaterBubble).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_Bubble.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_poison::AnimBubbleEffect as *const u8),
];

