// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sScriptConditionTable: RomBytes<18> = RomBytes([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1]);

pub(crate) static sScriptStringVars: [RomPtr<u8>; 3] = [
    RomPtr((&raw const crate::string_util::gStringVar1).cast::<u8>()),
    RomPtr((&raw const crate::string_util::gStringVar2).cast::<u8>()),
    RomPtr((&raw const crate::string_util::gStringVar3).cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gNullScriptPtr: RomBytes<4> = RomBytes([0, 0, 0, 0]);

