// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static AgbLibRtcVersion: RomBytes<12> = RomBytes([83, 73, 73, 82, 84, 67, 95, 86, 48, 48, 49, 0]);

