//! Generated by tools/rustport/gen_consts.py: the constants of include/battle_pyramid_bag.h
//! that the game code uses.

pub const PBAG_SPRITE_BAG: i32 = 0;
pub const PYRAMIDBAG_LOC_FIELD: u8 = 0;
pub const PBAG_SPRITE_ITEM_ICON: i32 = 1;
pub const PYRAMIDBAG_LOC_BATTLE: u8 = 1;
pub const PYRAMIDBAG_LOC_PARTY: u8 = 2;
pub const PBAG_SPRITE_SWAP_LINE_START: i32 = 3;
pub const PYRAMIDBAG_LOC_CHOOSE_TOSS: u8 = 3;
pub const PYRAMIDBAG_LOC_PREV: u8 = 4;
pub const PBAG_SPRITE_SWAP_LINE_END: i32 = 10;
