//! Generated by tools/rustport/gen_consts.py: the constants of include/berry_blender.h
//! that the game code uses.

pub const BLENDER_COMM_INPUT_STATE: i32 = 0;
pub const BLENDER_COMM_RESP: i32 = 1;
pub const BLENDER_COMM_SCORE: i32 = 2;
pub const BLENDER_COMM_STOP_TYPE: i32 = 2;
pub const BLENDER_COMM_PLAYER_ID: i32 = 3;
pub const BLENDER_COMM_PROGRESS_BAR: i32 = 5;
pub const BLENDER_COMM_ARROW_POS: i32 = 6;
