//! Generated by tools/rustport/gen_consts.py: the constants of include/string_util.h
//! that the game code uses.

pub const STR_CONV_MODE_LEFT_ALIGN: i32 = 0;
pub const STR_CONV_MODE_RIGHT_ALIGN: i32 = 1;
pub const STR_CONV_MODE_LEADING_ZEROS: i32 = 2;
