//! Generated by tools/rustport/gen_types.py from include/apprentice.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct ApprenticeTrainer`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct ApprenticeTrainer {
    pub name: CArray<CArray<u8, 8>, 6>,
    pub otId: u16,
    pub facilityClass: u8,
    pub species: CArray<u16, 10>,
    pub id: u8,
    pub speechLost: CArray<u16, 6>,
}

unsafe impl Sync for ApprenticeTrainer {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<ApprenticeTrainer>() == 88);
    assert!(offset_of!(ApprenticeTrainer, name) == 0);
    assert!(offset_of!(ApprenticeTrainer, otId) == 48);
    assert!(offset_of!(ApprenticeTrainer, facilityClass) == 50);
    assert!(offset_of!(ApprenticeTrainer, species) == 52);
    assert!(offset_of!(ApprenticeTrainer, id) == 72);
    assert!(offset_of!(ApprenticeTrainer, speechLost) == 74);
};
