//! Generated by tools/rustport/gen_types.py from include/battle_tower.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct RSBattleTowerRecord`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RSBattleTowerRecord {
    pub lvlMode: u8,
    pub facilityClass: u8,
    pub winStreak: u16,
    pub name: CArray<u8, 8>,
    pub trainerId: CArray<u8, 4>,
    pub greeting: CArray<u16, 6>,
    pub party: CArray<BattleTowerPokemon, 3>,
    pub checksum: u32,
}

unsafe impl Sync for RSBattleTowerRecord {}

/// `struct BattleFrontierTrainer`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct BattleFrontierTrainer {
    pub facilityClass: u8,
    pub filler1: CArray<u8, 3>,
    pub trainerName: CArray<u8, 8>,
    pub speechBefore: CArray<u16, 6>,
    pub speechWin: CArray<u16, 6>,
    pub speechLose: CArray<u16, 6>,
    pub monSet: *mut u16,
}

unsafe impl Sync for BattleFrontierTrainer {}

/// `struct FacilityMon`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct FacilityMon {
    pub species: u16,
    pub moves: CArray<u16, 4>,
    pub itemTableId: u8,
    pub evSpread: u8,
    pub nature: u8,
}

unsafe impl Sync for FacilityMon {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<RSBattleTowerRecord>() == 164);
    assert!(offset_of!(RSBattleTowerRecord, lvlMode) == 0);
    assert!(offset_of!(RSBattleTowerRecord, facilityClass) == 1);
    assert!(offset_of!(RSBattleTowerRecord, winStreak) == 2);
    assert!(offset_of!(RSBattleTowerRecord, name) == 4);
    assert!(offset_of!(RSBattleTowerRecord, trainerId) == 12);
    assert!(offset_of!(RSBattleTowerRecord, greeting) == 16);
    assert!(offset_of!(RSBattleTowerRecord, party) == 28);
    assert!(offset_of!(RSBattleTowerRecord, checksum) == 160);
    assert!(size_of::<BattleFrontierTrainer>() == 52);
    assert!(offset_of!(BattleFrontierTrainer, facilityClass) == 0);
    assert!(offset_of!(BattleFrontierTrainer, filler1) == 1);
    assert!(offset_of!(BattleFrontierTrainer, trainerName) == 4);
    assert!(offset_of!(BattleFrontierTrainer, speechBefore) == 12);
    assert!(offset_of!(BattleFrontierTrainer, speechWin) == 24);
    assert!(offset_of!(BattleFrontierTrainer, speechLose) == 36);
    assert!(offset_of!(BattleFrontierTrainer, monSet) == 48);
    assert!(size_of::<FacilityMon>() == 16);
    assert!(offset_of!(FacilityMon, species) == 0);
    assert!(offset_of!(FacilityMon, moves) == 2);
    assert!(offset_of!(FacilityMon, itemTableId) == 10);
    assert!(offset_of!(FacilityMon, evSpread) == 11);
    assert!(offset_of!(FacilityMon, nature) == 12);
};
