//! Generated by tools/rustport/gen_types.py from include/data.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct MonCoords`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct MonCoords {
    pub size: u8,
    pub y_offset: u8,
}

unsafe impl Sync for MonCoords {}

/// `struct TrainerMonNoItemDefaultMoves`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct TrainerMonNoItemDefaultMoves {
    pub iv: u16,
    pub lvl: u8,
    pub species: u16,
}

unsafe impl Sync for TrainerMonNoItemDefaultMoves {}

/// `struct TrainerMonItemDefaultMoves`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct TrainerMonItemDefaultMoves {
    pub iv: u16,
    pub lvl: u8,
    pub species: u16,
    pub heldItem: u16,
}

unsafe impl Sync for TrainerMonItemDefaultMoves {}

/// `struct TrainerMonNoItemCustomMoves`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct TrainerMonNoItemCustomMoves {
    pub iv: u16,
    pub lvl: u8,
    pub species: u16,
    pub moves: CArray<u16, 4>,
}

unsafe impl Sync for TrainerMonNoItemCustomMoves {}

/// `struct TrainerMonItemCustomMoves`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct TrainerMonItemCustomMoves {
    pub iv: u16,
    pub lvl: u8,
    pub species: u16,
    pub heldItem: u16,
    pub moves: CArray<u16, 4>,
}

unsafe impl Sync for TrainerMonItemCustomMoves {}

/// `union TrainerMonPtr`
#[repr(C)]
#[derive(Clone, Copy)]
pub union TrainerMonPtr {
    pub NoItemDefaultMoves: *mut TrainerMonNoItemDefaultMoves,
    pub NoItemCustomMoves: *mut TrainerMonNoItemCustomMoves,
    pub ItemDefaultMoves: *mut TrainerMonItemDefaultMoves,
    pub ItemCustomMoves: *mut TrainerMonItemCustomMoves,
}

unsafe impl Sync for TrainerMonPtr {}

/// `struct Trainer`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Trainer {
    pub partyFlags: u8,
    pub trainerClass: u8,
    pub encounterMusic_gender: u8,
    pub trainerPic: u8,
    pub trainerName: CArray<u8, 11>,
    pub items: CArray<u16, 4>,
    pub doubleBattle: u8,
    pub aiFlags: u32,
    pub partySize: u8,
    pub party: TrainerMonPtr,
}

unsafe impl Sync for Trainer {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<MonCoords>() == 4);
    assert!(offset_of!(MonCoords, size) == 0);
    assert!(offset_of!(MonCoords, y_offset) == 1);
    assert!(size_of::<TrainerMonNoItemDefaultMoves>() == 8);
    assert!(offset_of!(TrainerMonNoItemDefaultMoves, iv) == 0);
    assert!(offset_of!(TrainerMonNoItemDefaultMoves, lvl) == 2);
    assert!(offset_of!(TrainerMonNoItemDefaultMoves, species) == 4);
    assert!(size_of::<TrainerMonItemDefaultMoves>() == 8);
    assert!(offset_of!(TrainerMonItemDefaultMoves, iv) == 0);
    assert!(offset_of!(TrainerMonItemDefaultMoves, lvl) == 2);
    assert!(offset_of!(TrainerMonItemDefaultMoves, species) == 4);
    assert!(offset_of!(TrainerMonItemDefaultMoves, heldItem) == 6);
    assert!(size_of::<TrainerMonNoItemCustomMoves>() == 16);
    assert!(offset_of!(TrainerMonNoItemCustomMoves, iv) == 0);
    assert!(offset_of!(TrainerMonNoItemCustomMoves, lvl) == 2);
    assert!(offset_of!(TrainerMonNoItemCustomMoves, species) == 4);
    assert!(offset_of!(TrainerMonNoItemCustomMoves, moves) == 6);
    assert!(size_of::<TrainerMonItemCustomMoves>() == 16);
    assert!(offset_of!(TrainerMonItemCustomMoves, iv) == 0);
    assert!(offset_of!(TrainerMonItemCustomMoves, lvl) == 2);
    assert!(offset_of!(TrainerMonItemCustomMoves, species) == 4);
    assert!(offset_of!(TrainerMonItemCustomMoves, heldItem) == 6);
    assert!(offset_of!(TrainerMonItemCustomMoves, moves) == 8);
    assert!(size_of::<TrainerMonPtr>() == 4);
    assert!(size_of::<Trainer>() == 40);
    assert!(offset_of!(Trainer, partyFlags) == 0);
    assert!(offset_of!(Trainer, trainerClass) == 1);
    assert!(offset_of!(Trainer, encounterMusic_gender) == 2);
    assert!(offset_of!(Trainer, trainerPic) == 3);
    assert!(offset_of!(Trainer, trainerName) == 4);
    assert!(offset_of!(Trainer, items) == 16);
    assert!(offset_of!(Trainer, doubleBattle) == 24);
    assert!(offset_of!(Trainer, aiFlags) == 28);
    assert!(offset_of!(Trainer, partySize) == 32);
    assert!(offset_of!(Trainer, party) == 36);
};
