//! Generated by tools/rustport/gen_types.py from include/decoration.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct Decoration`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Decoration {
    pub id: u8,
    pub name: CArray<u8, 16>,
    pub permission: u8,
    pub shape: u8,
    pub category: u8,
    pub price: u16,
    pub description: *mut u8,
    pub tiles: *mut u16,
}

unsafe impl Sync for Decoration {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<Decoration>() == 32);
    assert!(offset_of!(Decoration, id) == 0);
    assert!(offset_of!(Decoration, name) == 1);
    assert!(offset_of!(Decoration, permission) == 17);
    assert!(offset_of!(Decoration, shape) == 18);
    assert!(offset_of!(Decoration, category) == 19);
    assert!(offset_of!(Decoration, price) == 20);
    assert!(offset_of!(Decoration, description) == 24);
    assert!(offset_of!(Decoration, tiles) == 28);
};
