//! Generated by tools/rustport/gen_types.py from include/save.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct SaveSectorLocation`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SaveSectorLocation {
    pub data: *mut core::ffi::c_void,
    pub size: u16,
}

unsafe impl Sync for SaveSectorLocation {}

/// `struct SaveSector`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SaveSector {
    pub data: CArray<u8, 3968>,
    pub unused: CArray<u8, 116>,
    pub id: u16,
    pub checksum: u16,
    pub signature: u32,
    pub counter: u32,
}

unsafe impl Sync for SaveSector {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<SaveSectorLocation>() == 8);
    assert!(offset_of!(SaveSectorLocation, data) == 0);
    assert!(offset_of!(SaveSectorLocation, size) == 4);
    assert!(size_of::<SaveSector>() == 4096);
    assert!(offset_of!(SaveSector, data) == 0);
    assert!(offset_of!(SaveSector, unused) == 3968);
    assert!(offset_of!(SaveSector, id) == 4084);
    assert!(offset_of!(SaveSector, checksum) == 4086);
    assert!(offset_of!(SaveSector, signature) == 4088);
    assert!(offset_of!(SaveSector, counter) == 4092);
};
