//! Generated by tools/rustport/gen_types.py from include/sprite.h: the C types, with GCC's layout.
#![allow(non_camel_case_types, non_snake_case)]

use super::*;
use crate::c::CArray;
use core::mem::{offset_of, size_of};

/// `struct SpriteSheet`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SpriteSheet {
    pub data: *mut core::ffi::c_void,
    pub size: u16,
    pub tag: u16,
}

unsafe impl Sync for SpriteSheet {}

/// `struct CompressedSpriteSheet`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CompressedSpriteSheet {
    pub data: *mut u32,
    pub size: u16,
    pub tag: u16,
}

unsafe impl Sync for CompressedSpriteSheet {}

/// `struct SpriteFrameImage`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SpriteFrameImage {
    pub data: *mut core::ffi::c_void,
    pub size: u16,
}

unsafe impl Sync for SpriteFrameImage {}

/// `struct SpritePalette`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SpritePalette {
    pub data: *mut u16,
    pub tag: u16,
}

unsafe impl Sync for SpritePalette {}

/// `struct CompressedSpritePalette`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CompressedSpritePalette {
    pub data: *mut u32,
    pub tag: u16,
}

unsafe impl Sync for CompressedSpritePalette {}

/// `struct AnimFrameCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AnimFrameCmd {
    bits_0: u16,
    bits_2: u8,
}

impl AnimFrameCmd {
    #[inline(always)]
    pub fn imageValue(&self) -> u32 {
        ((self.bits_0 as u32 >> 0) & 0xffff) as u32
    }
    #[inline(always)]
    pub fn set_imageValue(&mut self, v: u32) {
        self.bits_0 = (self.bits_0 & !(0xffff << 0)) | ((v as u16 & 0xffff) << 0);
    }
    #[inline(always)]
    pub fn duration(&self) -> u32 {
        ((self.bits_2 as u32 >> 0) & 0x3f) as u32
    }
    #[inline(always)]
    pub fn set_duration(&mut self, v: u32) {
        self.bits_2 = (self.bits_2 & !(0x3f << 0)) | ((v as u8 & 0x3f) << 0);
    }
    #[inline(always)]
    pub fn hFlip(&self) -> u32 {
        ((self.bits_2 as u32 >> 6) & 0x1) as u32
    }
    #[inline(always)]
    pub fn set_hFlip(&mut self, v: u32) {
        self.bits_2 = (self.bits_2 & !(0x1 << 6)) | ((v as u8 & 0x1) << 6);
    }
    #[inline(always)]
    pub fn vFlip(&self) -> u32 {
        ((self.bits_2 as u32 >> 7) & 0x1) as u32
    }
    #[inline(always)]
    pub fn set_vFlip(&mut self, v: u32) {
        self.bits_2 = (self.bits_2 & !(0x1 << 7)) | ((v as u8 & 0x1) << 7);
    }
}

unsafe impl Sync for AnimFrameCmd {}

/// `struct AnimLoopCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AnimLoopCmd {
    bits_0: u16,
    bits_2: u8,
}

impl AnimLoopCmd {
    #[inline(always)]
    pub fn r#type(&self) -> u32 {
        ((self.bits_0 as u32 >> 0) & 0xffff) as u32
    }
    #[inline(always)]
    pub fn set_type(&mut self, v: u32) {
        self.bits_0 = (self.bits_0 & !(0xffff << 0)) | ((v as u16 & 0xffff) << 0);
    }
    #[inline(always)]
    pub fn count(&self) -> u32 {
        ((self.bits_2 as u32 >> 0) & 0x3f) as u32
    }
    #[inline(always)]
    pub fn set_count(&mut self, v: u32) {
        self.bits_2 = (self.bits_2 & !(0x3f << 0)) | ((v as u8 & 0x3f) << 0);
    }
}

unsafe impl Sync for AnimLoopCmd {}

/// `struct AnimJumpCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AnimJumpCmd {
    bits_0: u16,
    bits_2: u8,
}

impl AnimJumpCmd {
    #[inline(always)]
    pub fn r#type(&self) -> u32 {
        ((self.bits_0 as u32 >> 0) & 0xffff) as u32
    }
    #[inline(always)]
    pub fn set_type(&mut self, v: u32) {
        self.bits_0 = (self.bits_0 & !(0xffff << 0)) | ((v as u16 & 0xffff) << 0);
    }
    #[inline(always)]
    pub fn target(&self) -> u32 {
        ((self.bits_2 as u32 >> 0) & 0x3f) as u32
    }
    #[inline(always)]
    pub fn set_target(&mut self, v: u32) {
        self.bits_2 = (self.bits_2 & !(0x3f << 0)) | ((v as u8 & 0x3f) << 0);
    }
}

unsafe impl Sync for AnimJumpCmd {}

/// `union AnimCmd`
#[repr(C)]
#[derive(Clone, Copy)]
pub union AnimCmd {
    pub r#type: i16,
    pub frame: AnimFrameCmd,
    pub r#loop: AnimLoopCmd,
    pub jump: AnimJumpCmd,
}

unsafe impl Sync for AnimCmd {}

/// `struct AffineAnimFrameCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AffineAnimFrameCmd {
    pub xScale: i16,
    pub yScale: i16,
    pub rotation: u8,
    pub duration: u8,
}

unsafe impl Sync for AffineAnimFrameCmd {}

/// `struct AffineAnimLoopCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AffineAnimLoopCmd {
    pub r#type: i16,
    pub count: i16,
}

unsafe impl Sync for AffineAnimLoopCmd {}

/// `struct AffineAnimJumpCmd`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AffineAnimJumpCmd {
    pub r#type: i16,
    pub target: u16,
}

unsafe impl Sync for AffineAnimJumpCmd {}

/// `struct AffineAnimEndCmdAlt`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AffineAnimEndCmdAlt {
    pub r#type: i16,
    pub val: u16,
}

unsafe impl Sync for AffineAnimEndCmdAlt {}

/// `union AffineAnimCmd`
#[repr(C)]
#[derive(Clone, Copy)]
pub union AffineAnimCmd {
    pub r#type: i16,
    pub frame: AffineAnimFrameCmd,
    pub r#loop: AffineAnimLoopCmd,
    pub jump: AffineAnimJumpCmd,
    pub end: AffineAnimEndCmdAlt,
}

unsafe impl Sync for AffineAnimCmd {}

/// `struct AffineAnimState`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct AffineAnimState {
    pub animNum: u8,
    pub animCmdIndex: u8,
    pub delayCounter: u8,
    pub loopCounter: u8,
    pub xScale: i16,
    pub yScale: i16,
    pub rotation: u16,
}

unsafe impl Sync for AffineAnimState {}

/// `struct Subsprite`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct Subsprite {
    pub x: i8,
    pub y: i8,
    bits_2: u16,
}

impl Subsprite {
    #[inline(always)]
    pub fn shape(&self) -> u16 {
        ((self.bits_2 as u32 >> 0) & 0x3) as u16
    }
    #[inline(always)]
    pub fn set_shape(&mut self, v: u16) {
        self.bits_2 = (self.bits_2 & !(0x3 << 0)) | ((v as u16 & 0x3) << 0);
    }
    #[inline(always)]
    pub fn size(&self) -> u16 {
        ((self.bits_2 as u32 >> 2) & 0x3) as u16
    }
    #[inline(always)]
    pub fn set_size(&mut self, v: u16) {
        self.bits_2 = (self.bits_2 & !(0x3 << 2)) | ((v as u16 & 0x3) << 2);
    }
    #[inline(always)]
    pub fn tileOffset(&self) -> u16 {
        ((self.bits_2 as u32 >> 4) & 0x3ff) as u16
    }
    #[inline(always)]
    pub fn set_tileOffset(&mut self, v: u16) {
        self.bits_2 = (self.bits_2 & !(0x3ff << 4)) | ((v as u16 & 0x3ff) << 4);
    }
    #[inline(always)]
    pub fn priority(&self) -> u16 {
        ((self.bits_2 as u32 >> 14) & 0x3) as u16
    }
    #[inline(always)]
    pub fn set_priority(&mut self, v: u16) {
        self.bits_2 = (self.bits_2 & !(0x3 << 14)) | ((v as u16 & 0x3) << 14);
    }
}

unsafe impl Sync for Subsprite {}

/// `struct SubspriteTable`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SubspriteTable {
    pub subspriteCount: u8,
    pub subsprites: *mut Subsprite,
}

unsafe impl Sync for SubspriteTable {}

/// `struct SpriteTemplate`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SpriteTemplate {
    pub tileTag: u16,
    pub paletteTag: u16,
    pub oam: *mut OamData,
    pub anims: *mut *mut AnimCmd,
    pub images: *mut SpriteFrameImage,
    pub affineAnims: *mut *mut AffineAnimCmd,
    pub callback: Option<unsafe extern "C" fn(*mut Sprite)>,
}

unsafe impl Sync for SpriteTemplate {}

/// `struct Sprite`
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Sprite {
    pub oam: OamData,
    pub anims: *mut *mut AnimCmd,
    pub images: *mut SpriteFrameImage,
    pub affineAnims: *mut *mut AffineAnimCmd,
    pub template: *mut SpriteTemplate,
    pub subspriteTables: *mut SubspriteTable,
    pub callback: Option<unsafe extern "C" fn(*mut Sprite)>,
    pub x: i16,
    pub y: i16,
    pub x2: i16,
    pub y2: i16,
    pub centerToCornerVecX: i8,
    pub centerToCornerVecY: i8,
    pub animNum: u8,
    pub animCmdIndex: u8,
    bits_44: u8,
    pub animLoopCounter: u8,
    pub data: CArray<i16, 8>,
    bits_62: u8,
    bits_63: u8,
    pub sheetTileStart: u16,
    bits_66: u8,
    pub subpriority: u8,
}

impl Sprite {
    #[inline(always)]
    pub fn animDelayCounter(&self) -> u8 {
        ((self.bits_44 as u32 >> 0) & 0x3f) as u8
    }
    #[inline(always)]
    pub fn set_animDelayCounter(&mut self, v: u8) {
        self.bits_44 = (self.bits_44 & !(0x3f << 0)) | ((v as u8 & 0x3f) << 0);
    }
    #[inline(always)]
    pub fn animPaused(&self) -> u8 {
        ((self.bits_44 as u32 >> 6) & 0x1) as u8
    }
    #[inline(always)]
    pub fn set_animPaused(&mut self, v: u8) {
        self.bits_44 = (self.bits_44 & !(0x1 << 6)) | ((v as u8 & 0x1) << 6);
    }
    #[inline(always)]
    pub fn affineAnimPaused(&self) -> u8 {
        ((self.bits_44 as u32 >> 7) & 0x1) as u8
    }
    #[inline(always)]
    pub fn set_affineAnimPaused(&mut self, v: u8) {
        self.bits_44 = (self.bits_44 & !(0x1 << 7)) | ((v as u8 & 0x1) << 7);
    }
    #[inline(always)]
    pub fn inUse(&self) -> u16 {
        ((self.bits_62 as u32 >> 0) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_inUse(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 0)) | ((v as u8 & 0x1) << 0);
    }
    #[inline(always)]
    pub fn coordOffsetEnabled(&self) -> u16 {
        ((self.bits_62 as u32 >> 1) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_coordOffsetEnabled(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 1)) | ((v as u8 & 0x1) << 1);
    }
    #[inline(always)]
    pub fn invisible(&self) -> u16 {
        ((self.bits_62 as u32 >> 2) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_invisible(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 2)) | ((v as u8 & 0x1) << 2);
    }
    #[inline(always)]
    pub fn flags_3(&self) -> u16 {
        ((self.bits_62 as u32 >> 3) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_flags_3(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 3)) | ((v as u8 & 0x1) << 3);
    }
    #[inline(always)]
    pub fn flags_4(&self) -> u16 {
        ((self.bits_62 as u32 >> 4) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_flags_4(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 4)) | ((v as u8 & 0x1) << 4);
    }
    #[inline(always)]
    pub fn flags_5(&self) -> u16 {
        ((self.bits_62 as u32 >> 5) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_flags_5(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 5)) | ((v as u8 & 0x1) << 5);
    }
    #[inline(always)]
    pub fn flags_6(&self) -> u16 {
        ((self.bits_62 as u32 >> 6) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_flags_6(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 6)) | ((v as u8 & 0x1) << 6);
    }
    #[inline(always)]
    pub fn flags_7(&self) -> u16 {
        ((self.bits_62 as u32 >> 7) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_flags_7(&mut self, v: u16) {
        self.bits_62 = (self.bits_62 & !(0x1 << 7)) | ((v as u8 & 0x1) << 7);
    }
    #[inline(always)]
    pub fn hFlip(&self) -> u16 {
        ((self.bits_63 as u32 >> 0) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_hFlip(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 0)) | ((v as u8 & 0x1) << 0);
    }
    #[inline(always)]
    pub fn vFlip(&self) -> u16 {
        ((self.bits_63 as u32 >> 1) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_vFlip(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 1)) | ((v as u8 & 0x1) << 1);
    }
    #[inline(always)]
    pub fn animBeginning(&self) -> u16 {
        ((self.bits_63 as u32 >> 2) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_animBeginning(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 2)) | ((v as u8 & 0x1) << 2);
    }
    #[inline(always)]
    pub fn affineAnimBeginning(&self) -> u16 {
        ((self.bits_63 as u32 >> 3) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_affineAnimBeginning(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 3)) | ((v as u8 & 0x1) << 3);
    }
    #[inline(always)]
    pub fn animEnded(&self) -> u16 {
        ((self.bits_63 as u32 >> 4) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_animEnded(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 4)) | ((v as u8 & 0x1) << 4);
    }
    #[inline(always)]
    pub fn affineAnimEnded(&self) -> u16 {
        ((self.bits_63 as u32 >> 5) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_affineAnimEnded(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 5)) | ((v as u8 & 0x1) << 5);
    }
    #[inline(always)]
    pub fn usingSheet(&self) -> u16 {
        ((self.bits_63 as u32 >> 6) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_usingSheet(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 6)) | ((v as u8 & 0x1) << 6);
    }
    #[inline(always)]
    pub fn anchored(&self) -> u16 {
        ((self.bits_63 as u32 >> 7) & 0x1) as u16
    }
    #[inline(always)]
    pub fn set_anchored(&mut self, v: u16) {
        self.bits_63 = (self.bits_63 & !(0x1 << 7)) | ((v as u8 & 0x1) << 7);
    }
    #[inline(always)]
    pub fn subspriteTableNum(&self) -> u8 {
        ((self.bits_66 as u32 >> 0) & 0x3f) as u8
    }
    #[inline(always)]
    pub fn set_subspriteTableNum(&mut self, v: u8) {
        self.bits_66 = (self.bits_66 & !(0x3f << 0)) | ((v as u8 & 0x3f) << 0);
    }
    #[inline(always)]
    pub fn subspriteMode(&self) -> u8 {
        ((self.bits_66 as u32 >> 6) & 0x3) as u8
    }
    #[inline(always)]
    pub fn set_subspriteMode(&mut self, v: u8) {
        self.bits_66 = (self.bits_66 & !(0x3 << 6)) | ((v as u8 & 0x3) << 6);
    }
}

unsafe impl Sync for Sprite {}

/// `struct OamMatrix`
#[repr(C, align(4))]
#[derive(Clone, Copy)]
pub struct OamMatrix {
    pub a: i16,
    pub b: i16,
    pub c: i16,
    pub d: i16,
}

unsafe impl Sync for OamMatrix {}

#[cfg(target_arch = "arm")]
const _: () = {
    assert!(size_of::<SpriteSheet>() == 8);
    assert!(offset_of!(SpriteSheet, data) == 0);
    assert!(offset_of!(SpriteSheet, size) == 4);
    assert!(offset_of!(SpriteSheet, tag) == 6);
    assert!(size_of::<CompressedSpriteSheet>() == 8);
    assert!(offset_of!(CompressedSpriteSheet, data) == 0);
    assert!(offset_of!(CompressedSpriteSheet, size) == 4);
    assert!(offset_of!(CompressedSpriteSheet, tag) == 6);
    assert!(size_of::<SpriteFrameImage>() == 8);
    assert!(offset_of!(SpriteFrameImage, data) == 0);
    assert!(offset_of!(SpriteFrameImage, size) == 4);
    assert!(size_of::<SpritePalette>() == 8);
    assert!(offset_of!(SpritePalette, data) == 0);
    assert!(offset_of!(SpritePalette, tag) == 4);
    assert!(size_of::<CompressedSpritePalette>() == 8);
    assert!(offset_of!(CompressedSpritePalette, data) == 0);
    assert!(offset_of!(CompressedSpritePalette, tag) == 4);
    assert!(size_of::<AnimFrameCmd>() == 4);
    assert!(offset_of!(AnimFrameCmd, bits_0) == 0);
    assert!(offset_of!(AnimFrameCmd, bits_2) == 2);
    assert!(size_of::<AnimLoopCmd>() == 4);
    assert!(offset_of!(AnimLoopCmd, bits_0) == 0);
    assert!(offset_of!(AnimLoopCmd, bits_2) == 2);
    assert!(size_of::<AnimJumpCmd>() == 4);
    assert!(offset_of!(AnimJumpCmd, bits_0) == 0);
    assert!(offset_of!(AnimJumpCmd, bits_2) == 2);
    assert!(size_of::<AnimCmd>() == 4);
    assert!(size_of::<AffineAnimFrameCmd>() == 8);
    assert!(offset_of!(AffineAnimFrameCmd, xScale) == 0);
    assert!(offset_of!(AffineAnimFrameCmd, yScale) == 2);
    assert!(offset_of!(AffineAnimFrameCmd, rotation) == 4);
    assert!(offset_of!(AffineAnimFrameCmd, duration) == 5);
    assert!(size_of::<AffineAnimLoopCmd>() == 4);
    assert!(offset_of!(AffineAnimLoopCmd, r#type) == 0);
    assert!(offset_of!(AffineAnimLoopCmd, count) == 2);
    assert!(size_of::<AffineAnimJumpCmd>() == 4);
    assert!(offset_of!(AffineAnimJumpCmd, r#type) == 0);
    assert!(offset_of!(AffineAnimJumpCmd, target) == 2);
    assert!(size_of::<AffineAnimEndCmdAlt>() == 4);
    assert!(offset_of!(AffineAnimEndCmdAlt, r#type) == 0);
    assert!(offset_of!(AffineAnimEndCmdAlt, val) == 2);
    assert!(size_of::<AffineAnimCmd>() == 8);
    assert!(size_of::<AffineAnimState>() == 12);
    assert!(offset_of!(AffineAnimState, animNum) == 0);
    assert!(offset_of!(AffineAnimState, animCmdIndex) == 1);
    assert!(offset_of!(AffineAnimState, delayCounter) == 2);
    assert!(offset_of!(AffineAnimState, loopCounter) == 3);
    assert!(offset_of!(AffineAnimState, xScale) == 4);
    assert!(offset_of!(AffineAnimState, yScale) == 6);
    assert!(offset_of!(AffineAnimState, rotation) == 8);
    assert!(size_of::<Subsprite>() == 4);
    assert!(offset_of!(Subsprite, x) == 0);
    assert!(offset_of!(Subsprite, y) == 1);
    assert!(offset_of!(Subsprite, bits_2) == 2);
    assert!(size_of::<SubspriteTable>() == 8);
    assert!(offset_of!(SubspriteTable, subspriteCount) == 0);
    assert!(offset_of!(SubspriteTable, subsprites) == 4);
    assert!(size_of::<SpriteTemplate>() == 24);
    assert!(offset_of!(SpriteTemplate, tileTag) == 0);
    assert!(offset_of!(SpriteTemplate, paletteTag) == 2);
    assert!(offset_of!(SpriteTemplate, oam) == 4);
    assert!(offset_of!(SpriteTemplate, anims) == 8);
    assert!(offset_of!(SpriteTemplate, images) == 12);
    assert!(offset_of!(SpriteTemplate, affineAnims) == 16);
    assert!(offset_of!(SpriteTemplate, callback) == 20);
    assert!(size_of::<Sprite>() == 68);
    assert!(offset_of!(Sprite, oam) == 0);
    assert!(offset_of!(Sprite, anims) == 8);
    assert!(offset_of!(Sprite, images) == 12);
    assert!(offset_of!(Sprite, affineAnims) == 16);
    assert!(offset_of!(Sprite, template) == 20);
    assert!(offset_of!(Sprite, subspriteTables) == 24);
    assert!(offset_of!(Sprite, callback) == 28);
    assert!(offset_of!(Sprite, x) == 32);
    assert!(offset_of!(Sprite, y) == 34);
    assert!(offset_of!(Sprite, x2) == 36);
    assert!(offset_of!(Sprite, y2) == 38);
    assert!(offset_of!(Sprite, centerToCornerVecX) == 40);
    assert!(offset_of!(Sprite, centerToCornerVecY) == 41);
    assert!(offset_of!(Sprite, animNum) == 42);
    assert!(offset_of!(Sprite, animCmdIndex) == 43);
    assert!(offset_of!(Sprite, bits_44) == 44);
    assert!(offset_of!(Sprite, animLoopCounter) == 45);
    assert!(offset_of!(Sprite, data) == 46);
    assert!(offset_of!(Sprite, bits_62) == 62);
    assert!(offset_of!(Sprite, bits_63) == 63);
    assert!(offset_of!(Sprite, sheetTileStart) == 64);
    assert!(offset_of!(Sprite, bits_66) == 66);
    assert!(offset_of!(Sprite, subpriority) == 67);
    assert!(size_of::<OamMatrix>() == 8);
    assert!(offset_of!(OamMatrix, a) == 0);
    assert!(offset_of!(OamMatrix, b) == 2);
    assert!(offset_of!(OamMatrix, c) == 4);
    assert!(offset_of!(OamMatrix, d) == 6);
};
