// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sAnim_FireSpiralSpread_0: RomBytes<16> = RomBytes([16, 0, 4, 0, 32, 0, 4, 0, 48, 0, 4, 0, 254, 255, 0, 0]);

pub(crate) static sAnim_FireSpiralSpread_1: RomBytes<16> = RomBytes([16, 0, 196, 0, 32, 0, 196, 0, 48, 0, 196, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_FireSpiralSpread: [RomPtr<u8>; 2] = [
    RomPtr(sAnim_FireSpiralSpread_0.as_ptr().cast::<u8>()),
    RomPtr(sAnim_FireSpiralSpread_1.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_LargeFlame: RomBytes<36> = RomBytes([0, 0, 3, 0, 16, 0, 3, 0, 32, 0, 3, 0, 48, 0, 3, 0, 64, 0, 3, 0, 80, 0, 3, 0, 96, 0, 3, 0, 112, 0, 3, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_LargeFlame: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_LargeFlame.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_FirePlume: RomBytes<24> = RomBytes([0, 0, 5, 0, 16, 0, 5, 0, 32, 0, 5, 0, 48, 0, 5, 0, 64, 0, 5, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_FirePlume: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_FirePlume.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_LargeFlame: RomBytes<24> = RomBytes([50, 0, 0, 1, 0, 0, 0, 0, 32, 0, 0, 0, 0, 7, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_LargeFlame: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_LargeFlame.as_ptr().cast::<u8>()),
];

pub(crate) static sUnusedEmberFirePlumeSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_FirePlume.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFirePlume as *const u8),
];

pub(crate) static sAnim_UnusedSmallEmber: RomBytes<16> = RomBytes([16, 0, 6, 0, 32, 0, 6, 0, 48, 0, 6, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_UnusedSmallEmber: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_UnusedSmallEmber.as_ptr().cast::<u8>()),
];

pub(crate) static sUnusedSmallEmberSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_UnusedSmallEmber.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimUnusedSmallEmber as *const u8),
];

pub(crate) static sAffineAnim_SunlightRay: RomBytes<24> = RomBytes([80, 0, 80, 0, 0, 0, 0, 0, 2, 0, 2, 0, 10, 1, 0, 0, 254, 127, 1, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_SunlightRay: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_SunlightRay.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_BasicFire: RomBytes<24> = RomBytes([0, 0, 4, 0, 16, 0, 4, 0, 32, 0, 4, 0, 48, 0, 4, 0, 64, 0, 4, 0, 254, 255, 0, 0]);

pub(crate) static sAnim_FireBlastCross: RomBytes<12> = RomBytes([32, 0, 6, 0, 48, 0, 6, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_FireBlastCross: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_FireBlastCross.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_Unused_0: RomBytes<16> = RomBytes([0, 0, 0, 0, 0, 1, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_Unused_1: RomBytes<16> = RomBytes([160, 0, 160, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_Unused: [RomPtr<u8>; 2] = [
    RomPtr(sAffineAnim_Unused_0.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_Unused_1.as_ptr().cast::<u8>()),
];

pub(crate) static sEruptionLaunchRockSpeeds: RomBytes<28> = RomBytes([254, 255, 251, 255, 255, 255, 255, 255, 3, 0, 250, 255, 4, 0, 254, 255, 2, 0, 248, 255, 251, 255, 251, 255, 4, 0, 249, 255]);

pub(crate) static sAnim_WillOWispOrb_0: RomBytes<20> = RomBytes([0, 0, 5, 0, 4, 0, 5, 0, 8, 0, 5, 0, 12, 0, 5, 0, 254, 255, 0, 0]);

pub(crate) static sAnim_WillOWispOrb_1: RomBytes<8> = RomBytes([16, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_WillOWispOrb_2: RomBytes<8> = RomBytes([20, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_WillOWispOrb_3: RomBytes<8> = RomBytes([20, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_WillOWispOrb: [RomPtr<u8>; 4] = [
    RomPtr(sAnim_WillOWispOrb_0.as_ptr().cast::<u8>()),
    RomPtr(sAnim_WillOWispOrb_1.as_ptr().cast::<u8>()),
    RomPtr(sAnim_WillOWispOrb_2.as_ptr().cast::<u8>()),
    RomPtr(sAnim_WillOWispOrb_3.as_ptr().cast::<u8>()),
];

pub(crate) static sAnim_WillOWispFire: RomBytes<20> = RomBytes([0, 0, 5, 0, 16, 0, 5, 0, 32, 0, 5, 0, 48, 0, 5, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_WillOWispFire: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_WillOWispFire.as_ptr().cast::<u8>()),
];

pub(crate) static sShakeDirsPattern0: RomBytes<16> = RomBytes([255, 255, 0, 1, 1, 0, 0, 255, 255, 1, 1, 0, 0, 255, 0, 1]);

pub(crate) static sShakeDirsPattern1: RomBytes<16> = RomBytes([255, 0, 1, 0, 255, 1, 0, 255, 0, 1, 0, 255, 0, 1, 0, 1]);

#[unsafe(no_mangle)]
pub static gFireSpiralInwardSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_FireSpiralSpread.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFireSpiralInward as *const u8),
];

#[unsafe(no_mangle)]
pub static gFireSpreadSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_FireSpiralSpread.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFireSpread as *const u8),
];

#[unsafe(no_mangle)]
pub static gLargeFlameSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27312731 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_LargeFlame.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_LargeFlame.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimLargeFlame as *const u8),
];

#[unsafe(no_mangle)]
pub static gLargeFlameScatterSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27312731 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_LargeFlame.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimLargeFlame as *const u8),
];

#[unsafe(no_mangle)]
pub static gFirePlumeSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27332733 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_FirePlume.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFirePlume as *const u8),
];

#[unsafe(no_mangle)]
pub static gSunlightRaySpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27ad27ad as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineNormal_ObjBlend_32x32).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_SunlightRay.as_ptr().cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimSunlight as *const u8),
];

#[unsafe(no_mangle)]
pub static gAnims_BasicFire: [RomPtr<u8>; 1] = [
    RomPtr(sAnim_BasicFire.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gEmberSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_mons::TranslateAnimSpriteToTargetMonLocation as *const u8),
];

#[unsafe(no_mangle)]
pub static gEmberFlareSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(gAnims_BasicFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimEmberFlare as *const u8),
];

#[unsafe(no_mangle)]
pub static gBurnFlameSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(gAnims_BasicFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimBurnFlame as *const u8),
];

#[unsafe(no_mangle)]
pub static gFireBlastRingSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(gAnims_BasicFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFireRing as *const u8),
];

#[unsafe(no_mangle)]
pub static gFireBlastCrossSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_FireBlastCross.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFireCross as *const u8),
];

#[unsafe(no_mangle)]
pub static gFireSpiralOutwardSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(gAnims_BasicFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimFireSpiralOutward as *const u8),
];

#[unsafe(no_mangle)]
pub static gWeatherBallFireDownSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x272d272d as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(gAnims_BasicFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_mons::AnimWeatherBallDown as *const u8),
];

#[unsafe(no_mangle)]
pub static gEruptionLaunchRockSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27d927d9 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x16).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimEruptionLaunchRock as *const u8),
];

#[unsafe(no_mangle)]
pub static gEruptionFallingRockSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27d927d9 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimEruptionFallingRock as *const u8),
];

#[unsafe(no_mangle)]
pub static gWillOWispOrbSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27f727f7 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_16x16).cast::<u8>()),
    RomPtr(sAnims_WillOWispOrb.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimWillOWispOrb as *const u8),
];

#[unsafe(no_mangle)]
pub static gWillOWispFireSpriteTemplate: [RomPtr<u8>; 6] = [
    RomPtr(0x27f827f8 as *const u8),
    RomPtr((&raw const crate::data::battle_anim::gOamData_AffineOff_ObjNormal_32x32).cast::<u8>()),
    RomPtr(sAnims_WillOWispFire.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::battle_anim_fire::AnimWillOWispFire as *const u8),
];

