// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

unsafe extern "C" {
    static BattleFrontier_ExchangeServiceCorner_Text_BrightpowderDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_CalciumDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_CarbosDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ChikoritaDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ChoiceBandDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ClefairyDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_CyndaquilDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_DittoDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_FocusBandDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_HPUpDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_IronDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_KingsRockDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_KissCushionDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_KissPosterDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_LeftoversDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_MentalHerbDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_MeowthDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ProteinDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_QuickClawDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ScopeLensDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_SmoochumDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_TogepiDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_TotodileDollDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_WhiteHerbDesc: u8;
    static BattleFrontier_ExchangeServiceCorner_Text_ZincDesc: u8;
    static BattleFrontier_Lounge2_Text_ArenaTycoonGoldMons: u8;
    static BattleFrontier_Lounge2_Text_ArenaTycoonIsThere: u8;
    static BattleFrontier_Lounge2_Text_ArenaTycoonSilverMons: u8;
    static BattleFrontier_Lounge2_Text_DomeAceGoldMons: u8;
    static BattleFrontier_Lounge2_Text_DomeAceIsThere: u8;
    static BattleFrontier_Lounge2_Text_DomeAceSilverMons: u8;
    static BattleFrontier_Lounge2_Text_DoubleBattleAdvice1: u8;
    static BattleFrontier_Lounge2_Text_DoubleBattleAdvice2: u8;
    static BattleFrontier_Lounge2_Text_DoubleBattleAdvice3: u8;
    static BattleFrontier_Lounge2_Text_FactoryHeadGoldMons: u8;
    static BattleFrontier_Lounge2_Text_FactoryHeadIsThere: u8;
    static BattleFrontier_Lounge2_Text_FactoryHeadSilverMons: u8;
    static BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice: u8;
    static BattleFrontier_Lounge2_Text_MultiBattleAdvice: u8;
    static BattleFrontier_Lounge2_Text_PalaceMavenGoldMons: u8;
    static BattleFrontier_Lounge2_Text_PalaceMavenIsThere: u8;
    static BattleFrontier_Lounge2_Text_PalaceMavenSilverMons: u8;
    static BattleFrontier_Lounge2_Text_PikeQueenGoldMons: u8;
    static BattleFrontier_Lounge2_Text_PikeQueenIsThere: u8;
    static BattleFrontier_Lounge2_Text_PikeQueenSilverMons: u8;
    static BattleFrontier_Lounge2_Text_PyramidKingGoldMons: u8;
    static BattleFrontier_Lounge2_Text_PyramidKingIsThere: u8;
    static BattleFrontier_Lounge2_Text_PyramidKingSilverMons: u8;
    static BattleFrontier_Lounge2_Text_SalonMaidenGoldMons: u8;
    static BattleFrontier_Lounge2_Text_SalonMaidenIsThere: u8;
    static BattleFrontier_Lounge2_Text_SalonMaidenSilverMons: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleArena: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattlePike: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattlePyramid: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti: u8;
    static BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleArena: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleDomeDouble: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleDomeSingle: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleFactorySingle: u8;
    static BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble: u8;
    static BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle: u8;
    static BattleFrontier_Lounge3_Text_GetToBattlePike: u8;
    static BattleFrontier_Lounge3_Text_GetToBattlePyramid: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleTowerDouble: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleTowerMulti: u8;
    static BattleFrontier_Lounge3_Text_GetToBattleTowerSingle: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlAdamant: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlBashful: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlBold: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlBrave: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlCalm: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlCareful: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlGentle: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlHardy: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlHasty: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlImpish: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlJolly: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlLax: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlLonely: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlMild: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlModest: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlNaughty: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlRash: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlRelaxed: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlSassy: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlSerious: u8;
    static BattleFrontier_Lounge5_Text_NatureGirlTimid: u8;
    static BattleFrontier_Lounge7_Text_BodySlamDesc: u8;
    static BattleFrontier_Lounge7_Text_CounterDesc: u8;
    static BattleFrontier_Lounge7_Text_DefenseCurlDesc: u8;
    static BattleFrontier_Lounge7_Text_DreamEaterDesc: u8;
    static BattleFrontier_Lounge7_Text_EndureDesc: u8;
    static BattleFrontier_Lounge7_Text_FirePunchDesc: u8;
    static BattleFrontier_Lounge7_Text_IcePunchDesc: u8;
    static BattleFrontier_Lounge7_Text_IcyWindDesc: u8;
    static BattleFrontier_Lounge7_Text_MegaKickDesc: u8;
    static BattleFrontier_Lounge7_Text_MegaPunchDesc: u8;
    static BattleFrontier_Lounge7_Text_MudSlapDesc: u8;
    static BattleFrontier_Lounge7_Text_PsychUpDesc: u8;
    static BattleFrontier_Lounge7_Text_RockSlideDesc: u8;
    static BattleFrontier_Lounge7_Text_SeismicTossDesc: u8;
    static BattleFrontier_Lounge7_Text_SnoreDesc: u8;
    static BattleFrontier_Lounge7_Text_SoftboiledDesc: u8;
    static BattleFrontier_Lounge7_Text_SwiftDesc: u8;
    static BattleFrontier_Lounge7_Text_SwordsDanceDesc: u8;
    static BattleFrontier_Lounge7_Text_ThunderPunchDesc: u8;
    static BattleFrontier_Lounge7_Text_ThunderWaveDesc: u8;
}

pub(crate) static sMauvilleGymSwitchCoords: RomBytes<16> = RomBytes([7, 22, 0, 0, 11, 19, 0, 0, 10, 16, 0, 0, 15, 16, 0, 0]);

pub(crate) static sSlidingDoorNextFrameDelay: RomBytes<5> = RomBytes([0, 1, 1, 1, 1]);

pub(crate) static sPetalburgGymSlidingDoorMetatiles: RomBytes<10> = RomBytes([24, 2, 25, 2, 26, 2, 27, 2, 28, 2]);

pub(crate) static CSWTCH_385: RomBytes<3> = RomBytes([0, 255, 1]);

pub(crate) static CSWTCH_383: RomBytes<6> = RomBytes([5, 0, 127, 2, 126, 2]);

pub(crate) static CSWTCH_382: RomBytes<6> = RomBytes([4, 0, 90, 2, 89, 2]);

pub(crate) static CSWTCH_388: RomBytes<3> = RomBytes([0, 255, 1]);

pub(crate) static sSlotMachineRandomSeeds_34: RomBytes<12> = RomBytes([12, 2, 4, 5, 1, 8, 7, 11, 3, 10, 9, 6]);

pub(crate) static sSlotMachineIds_32: RomBytes<12> = RomBytes([0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 5]);

pub(crate) static sSlotMachineServiceDayIds_33: RomBytes<12> = RomBytes([3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5]);

pub(crate) static sWindowTemplate_ElevatorFloor: RomBytes<8> = RomBytes([0, 21, 1, 8, 4, 15, 8, 0]);

pub(crate) static sDeptStoreFloorNames: [RomPtr<u8>; 16] = [
    RomPtr((&raw const crate::data::strings::gText_B4F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_B3F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_B2F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_B1F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_1F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_2F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_3F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_4F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_5F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_6F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_7F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_8F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_9F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_10F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_11F).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Rooftop).cast::<u8>()),
];

pub(crate) static sElevatorWindowTiles_Ascending: RomBytes<18> = RomBytes([41, 3, 42, 3, 43, 3, 49, 3, 50, 3, 51, 3, 57, 3, 58, 3, 59, 3]);

pub(crate) static sElevatorWindowTiles_Descending: RomBytes<18> = RomBytes([41, 3, 43, 3, 42, 3, 49, 3, 51, 3, 50, 3, 57, 3, 59, 3, 58, 3]);

pub(crate) static CSWTCH_442: RomBytes<5> = RomBytes([5, 6, 7, 8, 15]);

pub(crate) static sElevatorTripLength_31: RomBytes<9> = RomBytes([8, 16, 24, 32, 38, 46, 52, 56, 57]);

pub(crate) static sElevatorLightCycles_30: RomBytes<9> = RomBytes([3, 6, 9, 12, 15, 18, 21, 24, 27]);

pub(crate) static sPokemonCenters_29: RomBytes<38> = RomBytes([2, 2, 1, 3, 5, 4, 4, 5, 4, 6, 0, 7, 4, 8, 11, 9, 5, 10, 5, 11, 2, 12, 6, 13, 3, 14, 2, 15, 12, 16, 10, 16, 53, 26, 60, 25, 255, 255]);

pub(crate) static sFrontierManiacStreakThresholds_28: RomBytes<20> = RomBytes([21, 56, 21, 35, 255, 255, 255, 255, 2, 4, 7, 21, 7, 21, 14, 28, 13, 112, 7, 56]);

pub(crate) static sFrontierManiacMessages_27: [RomPtr<u8>; 30] = [
    RomPtr((&raw const BattleFrontier_Lounge2_Text_SalonMaidenIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_SalonMaidenSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_SalonMaidenGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DoubleBattleAdvice1)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DoubleBattleAdvice2)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DoubleBattleAdvice3)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_MultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_MultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_MultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DomeAceIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DomeAceSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_DomeAceGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_FactoryHeadIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_FactoryHeadSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_FactoryHeadGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PalaceMavenIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PalaceMavenSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PalaceMavenGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_ArenaTycoonIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_ArenaTycoonSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_ArenaTycoonGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PikeQueenIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PikeQueenSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PikeQueenGoldMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PyramidKingIsThere)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PyramidKingSilverMons)),
    RomPtr((&raw const BattleFrontier_Lounge2_Text_PyramidKingGoldMons)),
];

pub(crate) static sBattleTowerStreakThresholds_26: RomBytes<20> = RomBytes([7, 0, 14, 0, 21, 0, 28, 0, 35, 0, 49, 0, 63, 0, 77, 0, 91, 0, 0, 0]);

pub(crate) static sScrollableMultichoiceOptions: [RomPtr<u8>; 208] = [
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BlueFlute).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_YellowFlute).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_RedFlute).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WhiteFlute).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BlackFlute).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PrettyChair).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PrettyDesk).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_0Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_10Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_20Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_30Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_40Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_50Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_60Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_70Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_80Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_90Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_100Pts).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_QuestionMark).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_KissPoster16BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_KissCushion32BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SmoochumDoll32BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_TogepiDoll48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MeowthDoll48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ClefairyDoll48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_DittoDoll48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_CyndaquilDoll80BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ChikoritaDoll80BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_TotodileDoll80BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_LaprasDoll128BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SnorlaxDoll128BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_VenusaurDoll256BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_CharizardDoll256BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BlastoiseDoll256BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Protein1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Calcium1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Iron1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Zinc1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Carbos1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_HpUp1BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Leftovers48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WhiteHerb48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_QuickClaw48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MentalHerb48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BrightPowder64BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ChoiceBand64BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_KingsRock64BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_FocusBand64BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ScopeLens64BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_EnergyPowder50).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_EnergyRoot80).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_HealPowder50).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_RevivalHerb300).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Protein1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Iron1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Carbos1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Calcium1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Zinc1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_HPUp1000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PPUp3000).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BattleTower2).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattleDome).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattlePalace).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattleArena).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattleFactory).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattlePike).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattlePyramid).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_RankingHall).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ExchangeService).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_Softboiled16BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SeismicToss24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_DreamEater24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MegaPunch24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MegaKick48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BodySlam48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_RockSlide48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Counter48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ThunderWave48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SwordsDance48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_DefenseCurl16BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Snore24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MudSlap24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Swift24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_IcyWind24BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Endure48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PsychUp48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_IcePunch48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_ThunderPunch48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_FirePunch48BP).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_SlateportCity).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattleFrontier).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SouthernIsland).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_NavelRock).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BirthIsland).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_FarawayIsland).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BattleTrainers).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_BattleBasics).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PokemonNature).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_PokemonMoves).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Underpowered).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WhenInDanger).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sBattleFrontierTutor_WindowTemplate_10: RomBytes<8> = RomBytes([0, 1, 7, 12, 6, 15, 28, 0]);

pub(crate) static sScrollableMultichoice_ScrollArrowsTemplate_25: RomBytes<16> = RomBytes([2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 208, 7, 100, 0, 0, 0]);

pub(crate) static sNatureGirlMessages_24: [RomPtr<u8>; 25] = [
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlHardy)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlLonely)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlBrave)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlAdamant)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlNaughty)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlBold)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlRelaxed)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlImpish)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlLax)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlTimid)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlHasty)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlSerious)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlJolly)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlModest)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlMild)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlBashful)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlRash)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlCalm)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlGentle)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlSassy)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlCareful)),
    RomPtr((&raw const BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky)),
];

pub(crate) static sFrontierGamblerLookingMessages_23: [RomPtr<u8>; 12] = [
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattleArena)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattlePike)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_ChallengeBattlePyramid)),
];

pub(crate) static sFrontierGamblerGoMessages_22: [RomPtr<u8>; 12] = [
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleTowerSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleTowerDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleTowerMulti)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleDomeSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleDomeDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleFactorySingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattleArena)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattlePike)),
    RomPtr((&raw const BattleFrontier_Lounge3_Text_GetToBattlePyramid)),
];

pub(crate) static sFrontierChallenges_21: RomBytes<24> = RomBytes([0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 4, 1, 4, 0, 2, 1, 2, 0, 3, 0, 5, 0, 6]);

pub(crate) static sBattlePoints_WindowTemplate_20: RomBytes<8> = RomBytes([0, 1, 1, 6, 2, 15, 8, 0]);

pub(crate) static sFrontierExchangeCorner_ItemIconWindowTemplate_19: RomBytes<8> = RomBytes([0, 2, 9, 4, 4, 15, 20, 0]);

pub(crate) static sBattleFrontier_TutorMoves1: RomBytes<20> = RomBytes([135, 0, 69, 0, 138, 0, 5, 0, 25, 0, 34, 0, 157, 0, 68, 0, 86, 0, 14, 0]);

pub(crate) static sBattleFrontier_TutorMoves2: RomBytes<20> = RomBytes([111, 0, 173, 0, 189, 0, 129, 0, 196, 0, 203, 0, 244, 0, 8, 0, 9, 0, 7, 0]);

pub(crate) static sDeoxysRockPalettes: RomBytes<352> = RomBytes([14, 83, 214, 90, 82, 74, 107, 49, 231, 36, 31, 124, 31, 124, 31, 124, 31, 124, 31, 124, 31, 124, 31, 124, 31, 124, 31, 124, 123, 111, 0, 0, 14, 83, 214, 86, 51, 70, 76, 45, 199, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 215, 86, 20, 66, 45, 41, 168, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 216, 86, 245, 61, 15, 37, 169, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 249, 82, 215, 57, 16, 33, 138, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 250, 82, 216, 57, 242, 32, 139, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 251, 82, 185, 53, 211, 28, 108, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 28, 79, 155, 49, 212, 24, 77, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 29, 79, 124, 45, 182, 20, 78, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 30, 79, 93, 41, 151, 16, 47, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 83, 63, 79, 95, 41, 153, 16, 48, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sDeoxysRockCoords: RomBytes<22> = RomBytes([15, 12, 11, 14, 15, 8, 19, 14, 12, 11, 18, 11, 15, 14, 11, 14, 19, 14, 15, 15, 15, 10]);

pub(crate) static sStoneMaxStepCounts_7: RomBytes<10> = RomBytes([4, 8, 8, 8, 4, 4, 4, 6, 3, 3]);

pub(crate) static sAbnormalWeatherMapNumbers_6: RomBytes<16> = RomBytes([29, 29, 30, 30, 31, 31, 33, 33, 20, 20, 40, 40, 42, 42, 44, 44]);

pub(crate) static sAbnormalWeatherMapNumbers_5: RomBytes<16> = RomBytes([29, 29, 30, 30, 31, 31, 33, 33, 20, 20, 40, 40, 42, 42, 44, 44]);

pub(crate) static sPokeMarts_4: RomBytes<36> = RomBytes([2, 4, 1, 4, 4, 1, 5, 0, 1, 6, 3, 1, 8, 6, 1, 9, 13, 1, 10, 7, 1, 11, 7, 1, 12, 4, 1, 14, 5, 1, 15, 4, 1, 26, 55, 1]);

pub(crate) static sPokemonCenters_3: RomBytes<44> = RomBytes([2, 2, 1, 3, 5, 4, 4, 5, 4, 6, 0, 7, 4, 8, 11, 9, 5, 10, 5, 11, 2, 12, 6, 13, 3, 14, 2, 15, 12, 16, 10, 16, 53, 26, 24, 25, 25, 25, 26, 25, 27, 25, 255, 255]);

pub(crate) static sCounterIncrements_2: RomBytes<4> = RomBytes([2, 1, 2, 1]);

pub(crate) static sFanClubMemberIds_1: RomBytes<8> = RomBytes([8, 9, 10, 11, 12, 13, 14, 15]);

pub(crate) static sFanClubMemberIds_0: RomBytes<8> = RomBytes([8, 13, 14, 11, 10, 12, 15, 9]);

pub(crate) static CSWTCH_523: RomBytes<5> = RomBytes([0, 0, 1, 0, 1]);

pub(crate) static CSWTCH_524: RomBytes<5> = RomBytes([3, 1, 0, 4, 5]);

pub(crate) static sFrontierExchangeCorner_Decor1Descriptions_18: [RomPtr<u8>; 11] = [
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_KissPosterDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_KissCushionDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_SmoochumDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_TogepiDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_MeowthDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ClefairyDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_DittoDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_CyndaquilDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ChikoritaDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_TotodileDollDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

pub(crate) static sFrontierExchangeCorner_Decor1_17: RomBytes<22> = RomBytes([75, 0, 103, 0, 87, 0, 79, 0, 84, 0, 85, 0, 86, 0, 80, 0, 81, 0, 82, 0, 255, 255]);

pub(crate) static sFrontierExchangeCorner_Decor2Descriptions_16: [RomPtr<u8>; 6] = [
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

pub(crate) static sFrontierExchangeCorner_Decor2_15: RomBytes<12> = RomBytes([113, 0, 111, 0, 114, 0, 115, 0, 116, 0, 255, 255]);

pub(crate) static sFrontierExchangeCorner_VitaminsDescriptions_14: [RomPtr<u8>; 7] = [
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ProteinDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_CalciumDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_IronDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ZincDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_CarbosDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_HPUpDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

pub(crate) static sFrontierExchangeCorner_Vitamins_13: RomBytes<14> = RomBytes([64, 0, 67, 0, 65, 0, 70, 0, 66, 0, 63, 0, 255, 255]);

pub(crate) static sFrontierExchangeCorner_HoldItemsDescriptions_12: [RomPtr<u8>; 10] = [
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_LeftoversDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_WhiteHerbDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_QuickClawDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_MentalHerbDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_BrightpowderDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ChoiceBandDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_KingsRockDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_FocusBandDesc)),
    RomPtr((&raw const BattleFrontier_ExchangeServiceCorner_Text_ScopeLensDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

pub(crate) static sFrontierExchangeCorner_HoldItems_11: RomBytes<20> = RomBytes([200, 0, 180, 0, 183, 0, 185, 0, 179, 0, 186, 0, 187, 0, 196, 0, 198, 0, 255, 255]);

pub(crate) static sBattleFrontier_TutorMoveDescriptions2_9: [RomPtr<u8>; 11] = [
    RomPtr((&raw const BattleFrontier_Lounge7_Text_DefenseCurlDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_SnoreDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_MudSlapDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_SwiftDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_IcyWindDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_EndureDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_PsychUpDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_IcePunchDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_ThunderPunchDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_FirePunchDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

pub(crate) static sBattleFrontier_TutorMoveDescriptions1_8: [RomPtr<u8>; 11] = [
    RomPtr((&raw const BattleFrontier_Lounge7_Text_SoftboiledDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_SeismicTossDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_DreamEaterDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_MegaPunchDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_MegaKickDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_BodySlamDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_RockSlideDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_CounterDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_ThunderWaveDesc)),
    RomPtr((&raw const BattleFrontier_Lounge7_Text_SwordsDanceDesc)),
    RomPtr((&raw const crate::data::strings::gText_Exit).cast::<u8>()),
];

