// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
// Command: tools/rustport/cdata.py --all src/mystery_gift_scripts.c
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sText_CanceledReadingCard: RomBytes<27> = RomBytes([189, 213, 226, 215, 217, 224, 217, 216, 0, 230, 217, 213, 216, 221, 226, 219, 254, 232, 220, 217, 0, 189, 213, 230, 216, 173, 255]);

pub(crate) static sClientScript_SendGameData: RomBytes<32> = RomBytes([8, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sClientScript_CantAccept: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0]);

pub(crate) static sClientScript_CommError: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 11, 0, 0, 0]);

pub(crate) static sClientScript_NothingSent: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sClientScript_SaveCard: RomBytes<48> = RomBytes([2, 0, 0, 0, 22, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 25, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0]);

pub(crate) static sClientScript_SaveNews: RomBytes<40> = RomBytes([2, 0, 0, 0, 23, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sClientScript_HadNews: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0]);

pub(crate) static sClientScript_NewsReceived: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0]);

pub(crate) static sClientScript_AskToss: RomBytes<40> = RomBytes([13, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sClientScript_Canceled: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0]);

pub(crate) static sClientScript_HadCard: RomBytes<16> = RomBytes([20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0]);

pub(crate) static sClientScript_DynamicError: RomBytes<32> = RomBytes([2, 0, 0, 0, 21, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 14, 0, 0, 0]);

pub(crate) static sClientScript_DynamicSuccess: RomBytes<32> = RomBytes([2, 0, 0, 0, 21, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 13, 0, 0, 0]);

pub(crate) static sServerScript_CantSend: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_CantAccept.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xa as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_CommError: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_CommError.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xb as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_ClientCanceledNews: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_Canceled.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x9 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_ClientCanceledCard: [RomPtr<u8>; 18] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x20 as *const u8),
    RomPtr(sClientScript_DynamicError.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x1b as *const u8),
    RomPtr(sText_CanceledReadingCard.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x9 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_HasNews: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_HadNews.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x7 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_SendNews: [RomPtr<u8>; 33] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x28 as *const u8),
    RomPtr(sClientScript_SaveNews.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xe as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x13 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x8 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x4 as *const u8),
    RomPtr(0x1 as *const u8),
    RomPtr(sServerScript_HasNews.as_ptr().cast::<u8>()),
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_NewsReceived.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x3 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_SendCard: [RomPtr<u8>; 24] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x30 as *const u8),
    RomPtr(sClientScript_SaveCard.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xd as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0xf as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_TossPrompt: [RomPtr<u8>; 18] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x28 as *const u8),
    RomPtr(sClientScript_AskToss.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x13 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x8 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x4 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_SendCard.as_ptr().cast::<u8>()),
    RomPtr(0x3 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_ClientCanceledCard.as_ptr().cast::<u8>()),
];

pub(crate) static sServerScript_HasCard: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_HadCard.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x5 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sServerScript_NothingSent: [RomPtr<u8>; 12] = [
    RomPtr(0x12 as *const u8),
    RomPtr(0x10 as *const u8),
    RomPtr(sClientScript_NothingSent.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x14 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

#[unsafe(no_mangle)]
pub static gMysteryGiftClientScript_Init: RomBytes<16> = RomBytes([2, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]);

#[unsafe(no_mangle)]
pub static gMysteryGiftServerScript_SendWonderNews: [RomPtr<u8>; 24] = [
    RomPtr(0x1b as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x12 as *const u8),
    RomPtr(0x20 as *const u8),
    RomPtr(sClientScript_SendGameData.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x11 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x5 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x1e as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x4 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_CantSend.as_ptr().cast::<u8>()),
    RomPtr(0x3 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_SendNews.as_ptr().cast::<u8>()),
];

#[unsafe(no_mangle)]
pub static gMysteryGiftServerScript_SendWonderCard: [RomPtr<u8>; 36] = [
    RomPtr(0x1a as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x1c as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x12 as *const u8),
    RomPtr(0x20 as *const u8),
    RomPtr(sClientScript_SendGameData.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(0x11 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x5 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x6 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x4 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_CantSend.as_ptr().cast::<u8>()),
    RomPtr(0x7 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x4 as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(sServerScript_TossPrompt.as_ptr().cast::<u8>()),
    RomPtr(0x4 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_SendCard.as_ptr().cast::<u8>()),
    RomPtr(0x3 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(sServerScript_HasCard.as_ptr().cast::<u8>()),
];

