// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sMainMenuTexts: [RomPtr<u8>; 10] = [
    RomPtr((&raw const crate::data::strings::gText_WithdrawPokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_WithdrawMonDescription).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_DepositPokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_DepositMonDescription).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MovePokemon).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MoveMonDescription).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MoveItems).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_MoveItemsDescription).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SeeYa).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SeeYaDescription).cast::<u8>()),
];

pub(crate) static sWindowTemplate_MainMenu: RomBytes<8> = RomBytes([0, 1, 1, 17, 10, 15, 1, 0]);

pub(crate) static sAnim_ChooseBoxMenu_TopLeft: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_ChooseBoxMenu_BottomLeft: RomBytes<8> = RomBytes([4, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_ChooseBoxMenu_TopRight: RomBytes<8> = RomBytes([6, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_ChooseBoxMenu_BottomRight: RomBytes<8> = RomBytes([10, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_ChooseBoxMenu: [RomPtr<u8>; 4] = [
    RomPtr(sAnim_ChooseBoxMenu_TopLeft.as_ptr().cast::<u8>()),
    RomPtr(sAnim_ChooseBoxMenu_BottomLeft.as_ptr().cast::<u8>()),
    RomPtr(sAnim_ChooseBoxMenu_TopRight.as_ptr().cast::<u8>()),
    RomPtr(sAnim_ChooseBoxMenu_BottomRight.as_ptr().cast::<u8>()),
];

pub(crate) static sAffineAnim_ChooseBoxMenu: RomBytes<16> = RomBytes([224, 0, 224, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_ChooseBoxMenu: [RomPtr<u8>; 1] = [
    RomPtr(sAffineAnim_ChooseBoxMenu.as_ptr().cast::<u8>()),
];

pub(crate) static sChooseBoxMenu_TextColors: RomBytes<3> = RomBytes([4, 15, 14]);

pub(crate) static sText_OutOf30: RomBytes<4> = RomBytes([186, 164, 161, 255]);

pub(crate) static sChooseBoxMenu_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/box_selection_popup.pal.gbapal")));

pub(crate) static sChooseBoxMenuCenter_Gfx: RomBytes<2048> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/box_selection_popup_center.png.4bpp")));

pub(crate) static sChooseBoxMenuSides_Gfx: RomBytes<384> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/box_selection_popup_sides.png.4bpp")));

pub(crate) static sScrollingBg_Gfx: RomBytes<152> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/scrolling_bg.png.4bpp.lz")));

pub(crate) static sScrollingBg_Tilemap: RomBytes<268> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/scrolling_bg.bin.lz")));

pub(crate) static sDisplayMenu_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/display_menu.pal.gbapal")));

pub(crate) static sDisplayMenu_Tilemap: RomBytes<252> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/display_menu.bin.lz")));

pub(crate) static sPkmnData_Tilemap: RomBytes<64> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../graphics/pokemon_storage/pkmn_data.bin")));

pub(crate) static sInterface_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/interface.pal.gbapal")));

pub(crate) static sPkmnDataGray_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/pkmn_data_gray.pal.gbapal")));

pub(crate) static sScrollingBg_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/scrolling_bg.pal.gbapal")));

pub(crate) static sScrollingBgMoveItems_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/scrolling_bg_move_items.pal.gbapal")));

pub(crate) static sCloseBoxButton_Tilemap: RomBytes<72> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../graphics/pokemon_storage/close_box_button.bin")));

pub(crate) static sPartySlotFilled_Tilemap: RomBytes<24> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../graphics/pokemon_storage/party_slot_filled.bin")));

pub(crate) static sPartySlotEmpty_Tilemap: RomBytes<24> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../graphics/pokemon_storage/party_slot_empty.bin")));

pub(crate) static sWaveform_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/waveform.png.gbapal")));

pub(crate) static sWaveform_Gfx: RomBytes<448> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/waveform.png.4bpp")));

pub(crate) static sUnused_Pal: RomBytes<64> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/unused.pal.gbapal")));

pub(crate) static sTextWindows_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/text_windows.pal.gbapal")));

pub(crate) static sWindowTemplates: RomBytes<32> = RomBytes([1, 0, 11, 9, 7, 3, 192, 0, 0, 11, 17, 18, 2, 15, 20, 0, 0, 0, 13, 21, 7, 15, 20, 0, 255, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sBgTemplates: RomBytes<16> = RomBytes([208, 1, 0, 0, 229, 17, 0, 1, 186, 35, 0, 0, 255, 49, 0, 0]);

pub(crate) static sWaveformSpritePalette: [RomPtr<u8>; 2] = [
    RomPtr(sWaveform_Pal.as_ptr().cast::<u8>()),
    RomPtr(0xdaca as *const u8),
];

pub(crate) static sSpriteSheet_Waveform: [RomPtr<u8>; 2] = [
    RomPtr(sWaveform_Gfx.as_ptr().cast::<u8>()),
    RomPtr(0x501c0 as *const u8),
];

pub(crate) static sOamData_DisplayMon: RomBytes<8> = RomBytes([0, 0, 0, 192, 0, 0, 0, 0]);

pub(crate) static sSpriteTemplate_DisplayMon: [RomPtr<u8>; 6] = [
    RomPtr(0xdac60002 as *const u8),
    RomPtr(sOamData_DisplayMon.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sMessages: [RomPtr<u8>; 62] = [
    RomPtr((&raw const crate::data::strings::gText_ExitFromBox).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WhatDoYouWantToDo).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PleasePickATheme).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PickTheWallpaper).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PkmnIsSelected).cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_JumpToWhichBox).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_DepositInWhichBox).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PkmnWasDeposited).cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BoxIsFull2).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ReleaseThisPokemon).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PkmnWasReleased).cast::<u8>()),
    RomPtr(0x4 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ByeByePkmn).cast::<u8>()),
    RomPtr(0x6 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MarkYourPkmn).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ThatsYourLastPkmn).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_YourPartysFull).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_YoureHoldingAPkmn).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WhichOneWillYouTake).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_YouCantReleaseAnEgg).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ContinueBoxOperations).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PkmnCameBack).cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_WasItWorriedAboutYou).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_FourEllipsesExclamation).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PleaseRemoveTheMail).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PkmnIsSelected).cast::<u8>()),
    RomPtr(0x7 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_GiveToAPkmn).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PlacedItemInBag).cast::<u8>()),
    RomPtr(0x7 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_BagIsFull2).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_PutItemInBag).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ItemIsNowHeld).cast::<u8>()),
    RomPtr(0x7 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_ChangedToNewItem).cast::<u8>()),
    RomPtr(0x7 as *const u8),
    RomPtr((&raw const crate::data::strings::gText_MailCantBeStored).cast::<u8>()),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sYesNoWindowTemplate: RomBytes<8> = RomBytes([0, 24, 11, 5, 4, 15, 92, 0]);

pub(crate) static sOamData_Waveform: RomBytes<8> = RomBytes([0, 64, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAnim_Waveform_LeftOff: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Waveform_LeftOn: RomBytes<16> = RomBytes([2, 0, 8, 0, 4, 0, 8, 0, 6, 0, 8, 0, 254, 255, 0, 0]);

pub(crate) static sAnim_Waveform_RightOff: RomBytes<8> = RomBytes([8, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Waveform_RightOn: RomBytes<16> = RomBytes([10, 0, 8, 0, 4, 0, 8, 0, 12, 0, 8, 0, 254, 255, 0, 0]);

pub(crate) static sAnims_Waveform: [RomPtr<u8>; 4] = [
    RomPtr(sAnim_Waveform_LeftOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Waveform_LeftOn.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Waveform_RightOff.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Waveform_RightOn.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteTemplate_Waveform: [RomPtr<u8>; 6] = [
    RomPtr(0xdaca0005 as *const u8),
    RomPtr(sOamData_Waveform.as_ptr().cast::<u8>()),
    RomPtr(sAnims_Waveform.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sOamData_MonIcon: RomBytes<8> = RomBytes([0, 0, 0, 128, 0, 0, 0, 0]);

pub(crate) static sSpriteTemplate_MonIcon: [RomPtr<u8>; 6] = [
    RomPtr(0xdac00012 as *const u8),
    RomPtr(sOamData_MonIcon.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sAffineAnim_ReleaseMon_Release: RomBytes<16> = RomBytes([254, 255, 254, 255, 0, 120, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ReleaseMon_CameBack: RomBytes<24> = RomBytes([16, 0, 16, 0, 0, 0, 0, 0, 16, 0, 16, 0, 0, 15, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_ReleaseMon: [RomPtr<u8>; 2] = [
    RomPtr(sAffineAnim_ReleaseMon_Release.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ReleaseMon_CameBack.as_ptr().cast::<u8>()),
];

pub(crate) static sWallpaperPalettes_Forest: RomBytes<64> = RomBytes([255, 127, 254, 115, 207, 126, 151, 127, 51, 127, 0, 0, 111, 55, 235, 38, 245, 21, 40, 26, 139, 38, 114, 58, 121, 38, 255, 127, 52, 42, 110, 17, 255, 127, 252, 87, 249, 75, 150, 63, 51, 51, 208, 38, 109, 26, 10, 14, 0, 0, 89, 87, 213, 70, 0, 0, 0, 0, 0, 0, 52, 42, 143, 21]);

pub(crate) static sWallpaperTiles_Forest: RomBytes<1156> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/forest/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Forest: RomBytes<224> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/forest/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_City: RomBytes<64> = RomBytes([255, 127, 222, 123, 11, 98, 143, 106, 19, 115, 10, 58, 142, 74, 246, 98, 114, 82, 238, 65, 106, 49, 247, 114, 219, 123, 87, 107, 243, 41, 45, 17, 255, 127, 0, 0, 191, 123, 92, 111, 249, 98, 84, 78, 241, 65, 0, 0, 0, 0, 0, 0, 0, 0, 150, 86, 183, 90, 0, 0, 243, 41, 78, 21]);

pub(crate) static sWallpaperTiles_City: RomBytes<792> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/city/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_City: RomBytes<220> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/city/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Desert: RomBytes<64> = RomBytes([255, 127, 255, 71, 216, 70, 251, 62, 220, 46, 149, 86, 231, 28, 119, 66, 239, 61, 231, 28, 250, 50, 62, 39, 159, 55, 255, 127, 85, 46, 209, 29, 255, 127, 191, 95, 95, 83, 29, 75, 219, 58, 153, 54, 211, 33, 112, 21, 186, 58, 120, 54, 0, 0, 0, 0, 0, 0, 0, 0, 52, 42, 143, 21]);

pub(crate) static sWallpaperTiles_Desert: RomBytes<948> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/desert/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Desert: RomBytes<252> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/desert/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Savanna: RomBytes<64> = RomBytes([255, 127, 123, 111, 186, 127, 119, 127, 53, 127, 208, 126, 0, 0, 87, 79, 244, 62, 145, 46, 255, 127, 123, 127, 189, 127, 156, 127, 119, 42, 210, 21, 255, 127, 250, 75, 119, 59, 17, 43, 142, 26, 10, 10, 103, 9, 227, 8, 54, 47, 212, 38, 237, 9, 80, 22, 146, 30, 21, 43, 119, 42, 210, 21]);

pub(crate) static sWallpaperTiles_Savanna: RomBytes<1044> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/savanna/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Savanna: RomBytes<260> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/savanna/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Crag: RomBytes<64> = RomBytes([255, 127, 0, 0, 213, 94, 114, 86, 48, 78, 238, 69, 89, 119, 22, 107, 179, 94, 0, 0, 0, 0, 0, 0, 156, 115, 255, 127, 250, 42, 85, 22, 255, 127, 123, 111, 247, 98, 115, 78, 239, 61, 140, 49, 41, 37, 0, 0, 0, 0, 0, 0, 24, 99, 214, 90, 148, 82, 82, 74, 250, 42, 85, 22]);

pub(crate) static sWallpaperTiles_Crag: RomBytes<1020> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/crag/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Crag: RomBytes<240> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/crag/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Volcano: RomBytes<64> = RomBytes([255, 127, 0, 0, 82, 86, 180, 94, 247, 102, 124, 119, 58, 115, 24, 103, 84, 70, 241, 53, 175, 45, 124, 25, 159, 54, 255, 127, 26, 70, 117, 49, 255, 127, 191, 111, 159, 99, 63, 87, 190, 70, 58, 54, 182, 37, 50, 21, 191, 58, 252, 41, 254, 74, 153, 29, 62, 50, 186, 33, 26, 70, 117, 49]);

pub(crate) static sWallpaperTiles_Volcano: RomBytes<1264> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/volcano/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Volcano: RomBytes<316> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/volcano/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Snow: RomBytes<64> = RomBytes([255, 127, 156, 119, 90, 115, 142, 98, 10, 82, 86, 119, 242, 106, 222, 127, 189, 123, 0, 0, 0, 0, 0, 0, 156, 115, 255, 127, 26, 70, 117, 49, 255, 127, 156, 115, 57, 103, 81, 94, 205, 77, 73, 61, 197, 44, 65, 28, 188, 127, 153, 123, 0, 0, 222, 127, 254, 127, 255, 127, 26, 70, 117, 49]);

pub(crate) static sWallpaperTiles_Snow: RomBytes<1120> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/snow/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Snow: RomBytes<268> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/snow/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Cave: RomBytes<64> = RomBytes([255, 127, 28, 63, 216, 66, 84, 54, 240, 53, 141, 37, 74, 33, 73, 26, 0, 0, 244, 114, 144, 110, 12, 102, 156, 115, 255, 127, 107, 65, 198, 44, 255, 127, 94, 67, 218, 50, 86, 34, 210, 17, 78, 1, 202, 0, 70, 0, 249, 70, 86, 54, 183, 62, 243, 49, 83, 74, 255, 127, 107, 65, 198, 44]);

pub(crate) static sWallpaperTiles_Cave: RomBytes<984> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/cave/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Cave: RomBytes<216> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/cave/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Beach: RomBytes<64> = RomBytes([255, 127, 242, 25, 151, 123, 215, 123, 252, 127, 74, 42, 48, 27, 184, 50, 158, 83, 223, 91, 190, 83, 75, 103, 144, 99, 255, 127, 138, 125, 6, 77, 255, 127, 255, 111, 157, 91, 124, 71, 92, 63, 27, 59, 250, 50, 0, 0, 0, 0, 157, 99, 154, 115, 19, 95, 88, 91, 0, 0, 138, 125, 6, 77]);

pub(crate) static sWallpaperTiles_Beach: RomBytes<976> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/beach/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Beach: RomBytes<256> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/beach/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Seafloor: RomBytes<64> = RomBytes([255, 127, 48, 123, 141, 102, 232, 93, 98, 77, 96, 48, 183, 123, 0, 0, 14, 45, 0, 0, 108, 16, 0, 0, 156, 115, 255, 127, 210, 22, 45, 2, 255, 127, 84, 127, 175, 118, 76, 110, 200, 93, 68, 77, 192, 60, 64, 44, 226, 64, 245, 65, 145, 61, 15, 119, 189, 119, 255, 127, 210, 22, 45, 2]);

pub(crate) static sWallpaperTiles_Seafloor: RomBytes<764> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/seafloor/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Seafloor: RomBytes<276> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/seafloor/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_River: RomBytes<64> = RomBytes([255, 127, 252, 127, 184, 123, 145, 115, 0, 0, 46, 103, 0, 0, 111, 51, 40, 2, 206, 2, 82, 15, 150, 79, 156, 115, 255, 127, 86, 54, 177, 33, 255, 127, 252, 79, 248, 63, 148, 47, 16, 31, 140, 14, 8, 2, 132, 1, 253, 127, 145, 115, 179, 123, 247, 127, 189, 119, 255, 127, 86, 54, 177, 33]);

pub(crate) static sWallpaperTiles_River: RomBytes<1000> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/river/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_River: RomBytes<248> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/river/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Sky: RomBytes<64> = RomBytes([255, 127, 221, 127, 186, 127, 150, 127, 82, 127, 239, 126, 74, 126, 199, 121, 36, 113, 0, 0, 0, 0, 188, 127, 122, 127, 255, 127, 57, 22, 148, 1, 255, 127, 221, 127, 186, 127, 150, 127, 82, 127, 239, 126, 9, 118, 37, 97, 74, 126, 8, 122, 199, 121, 133, 117, 36, 113, 173, 126, 57, 22, 148, 1]);

pub(crate) static sWallpaperTiles_Sky: RomBytes<904> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/sky/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Sky: RomBytes<240> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/sky/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_PolkaDot: RomBytes<64> = RomBytes([255, 127, 174, 122, 84, 127, 152, 127, 220, 127, 50, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 127, 172, 85, 164, 52, 255, 127, 122, 127, 23, 115, 147, 98, 15, 82, 15, 82, 139, 65, 7, 49, 0, 0, 150, 127, 0, 0, 186, 127, 0, 0, 255, 127, 172, 85, 164, 52]);

pub(crate) static sWallpaperTiles_PolkaDot: RomBytes<712> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/polkadot/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_PolkaDot: RomBytes<256> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/polkadot/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Pokecenter: RomBytes<64> = RomBytes([255, 127, 223, 123, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 222, 78, 30, 54, 255, 82, 95, 62, 251, 45, 90, 103, 247, 86, 212, 49, 239, 28, 255, 127, 159, 107, 61, 91, 188, 78, 122, 66, 23, 54, 181, 41, 49, 29, 255, 82, 63, 91, 95, 103, 159, 70, 0, 0, 0, 0, 212, 49, 239, 28]);

pub(crate) static sWallpaperTiles_Pokecenter: RomBytes<636> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pokecenter/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Pokecenter: RomBytes<256> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pokecenter/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Machine: RomBytes<64> = RomBytes([255, 127, 90, 107, 156, 115, 115, 78, 247, 94, 181, 86, 0, 0, 82, 75, 181, 87, 0, 0, 59, 66, 189, 82, 0, 0, 255, 127, 16, 74, 73, 53, 255, 127, 156, 115, 57, 103, 214, 90, 115, 78, 16, 66, 173, 53, 74, 41, 0, 0, 123, 111, 0, 0, 82, 75, 181, 87, 0, 0, 16, 74, 73, 53]);

pub(crate) static sWallpaperTiles_Machine: RomBytes<596> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/machine/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Machine: RomBytes<196> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/machine/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Plain: RomBytes<64> = RomBytes([255, 127, 189, 119, 90, 107, 247, 94, 148, 82, 49, 70, 0, 0, 123, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 127, 15, 70, 106, 49, 222, 123, 189, 119, 156, 115, 123, 111, 255, 127, 57, 103, 214, 90, 49, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 70, 106, 49]);

pub(crate) static sWallpaperTiles_Plain: RomBytes<288> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/plain/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Plain: RomBytes<152> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/plain/tilemap.bin.lz")));

pub(crate) static sWallpaperTilemap_Unused: RomBytes<432> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../graphics/pokemon_storage/wallpapers/unused.bin")));

pub(crate) static sBoxTitleColors: RomBytes<68> = RomBytes([231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127, 231, 28, 255, 127]);

pub(crate) static sWallpapers: [RomPtr<u8>; 48] = [
    RomPtr(sWallpaperTiles_Forest.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Forest.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Forest.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_City.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_City.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_City.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Desert.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Desert.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Desert.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Savanna.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Savanna.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Savanna.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Crag.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Crag.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Crag.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Volcano.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Volcano.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Volcano.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Snow.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Snow.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Snow.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Cave.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Cave.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Cave.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Beach.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Beach.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Beach.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Seafloor.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Seafloor.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Seafloor.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_River.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_River.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_River.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Sky.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Sky.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Sky.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_PolkaDot.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_PolkaDot.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_PolkaDot.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Pokecenter.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Pokecenter.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Pokecenter.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Machine.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Machine.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Machine.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Plain.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Plain.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Plain.as_ptr().cast::<u8>()),
];

pub(crate) static sArrow_Gfx: RomBytes<128> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/arrow.png.4bpp")));

pub(crate) static sWallpaperPalettes_Zigzagoon: RomBytes<64> = RomBytes([255, 127, 111, 98, 24, 96, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 53, 123, 134, 97, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Zigzagoon: RomBytes<500> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/zigzagoon/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Zigzagoon: RomBytes<280> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/zigzagoon/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Screen: RomBytes<64> = RomBytes([255, 127, 111, 98, 24, 96, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 53, 123, 134, 97, 6, 72, 222, 58, 243, 57, 127, 83, 223, 107, 90, 50, 30, 71, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Screen: RomBytes<636> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/screen/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Screen: RomBytes<300> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/screen/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Diagonal: RomBytes<64> = RomBytes([255, 127, 111, 98, 24, 96, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 134, 97, 18, 123, 6, 72, 0, 0, 0, 0, 156, 3, 124, 1, 240, 3, 10, 126, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Diagonal: RomBytes<492> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/diagonal/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Diagonal: RomBytes<240> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/diagonal/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Block: RomBytes<64> = RomBytes([255, 127, 120, 71, 252, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 120, 71, 252, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Block: RomBytes<464> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/block/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Block: RomBytes<248> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/block/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Pokecenter2: RomBytes<64> = RomBytes([255, 127, 63, 46, 191, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 63, 46, 191, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Pokecenter2: RomBytes<576> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pokecenter2/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Pokecenter2: RomBytes<276> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pokecenter2/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Frame: RomBytes<64> = RomBytes([255, 127, 174, 85, 61, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 174, 85, 61, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Frame: RomBytes<528> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/frame/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Frame: RomBytes<276> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/frame/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Blank: RomBytes<64> = RomBytes([255, 127, 111, 98, 24, 96, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 53, 123, 134, 97, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Blank: RomBytes<428> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/blank/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Blank: RomBytes<220> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/blank/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Circles: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 86, 127, 169, 93, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Circles: RomBytes<596> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/circles/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Circles: RomBytes<252> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/circles/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Azumarill: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 208, 94, 127, 78, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Azumarill: RomBytes<492> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/azumarill/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Azumarill: RomBytes<248> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/azumarill/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Pikachu: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 222, 62, 114, 21, 0, 0, 0, 0, 0, 0, 0, 0, 173, 53, 211, 25, 218, 45, 125, 47, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Pikachu: RomBytes<564> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pikachu/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Pikachu: RomBytes<296> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/pikachu/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Legendary: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 222, 62, 114, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 126, 31, 66, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Legendary: RomBytes<736> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/legendary/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Legendary: RomBytes<324> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/legendary/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Dusclops: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 220, 70, 114, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 238, 65, 213, 94, 153, 49, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Dusclops: RomBytes<588> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/dusclops/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Dusclops: RomBytes<248> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/dusclops/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Ludicolo: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 220, 70, 114, 21, 0, 0, 0, 0, 117, 50, 247, 50, 206, 50, 108, 42, 48, 51, 57, 51, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Ludicolo: RomBytes<704> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/ludicolo/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Ludicolo: RomBytes<288> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/ludicolo/tilemap.bin.lz")));

pub(crate) static sWallpaperPalettes_Whiscash: RomBytes<64> = RomBytes([255, 127, 41, 71, 181, 73, 6, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41, 255, 127, 220, 70, 114, 21, 0, 0, 0, 0, 0, 0, 20, 119, 237, 89, 91, 47, 0, 0, 0, 0, 90, 107, 115, 78, 255, 127, 148, 82, 74, 41]);

pub(crate) static sWallpaperTiles_Whiscash: RomBytes<584> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/whiscash/tiles.4bpp.lz")));

pub(crate) static sWallpaperTilemap_Whiscash: RomBytes<300> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/whiscash/tilemap.bin.lz")));

pub(crate) static sWallpaperIcon_Aqua: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/aqua.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Heart: RomBytes<60> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/heart.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_FiveStar: RomBytes<64> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/five_star.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Brick: RomBytes<40> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/brick.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_FourStar: RomBytes<60> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/four_star.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Asterisk: RomBytes<80> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/asterisk.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Dot: RomBytes<48> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/dot.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_LineCircle: RomBytes<44> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/line_circle.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_PokeBall: RomBytes<76> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/pokeball.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Maze: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/maze.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Footprint: RomBytes<72> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/footprint.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_BigAsterisk: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/big_asterisk.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Circle: RomBytes<64> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/circle.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Koffing: RomBytes<80> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/koffing.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Ribbon: RomBytes<104> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/ribbon.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_FourCircles: RomBytes<48> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/four_circles.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Lotad: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/lotad.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Crystal: RomBytes<72> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/crystal.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Pichu: RomBytes<56> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/pichu.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Diglett: RomBytes<80> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/diglett.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Luvdisc: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/luvdisc.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_StarInCircle: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/star_in_circle.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Spinda: RomBytes<84> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/spinda.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Latis: RomBytes<68> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/latis.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Minun: RomBytes<72> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/minun.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Togepi: RomBytes<92> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/togepi.png.4bpp.lz")));

pub(crate) static sWallpaperIcon_Magma: RomBytes<60> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/wallpapers/icons/magma.png.4bpp.lz")));

pub(crate) static sWaldaWallpapers: [RomPtr<u8>; 48] = [
    RomPtr(sWallpaperTiles_Zigzagoon.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Zigzagoon.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Zigzagoon.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Screen.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Screen.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Screen.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperTiles_Horizontal).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperTilemap_Horizontal).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperPalettes_Horizontal).cast::<u8>()),
    RomPtr(sWallpaperTiles_Diagonal.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Diagonal.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Diagonal.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Block.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Block.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Block.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperTiles_Ribbon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperTilemap_Ribbon).cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperPalettes_Ribbon).cast::<u8>()),
    RomPtr(sWallpaperTiles_Pokecenter2.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Pokecenter2.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Pokecenter2.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Frame.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Frame.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Frame.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Blank.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Blank.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Blank.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Circles.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Circles.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Circles.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Azumarill.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Azumarill.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Azumarill.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Pikachu.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Pikachu.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Pikachu.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Legendary.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Legendary.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Legendary.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Dusclops.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Dusclops.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Dusclops.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Ludicolo.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Ludicolo.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Ludicolo.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTiles_Whiscash.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperTilemap_Whiscash.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperPalettes_Whiscash.as_ptr().cast::<u8>()),
];

pub(crate) static sWaldaWallpaperIcons: [RomPtr<u8>; 30] = [
    RomPtr(sWallpaperIcon_Aqua.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Heart.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_FiveStar.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Brick.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_FourStar.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Asterisk.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Dot.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperIcon_Cross).cast::<u8>()),
    RomPtr(sWallpaperIcon_LineCircle.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_PokeBall.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Maze.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Footprint.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_BigAsterisk.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Circle.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Koffing.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Ribbon.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperIcon_Bolt).cast::<u8>()),
    RomPtr(sWallpaperIcon_FourCircles.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Lotad.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Crystal.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Pichu.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Diglett.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Luvdisc.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_StarInCircle.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Spinda.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Latis.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::data::graphics::gWallpaperIcon_Plusle).cast::<u8>()),
    RomPtr(sWallpaperIcon_Minun.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Togepi.as_ptr().cast::<u8>()),
    RomPtr(sWallpaperIcon_Magma.as_ptr().cast::<u8>()),
];

pub(crate) static sUnusedColor: RomBytes<2> = RomBytes([186, 35]);

pub(crate) static sSpriteSheet_Arrow: [RomPtr<u8>; 2] = [
    RomPtr(sArrow_Gfx.as_ptr().cast::<u8>()),
    RomPtr(0x60080 as *const u8),
];

pub(crate) static sOamData_BoxTitle: RomBytes<8> = RomBytes([0, 64, 0, 128, 0, 8, 0, 0]);

pub(crate) static sAnim_BoxTitle_Left: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_BoxTitle_Right: RomBytes<8> = RomBytes([8, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_BoxTitle: [RomPtr<u8>; 2] = [
    RomPtr(sAnim_BoxTitle_Left.as_ptr().cast::<u8>()),
    RomPtr(sAnim_BoxTitle_Right.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteTemplate_BoxTitle: [RomPtr<u8>; 6] = [
    RomPtr(0xdac90003 as *const u8),
    RomPtr(sOamData_BoxTitle.as_ptr().cast::<u8>()),
    RomPtr(sAnims_BoxTitle.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sOamData_Arrow: RomBytes<8> = RomBytes([0, 128, 0, 0, 0, 8, 0, 0]);

pub(crate) static sAnim_Arrow_Left: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Arrow_Right: RomBytes<8> = RomBytes([2, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnims_Arrow: [RomPtr<u8>; 2] = [
    RomPtr(sAnim_Arrow_Left.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Arrow_Right.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteTemplate_Arrow: [RomPtr<u8>; 6] = [
    RomPtr(0xdaca0006 as *const u8),
    RomPtr(sOamData_Arrow.as_ptr().cast::<u8>()),
    RomPtr(sAnims_Arrow.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::pokemon_storage_system::SpriteCB_Arrow as *const u8),
];

pub(crate) static sHandCursor_Pal: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/hand_cursor.png.gbapal")));

pub(crate) static sHandCursor_Gfx: RomBytes<2048> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/hand_cursor.png.4bpp")));

pub(crate) static sHandCursorShadow_Gfx: RomBytes<128> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/hand_cursor_shadow.png.4bpp")));

pub(crate) static inputFuncs_9: [RomPtr<u8>; 10] = [
    RomPtr(crate::pokemon_storage_system::HandleInput_InBox as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(crate::pokemon_storage_system::HandleInput_InParty as *const u8),
    RomPtr(0x1 as *const u8),
    RomPtr(crate::pokemon_storage_system::HandleInput_OnBox as *const u8),
    RomPtr(0x2 as *const u8),
    RomPtr(crate::pokemon_storage_system::HandleInput_OnButtons as *const u8),
    RomPtr(0x3 as *const u8),
    RomPtr(0x0 as *const u8),
    RomPtr(0x0 as *const u8),
];

pub(crate) static sItemInfoFrame_Gfx: RomBytes<128> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon_storage/item_info_frame.png.4bpp")));

pub(crate) static placeChangeFuncs_10: [RomPtr<u8>; 3] = [
    RomPtr(crate::pokemon_storage_system::MonPlaceChange_Grab as *const u8),
    RomPtr(crate::pokemon_storage_system::MonPlaceChange_Place as *const u8),
    RomPtr(crate::pokemon_storage_system::MonPlaceChange_Shift as *const u8),
];

pub(crate) static sRestrictedReleaseMoves: RomBytes<24> = RomBytes([34, 0, 57, 0, 34, 0, 35, 1, 16, 10, 70, 0, 16, 10, 249, 0, 16, 14, 70, 0, 16, 14, 249, 0]);

pub(crate) static sSpriteTemplate_Cursor_8: [RomPtr<u8>; 6] = [
    RomPtr(0xdaca0000 as *const u8),
    RomPtr(sOamData_Cursor_0.as_ptr().cast::<u8>()),
    RomPtr(sAnims_Cursor_6.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sSpriteTemplate_CursorShadow_7: [RomPtr<u8>; 6] = [
    RomPtr(0xdaca0001 as *const u8),
    RomPtr(sOamData_CursorShadow_1.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::pokemon_storage_system::SpriteCB_CursorShadow as *const u8),
];

pub(crate) static sMenuTexts: [RomPtr<u8>; 39] = [
    RomPtr((&raw const crate::data::strings::gPCText_Cancel).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Store).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Withdraw).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Move).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Shift).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Place).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Summary).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Release).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Mark).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Jump).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Wallpaper).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Name).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Take).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Give).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Give).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Switch).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Bag).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Info).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Scenery1).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Scenery2).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Scenery3).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Etcetera).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Friends).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Forest).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_City).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Desert).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Savanna).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Crag).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Volcano).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Snow).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Cave).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Beach).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Seafloor).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_River).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Sky).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_PolkaDot).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Pokecenter).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Machine).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gPCText_Simple).cast::<u8>()),
];

pub(crate) static sWindowTemplate_MultiMove: RomBytes<8> = RomBytes([0, 10, 3, 20, 18, 9, 10, 0]);

pub(crate) static sOamData_ItemIcon: RomBytes<8> = RomBytes([0, 1, 0, 128, 0, 4, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_Small: RomBytes<16> = RomBytes([128, 0, 128, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_Appear: RomBytes<24> = RomBytes([88, 0, 88, 0, 0, 0, 0, 0, 5, 0, 5, 0, 0, 8, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_Disappear: RomBytes<24> = RomBytes([128, 0, 128, 0, 0, 0, 0, 0, 251, 255, 251, 255, 0, 8, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_PickUp: RomBytes<32> = RomBytes([128, 0, 128, 0, 0, 0, 0, 0, 10, 0, 10, 0, 0, 12, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_PutDown: RomBytes<32> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 246, 255, 246, 255, 0, 12, 0, 0, 128, 0, 128, 0, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_PutAway: RomBytes<24> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 251, 255, 251, 255, 0, 16, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnim_ItemIcon_Large: RomBytes<16> = RomBytes([0, 1, 0, 1, 0, 0, 0, 0, 255, 127, 0, 0, 0, 0, 0, 0]);

pub(crate) static sAffineAnims_ItemIcon: [RomPtr<u8>; 7] = [
    RomPtr(sAffineAnim_ItemIcon_Small.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_Appear.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_Disappear.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_PickUp.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_PutDown.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_PutAway.as_ptr().cast::<u8>()),
    RomPtr(sAffineAnim_ItemIcon_Large.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteTemplate_ItemIcon: [RomPtr<u8>; 6] = [
    RomPtr(0xdacb0007 as *const u8),
    RomPtr(sOamData_ItemIcon.as_ptr().cast::<u8>()),
    RomPtr((&raw const crate::sprite::gDummySpriteAnimTable).cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr(sAffineAnims_ItemIcon.as_ptr().cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sTilemapDimensions: RomBytes<32> = RomBytes([0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 128, 0, 128, 0, 0, 1, 0, 1, 0, 2, 0, 2, 0, 4, 0, 4]);

pub(crate) static sOamData_Cursor_0: RomBytes<8> = RomBytes([0, 0, 0, 128, 0, 4, 0, 0]);

pub(crate) static sAnims_Cursor_6: [RomPtr<u8>; 4] = [
    RomPtr(sAnim_Cursor_Bouncing_2.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Cursor_Still_3.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Cursor_Open_4.as_ptr().cast::<u8>()),
    RomPtr(sAnim_Cursor_Fist_5.as_ptr().cast::<u8>()),
];

pub(crate) static sOamData_CursorShadow_1: RomBytes<8> = RomBytes([0, 0, 0, 64, 0, 4, 0, 0]);

pub(crate) static sAnim_Cursor_Bouncing_2: RomBytes<12> = RomBytes([0, 0, 30, 0, 16, 0, 30, 0, 254, 255, 0, 0]);

pub(crate) static sAnim_Cursor_Still_3: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Cursor_Open_4: RomBytes<8> = RomBytes([32, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sAnim_Cursor_Fist_5: RomBytes<8> = RomBytes([48, 0, 5, 0, 255, 255, 0, 0]);

