// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sBerryDescriptionPart1_Cheri: RomBytes<37> = RomBytes([188, 224, 227, 227, 225, 231, 0, 235, 221, 232, 220, 0, 216, 217, 224, 221, 215, 213, 232, 217, 0, 228, 230, 217, 232, 232, 237, 0, 218, 224, 227, 235, 217, 230, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Cheri: RomBytes<36> = RomBytes([206, 220, 217, 0, 214, 230, 221, 219, 220, 232, 0, 230, 217, 216, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 234, 217, 230, 237, 0, 231, 228, 221, 215, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Chesto: RomBytes<37> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 180, 231, 0, 232, 220, 221, 215, 223, 0, 231, 223, 221, 226, 0, 213, 226, 216, 0, 218, 230, 233, 221, 232, 0, 213, 230, 217, 255]);

pub(crate) static sBerryDescriptionPart2_Chesto: RomBytes<40> = RomBytes([234, 217, 230, 237, 0, 232, 227, 233, 219, 220, 173, 0, 195, 232, 0, 221, 231, 0, 216, 230, 237, 174, 232, 213, 231, 232, 221, 226, 219, 0, 213, 224, 224, 0, 227, 234, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Pecha: RomBytes<26> = RomBytes([208, 217, 230, 237, 0, 231, 235, 217, 217, 232, 0, 213, 226, 216, 0, 216, 217, 224, 221, 215, 221, 227, 233, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Pecha: RomBytes<37> = RomBytes([187, 224, 231, 227, 0, 234, 217, 230, 237, 0, 232, 217, 226, 216, 217, 230, 0, 174, 0, 220, 213, 226, 216, 224, 217, 0, 235, 221, 232, 220, 0, 215, 213, 230, 217, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Rawst: RomBytes<35> = RomBytes([195, 218, 0, 232, 220, 217, 0, 224, 217, 213, 234, 217, 231, 0, 219, 230, 227, 235, 0, 224, 227, 226, 219, 0, 213, 226, 216, 0, 215, 233, 230, 224, 237, 184, 255]);

pub(crate) static sBerryDescriptionPart2_Rawst: RomBytes<37> = RomBytes([232, 220, 217, 0, 188, 191, 204, 204, 211, 0, 231, 217, 217, 225, 231, 0, 232, 227, 0, 219, 230, 227, 235, 0, 234, 217, 230, 237, 0, 214, 221, 232, 232, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Aspear: RomBytes<36> = RomBytes([206, 220, 217, 0, 220, 213, 230, 216, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 216, 217, 226, 231, 217, 0, 235, 221, 232, 220, 0, 213, 0, 230, 221, 215, 220, 255]);

pub(crate) static sBerryDescriptionPart2_Aspear: RomBytes<25> = RomBytes([222, 233, 221, 215, 217, 173, 0, 195, 232, 0, 221, 231, 0, 229, 233, 221, 232, 217, 0, 231, 227, 233, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Leppa: RomBytes<36> = RomBytes([193, 230, 227, 235, 231, 0, 231, 224, 227, 235, 217, 230, 0, 232, 220, 213, 226, 0, 189, 194, 191, 204, 195, 0, 213, 226, 216, 0, 227, 232, 220, 217, 230, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Leppa: RomBytes<36> = RomBytes([206, 220, 217, 0, 231, 225, 213, 224, 224, 217, 230, 0, 232, 220, 217, 0, 188, 191, 204, 204, 211, 184, 0, 232, 220, 217, 0, 232, 213, 231, 232, 221, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Oran: RomBytes<40> = RomBytes([187, 0, 228, 217, 215, 233, 224, 221, 213, 230, 0, 188, 191, 204, 204, 211, 0, 235, 221, 232, 220, 0, 213, 0, 225, 221, 236, 0, 227, 218, 0, 218, 224, 213, 234, 227, 230, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Oran: RomBytes<28> = RomBytes([188, 191, 204, 204, 195, 191, 205, 0, 219, 230, 227, 235, 0, 221, 226, 0, 220, 213, 224, 218, 0, 213, 0, 216, 213, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Persim: RomBytes<34> = RomBytes([198, 227, 234, 217, 231, 0, 231, 233, 226, 224, 221, 219, 220, 232, 173, 0, 206, 220, 217, 0, 188, 191, 204, 204, 211, 180, 231, 0, 215, 227, 224, 227, 230, 255]);

pub(crate) static sBerryDescriptionPart2_Persim: RomBytes<37> = RomBytes([219, 230, 227, 235, 231, 0, 234, 221, 234, 221, 216, 0, 235, 220, 217, 226, 0, 217, 236, 228, 227, 231, 217, 216, 0, 232, 227, 0, 232, 220, 217, 0, 231, 233, 226, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Lum: RomBytes<36> = RomBytes([205, 224, 227, 235, 0, 232, 227, 0, 219, 230, 227, 235, 173, 0, 195, 218, 0, 230, 213, 221, 231, 217, 216, 0, 235, 221, 232, 220, 0, 224, 227, 234, 221, 226, 219, 255]);

pub(crate) static sBerryDescriptionPart2_Lum: RomBytes<31> = RomBytes([215, 213, 230, 217, 184, 0, 221, 232, 0, 225, 213, 237, 0, 219, 230, 227, 235, 0, 232, 235, 227, 0, 188, 191, 204, 204, 195, 191, 205, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Sitrus: RomBytes<35> = RomBytes([189, 224, 227, 231, 217, 224, 237, 0, 230, 217, 224, 213, 232, 217, 216, 0, 232, 227, 0, 201, 204, 187, 200, 173, 0, 206, 220, 217, 0, 224, 213, 230, 219, 217, 255]);

pub(crate) static sBerryDescriptionPart2_Sitrus: RomBytes<33> = RomBytes([188, 191, 204, 204, 211, 0, 220, 213, 231, 0, 213, 0, 235, 217, 224, 224, 174, 230, 227, 233, 226, 216, 217, 216, 0, 218, 224, 213, 234, 227, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Figy: RomBytes<34> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 184, 0, 235, 220, 221, 215, 220, 0, 224, 227, 227, 223, 231, 0, 215, 220, 217, 235, 217, 216, 0, 233, 228, 184, 255]);

pub(crate) static sBerryDescriptionPart2_Figy: RomBytes<29> = RomBytes([214, 230, 221, 225, 231, 0, 235, 221, 232, 220, 0, 231, 228, 221, 215, 237, 0, 231, 233, 214, 231, 232, 213, 226, 215, 217, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Wiki: RomBytes<38> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 231, 213, 221, 216, 0, 232, 227, 0, 220, 213, 234, 217, 0, 219, 230, 227, 235, 226, 0, 224, 233, 225, 228, 237, 255]);

pub(crate) static sBerryDescriptionPart2_Wiki: RomBytes<25> = RomBytes([232, 227, 0, 220, 217, 224, 228, 0, 202, 201, 197, 27, 199, 201, 200, 0, 219, 230, 221, 228, 0, 221, 232, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Mago: RomBytes<35> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 0, 232, 233, 230, 226, 231, 0, 215, 233, 230, 234, 237, 0, 213, 231, 0, 221, 232, 0, 219, 230, 227, 235, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Mago: RomBytes<38> = RomBytes([206, 220, 217, 0, 215, 233, 230, 234, 221, 217, 230, 184, 0, 232, 220, 217, 0, 231, 235, 217, 217, 232, 217, 230, 0, 213, 226, 216, 0, 232, 213, 231, 232, 221, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Aguav: RomBytes<40> = RomBytes([206, 220, 217, 0, 218, 224, 227, 235, 217, 230, 0, 221, 231, 0, 216, 213, 221, 226, 232, 237, 173, 0, 195, 232, 0, 221, 231, 0, 230, 213, 230, 217, 0, 221, 226, 0, 221, 232, 231, 255]);

pub(crate) static sBerryDescriptionPart2_Aguav: RomBytes<31> = RomBytes([213, 214, 221, 224, 221, 232, 237, 0, 232, 227, 0, 219, 230, 227, 235, 0, 235, 221, 232, 220, 227, 233, 232, 0, 224, 221, 219, 220, 232, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Iapapa: RomBytes<32> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 234, 217, 230, 237, 0, 214, 221, 219, 0, 213, 226, 216, 0, 231, 227, 233, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Iapapa: RomBytes<33> = RomBytes([195, 232, 0, 232, 213, 223, 217, 231, 0, 213, 232, 0, 224, 217, 213, 231, 232, 0, 213, 0, 216, 213, 237, 0, 232, 227, 0, 219, 230, 227, 235, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Razz: RomBytes<37> = RomBytes([206, 220, 217, 0, 230, 217, 216, 0, 188, 191, 204, 204, 211, 0, 232, 213, 231, 232, 217, 231, 0, 231, 224, 221, 219, 220, 232, 224, 237, 0, 231, 228, 221, 215, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Razz: RomBytes<37> = RomBytes([195, 232, 0, 219, 230, 227, 235, 231, 0, 229, 233, 221, 215, 223, 224, 237, 0, 221, 226, 0, 222, 233, 231, 232, 0, 218, 227, 233, 230, 0, 220, 227, 233, 230, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Bluk: RomBytes<38> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 214, 224, 233, 217, 0, 227, 226, 0, 232, 220, 217, 0, 227, 233, 232, 231, 221, 216, 217, 184, 0, 214, 233, 232, 255]);

pub(crate) static sBerryDescriptionPart2_Bluk: RomBytes<34> = RomBytes([221, 232, 0, 214, 224, 213, 215, 223, 217, 226, 231, 0, 232, 220, 217, 0, 225, 227, 233, 232, 220, 0, 235, 220, 217, 226, 0, 217, 213, 232, 217, 226, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Nanab: RomBytes<27> = RomBytes([206, 220, 221, 231, 0, 188, 191, 204, 204, 211, 0, 235, 213, 231, 0, 232, 220, 217, 0, 231, 217, 234, 217, 226, 232, 220, 255]);

pub(crate) static sBerryDescriptionPart2_Nanab: RomBytes<38> = RomBytes([216, 221, 231, 215, 227, 234, 217, 230, 217, 216, 0, 221, 226, 0, 232, 220, 217, 0, 235, 227, 230, 224, 216, 173, 0, 195, 232, 0, 221, 231, 0, 231, 235, 217, 217, 232, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Wepear: RomBytes<40> = RomBytes([206, 220, 217, 0, 218, 224, 227, 235, 217, 230, 0, 221, 231, 0, 231, 225, 213, 224, 224, 0, 213, 226, 216, 0, 235, 220, 221, 232, 217, 173, 0, 195, 232, 0, 220, 213, 231, 0, 213, 255]);

pub(crate) static sBerryDescriptionPart2_Wepear: RomBytes<37> = RomBytes([216, 217, 224, 221, 215, 213, 232, 217, 0, 214, 213, 224, 213, 226, 215, 217, 0, 227, 218, 0, 214, 221, 232, 232, 217, 230, 0, 213, 226, 216, 0, 231, 227, 233, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Pinap: RomBytes<28> = RomBytes([209, 217, 213, 223, 0, 213, 219, 213, 221, 226, 231, 232, 0, 235, 221, 226, 216, 0, 213, 226, 216, 0, 215, 227, 224, 216, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Pinap: RomBytes<39> = RomBytes([206, 220, 217, 0, 218, 230, 233, 221, 232, 0, 221, 231, 0, 231, 228, 221, 215, 237, 0, 213, 226, 216, 0, 232, 220, 217, 0, 231, 223, 221, 226, 184, 0, 231, 227, 233, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Pomeg: RomBytes<28> = RomBytes([194, 227, 235, 217, 234, 217, 230, 0, 225, 233, 215, 220, 0, 221, 232, 0, 221, 231, 0, 235, 213, 232, 217, 230, 217, 216, 184, 255]);

pub(crate) static sBerryDescriptionPart2_Pomeg: RomBytes<33> = RomBytes([221, 232, 0, 227, 226, 224, 237, 0, 219, 230, 227, 235, 231, 0, 233, 228, 0, 232, 227, 0, 231, 221, 236, 0, 188, 191, 204, 204, 195, 191, 205, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Kelpsy: RomBytes<35> = RomBytes([187, 0, 230, 213, 230, 217, 0, 234, 213, 230, 221, 217, 232, 237, 0, 231, 220, 213, 228, 217, 216, 0, 224, 221, 223, 217, 0, 213, 0, 230, 227, 227, 232, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Kelpsy: RomBytes<27> = RomBytes([193, 230, 227, 235, 231, 0, 213, 0, 234, 217, 230, 237, 0, 224, 213, 230, 219, 217, 0, 218, 224, 227, 235, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Qualot: RomBytes<34> = RomBytes([198, 227, 234, 217, 231, 0, 235, 213, 232, 217, 230, 173, 0, 193, 230, 227, 235, 231, 0, 231, 232, 230, 227, 226, 219, 0, 217, 234, 217, 226, 0, 221, 226, 255]);

pub(crate) static sBerryDescriptionPart2_Qualot: RomBytes<34> = RomBytes([224, 227, 215, 213, 232, 221, 227, 226, 231, 0, 235, 221, 232, 220, 0, 215, 227, 226, 231, 232, 213, 226, 232, 0, 230, 213, 221, 226, 218, 213, 224, 224, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Hondew: RomBytes<34> = RomBytes([187, 0, 188, 191, 204, 204, 211, 0, 232, 220, 213, 232, 0, 221, 231, 0, 234, 217, 230, 237, 0, 234, 213, 224, 233, 213, 214, 224, 217, 0, 213, 226, 216, 255]);

pub(crate) static sBerryDescriptionPart2_Hondew: RomBytes<35> = RomBytes([230, 213, 230, 217, 224, 237, 0, 231, 217, 217, 226, 173, 0, 195, 232, 0, 221, 231, 0, 234, 217, 230, 237, 0, 216, 217, 224, 221, 215, 221, 227, 233, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Grepa: RomBytes<33> = RomBytes([190, 217, 231, 228, 221, 232, 217, 0, 221, 232, 231, 0, 232, 217, 226, 216, 217, 230, 226, 217, 231, 231, 0, 213, 226, 216, 0, 230, 227, 233, 226, 216, 255]);

pub(crate) static sBerryDescriptionPart2_Grepa: RomBytes<39> = RomBytes([231, 220, 213, 228, 217, 184, 0, 232, 220, 217, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 233, 226, 221, 225, 213, 219, 221, 226, 213, 214, 224, 237, 0, 231, 227, 233, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Tamato: RomBytes<34> = RomBytes([206, 220, 217, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 224, 221, 228, 174, 214, 217, 226, 216, 221, 226, 219, 224, 237, 0, 231, 228, 221, 215, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Tamato: RomBytes<23> = RomBytes([195, 232, 0, 232, 213, 223, 217, 231, 0, 232, 221, 225, 217, 0, 232, 227, 0, 219, 230, 227, 235, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Cornn: RomBytes<37> = RomBytes([187, 0, 188, 191, 204, 204, 211, 0, 218, 230, 227, 225, 0, 213, 226, 0, 213, 226, 215, 221, 217, 226, 232, 0, 217, 230, 213, 173, 0, 199, 213, 237, 0, 226, 227, 232, 255]);

pub(crate) static sBerryDescriptionPart2_Cornn: RomBytes<33> = RomBytes([219, 230, 227, 235, 0, 233, 226, 224, 217, 231, 231, 0, 228, 224, 213, 226, 232, 217, 216, 0, 221, 226, 0, 229, 233, 213, 226, 232, 221, 232, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Magost: RomBytes<36> = RomBytes([187, 0, 188, 191, 204, 204, 211, 0, 232, 220, 213, 232, 0, 221, 231, 0, 235, 221, 216, 217, 224, 237, 0, 231, 213, 221, 216, 0, 232, 227, 0, 220, 213, 234, 217, 255]);

pub(crate) static sBerryDescriptionPart2_Magost: RomBytes<26> = RomBytes([213, 0, 218, 221, 226, 217, 224, 237, 0, 214, 213, 224, 213, 226, 215, 217, 216, 0, 218, 224, 213, 234, 227, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Rabuta: RomBytes<38> = RomBytes([187, 0, 230, 213, 230, 217, 0, 234, 213, 230, 221, 217, 232, 237, 0, 232, 220, 213, 232, 0, 221, 231, 0, 227, 234, 217, 230, 219, 230, 227, 235, 226, 0, 235, 221, 232, 220, 255]);

pub(crate) static sBerryDescriptionPart2_Rabuta: RomBytes<26> = RomBytes([220, 213, 221, 230, 173, 0, 195, 232, 0, 221, 231, 0, 229, 233, 221, 232, 217, 0, 214, 221, 232, 232, 217, 230, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Nomel: RomBytes<35> = RomBytes([203, 233, 221, 232, 217, 0, 231, 227, 233, 230, 173, 0, 196, 233, 231, 232, 0, 227, 226, 217, 0, 214, 221, 232, 217, 0, 225, 213, 223, 217, 231, 0, 221, 232, 255]);

pub(crate) static sBerryDescriptionPart2_Nomel: RomBytes<36> = RomBytes([221, 225, 228, 227, 231, 231, 221, 214, 224, 217, 0, 232, 227, 0, 232, 213, 231, 232, 217, 0, 218, 227, 230, 0, 232, 220, 230, 217, 217, 0, 216, 213, 237, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Spelon: RomBytes<37> = RomBytes([206, 220, 217, 0, 234, 221, 234, 221, 216, 224, 237, 0, 230, 217, 216, 0, 188, 191, 204, 204, 211, 0, 221, 231, 0, 234, 217, 230, 237, 0, 231, 228, 221, 215, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Spelon: RomBytes<37> = RomBytes([195, 232, 231, 0, 235, 213, 230, 232, 231, 0, 231, 217, 215, 230, 217, 232, 217, 0, 213, 0, 231, 228, 221, 215, 237, 0, 231, 233, 214, 231, 232, 213, 226, 215, 217, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Pamtre: RomBytes<34> = RomBytes([190, 230, 221, 218, 232, 231, 0, 227, 226, 0, 232, 220, 217, 0, 231, 217, 213, 0, 218, 230, 227, 225, 0, 231, 227, 225, 217, 235, 220, 217, 230, 217, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Pamtre: RomBytes<33> = RomBytes([195, 232, 0, 221, 231, 0, 232, 220, 227, 233, 219, 220, 232, 0, 232, 227, 0, 219, 230, 227, 235, 0, 217, 224, 231, 217, 235, 220, 217, 230, 217, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Watmel: RomBytes<32> = RomBytes([187, 0, 220, 233, 219, 217, 0, 188, 191, 204, 204, 211, 184, 0, 235, 221, 232, 220, 0, 231, 227, 225, 217, 0, 227, 234, 217, 230, 0, 163, 161, 255]);

pub(crate) static sBerryDescriptionPart2_Watmel: RomBytes<38> = RomBytes([221, 226, 215, 220, 217, 231, 0, 216, 221, 231, 215, 227, 234, 217, 230, 217, 216, 173, 0, 191, 236, 215, 217, 217, 216, 221, 226, 219, 224, 237, 0, 231, 235, 217, 217, 232, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Durin: RomBytes<33> = RomBytes([188, 221, 232, 232, 217, 230, 0, 232, 227, 0, 217, 234, 217, 226, 0, 224, 227, 227, 223, 0, 213, 232, 173, 0, 195, 232, 0, 221, 231, 0, 231, 227, 255]);

pub(crate) static sBerryDescriptionPart2_Durin: RomBytes<40> = RomBytes([214, 221, 232, 232, 217, 230, 184, 0, 226, 227, 0, 227, 226, 217, 0, 220, 213, 231, 0, 217, 234, 217, 230, 0, 217, 213, 232, 217, 226, 0, 221, 232, 0, 213, 231, 0, 221, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Belue: RomBytes<38> = RomBytes([195, 232, 0, 221, 231, 0, 219, 224, 227, 231, 231, 237, 0, 213, 226, 216, 0, 224, 227, 227, 223, 231, 0, 216, 217, 224, 221, 215, 221, 227, 233, 231, 184, 0, 214, 233, 232, 255]);

pub(crate) static sBerryDescriptionPart2_Belue: RomBytes<40> = RomBytes([221, 232, 0, 221, 231, 0, 213, 235, 218, 233, 224, 224, 237, 0, 231, 227, 233, 230, 173, 0, 206, 213, 223, 217, 231, 0, 232, 221, 225, 217, 0, 232, 227, 0, 219, 230, 227, 235, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Liechi: RomBytes<37> = RomBytes([187, 0, 225, 237, 231, 232, 217, 230, 221, 227, 233, 231, 0, 188, 191, 204, 204, 211, 173, 0, 195, 232, 0, 221, 231, 0, 230, 233, 225, 227, 230, 217, 216, 0, 232, 227, 255]);

pub(crate) static sBerryDescriptionPart2_Liechi: RomBytes<30> = RomBytes([215, 227, 226, 232, 213, 221, 226, 0, 232, 220, 217, 0, 228, 227, 235, 217, 230, 0, 227, 218, 0, 232, 220, 217, 0, 231, 217, 213, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Ganlon: RomBytes<37> = RomBytes([187, 0, 225, 237, 231, 232, 217, 230, 221, 227, 233, 231, 0, 188, 191, 204, 204, 211, 173, 0, 195, 232, 0, 221, 231, 0, 230, 233, 225, 227, 230, 217, 216, 0, 232, 227, 255]);

pub(crate) static sBerryDescriptionPart2_Ganlon: RomBytes<31> = RomBytes([215, 227, 226, 232, 213, 221, 226, 0, 232, 220, 217, 0, 228, 227, 235, 217, 230, 0, 227, 218, 0, 232, 220, 217, 0, 224, 213, 226, 216, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Salac: RomBytes<37> = RomBytes([187, 0, 225, 237, 231, 232, 217, 230, 221, 227, 233, 231, 0, 188, 191, 204, 204, 211, 173, 0, 195, 232, 0, 221, 231, 0, 230, 233, 225, 227, 230, 217, 216, 0, 232, 227, 255]);

pub(crate) static sBerryDescriptionPart2_Salac: RomBytes<30> = RomBytes([215, 227, 226, 232, 213, 221, 226, 0, 232, 220, 217, 0, 228, 227, 235, 217, 230, 0, 227, 218, 0, 232, 220, 217, 0, 231, 223, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Petaya: RomBytes<37> = RomBytes([187, 0, 225, 237, 231, 232, 217, 230, 221, 227, 233, 231, 0, 188, 191, 204, 204, 211, 173, 0, 195, 232, 0, 221, 231, 0, 230, 233, 225, 227, 230, 217, 216, 0, 232, 227, 255]);

pub(crate) static sBerryDescriptionPart2_Petaya: RomBytes<40> = RomBytes([215, 227, 226, 232, 213, 221, 226, 0, 232, 220, 217, 0, 228, 227, 235, 217, 230, 0, 227, 218, 0, 213, 224, 224, 0, 224, 221, 234, 221, 226, 219, 0, 232, 220, 221, 226, 219, 231, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Apicot: RomBytes<36> = RomBytes([187, 0, 234, 217, 230, 237, 0, 225, 237, 231, 232, 221, 218, 237, 221, 226, 219, 0, 188, 191, 204, 204, 211, 173, 0, 200, 227, 0, 232, 217, 224, 224, 221, 226, 219, 255]);

pub(crate) static sBerryDescriptionPart2_Apicot: RomBytes<39> = RomBytes([235, 220, 213, 232, 0, 225, 213, 237, 0, 220, 213, 228, 228, 217, 226, 0, 227, 230, 0, 220, 227, 235, 0, 221, 232, 0, 215, 213, 226, 0, 214, 217, 0, 233, 231, 217, 216, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Lansat: RomBytes<30> = RomBytes([205, 213, 221, 216, 0, 232, 227, 0, 214, 217, 0, 213, 0, 224, 217, 219, 217, 226, 216, 213, 230, 237, 0, 188, 191, 204, 204, 211, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Lansat: RomBytes<34> = RomBytes([194, 227, 224, 216, 221, 226, 219, 0, 221, 232, 0, 231, 233, 228, 228, 227, 231, 217, 216, 224, 237, 0, 214, 230, 221, 226, 219, 231, 0, 222, 227, 237, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Starf: RomBytes<35> = RomBytes([205, 227, 0, 231, 232, 230, 227, 226, 219, 184, 0, 221, 232, 0, 235, 213, 231, 0, 213, 214, 213, 226, 216, 227, 226, 217, 216, 0, 213, 232, 0, 232, 220, 217, 255]);

pub(crate) static sBerryDescriptionPart2_Starf: RomBytes<35> = RomBytes([235, 227, 230, 224, 216, 180, 231, 0, 217, 216, 219, 217, 173, 0, 189, 227, 226, 231, 221, 216, 217, 230, 217, 216, 0, 213, 0, 225, 221, 230, 213, 219, 217, 173, 255]);

pub(crate) static sBerryDescriptionPart1_Enigma: RomBytes<30> = RomBytes([187, 0, 215, 227, 225, 228, 224, 217, 232, 217, 224, 237, 0, 217, 226, 221, 219, 225, 213, 232, 221, 215, 0, 188, 191, 204, 204, 211, 173, 255]);

pub(crate) static sBerryDescriptionPart2_Enigma: RomBytes<36> = RomBytes([187, 228, 228, 217, 213, 230, 231, 0, 232, 227, 0, 220, 213, 234, 217, 0, 232, 220, 217, 0, 228, 227, 235, 217, 230, 0, 227, 218, 0, 231, 232, 213, 230, 231, 173, 255]);

#[unsafe(no_mangle)]
pub static gBerries: [RomPtr<u8>; 301] = [
    RomPtr(0xccbfc2bd as *const u8),
    RomPtr(0x200ffc3 as *const u8),
    RomPtr(0x2030014 as *const u8),
    RomPtr(sBerryDescriptionPart1_Cheri.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Cheri.as_ptr().cast::<u8>()),
    RomPtr(0xa03 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xcdbfc2bd as *const u8),
    RomPtr(0x5ffc9ce as *const u8),
    RomPtr(0x2030050 as *const u8),
    RomPtr(sBerryDescriptionPart1_Chesto.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Chesto.as_ptr().cast::<u8>()),
    RomPtr(0xa0003 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xc2bdbfca as *const u8),
    RomPtr(0x100ffbb as *const u8),
    RomPtr(0x2030028 as *const u8),
    RomPtr(sBerryDescriptionPart1_Pecha.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Pecha.as_ptr().cast::<u8>()),
    RomPtr(0xa000003 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xcdd1bbcc as *const u8),
    RomPtr(0x300ffce as *const u8),
    RomPtr(0x2030020 as *const u8),
    RomPtr(sBerryDescriptionPart1_Rawst.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Rawst.as_ptr().cast::<u8>()),
    RomPtr(0x3 as *const u8),
    RomPtr(0x19000a as *const u8),
    RomPtr(0xbfcacdbb as *const u8),
    RomPtr(0x5ffccbb as *const u8),
    RomPtr(0x2030032 as *const u8),
    RomPtr(sBerryDescriptionPart1_Aspear.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Aspear.as_ptr().cast::<u8>()),
    RomPtr(0x3 as *const u8),
    RomPtr(0x190a00 as *const u8),
    RomPtr(0xcacabfc6 as *const u8),
    RomPtr(0x400ffbb as *const u8),
    RomPtr(0x203001c as *const u8),
    RomPtr(sBerryDescriptionPart1_Leppa.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Leppa.as_ptr().cast::<u8>()),
    RomPtr(0xa000a04 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xc8bbccc9 as *const u8),
    RomPtr(0x50000ff as *const u8),
    RomPtr(0x2030023 as *const u8),
    RomPtr(sBerryDescriptionPart1_Oran.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Oran.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a03 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xcdccbfca as *const u8),
    RomPtr(0x3ffc7c3 as *const u8),
    RomPtr(0x203002f as *const u8),
    RomPtr(sBerryDescriptionPart1_Persim.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Persim.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a03 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xffc7cfc6 as *const u8),
    RomPtr(0x5000000 as *const u8),
    RomPtr(0x1020022 as *const u8),
    RomPtr(sBerryDescriptionPart1_Lum.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Lum.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a0c as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xcccec3cd as *const u8),
    RomPtr(0x4ffcdcf as *const u8),
    RomPtr(0x203005f as *const u8),
    RomPtr(sBerryDescriptionPart1_Sitrus.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Sitrus.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a06 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xd3c1c3c0 as *const u8),
    RomPtr(0x20000ff as *const u8),
    RomPtr(0x2030064 as *const u8),
    RomPtr(sBerryDescriptionPart1_Figy.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Figy.as_ptr().cast::<u8>()),
    RomPtr(0xa06 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xc3c5c3d1 as *const u8),
    RomPtr(0x30000ff as *const u8),
    RomPtr(0x2030073 as *const u8),
    RomPtr(sBerryDescriptionPart1_Wiki.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Wiki.as_ptr().cast::<u8>()),
    RomPtr(0xa0006 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xc9c1bbc7 as *const u8),
    RomPtr(0x30000ff as *const u8),
    RomPtr(0x203007e as *const u8),
    RomPtr(sBerryDescriptionPart1_Mago.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Mago.as_ptr().cast::<u8>()),
    RomPtr(0xa000006 as *const u8),
    RomPtr(0x190000 as *const u8),
    RomPtr(0xbbcfc1bb as *const u8),
    RomPtr(0x500ffd0 as *const u8),
    RomPtr(0x2030040 as *const u8),
    RomPtr(sBerryDescriptionPart1_Aguav.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Aguav.as_ptr().cast::<u8>()),
    RomPtr(0x6 as *const u8),
    RomPtr(0x19000a as *const u8),
    RomPtr(0xbbcabbc3 as *const u8),
    RomPtr(0x2ffbbca as *const u8),
    RomPtr(0x20300df as *const u8),
    RomPtr(sBerryDescriptionPart1_Iapapa.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Iapapa.as_ptr().cast::<u8>()),
    RomPtr(0x6 as *const u8),
    RomPtr(0x190a00 as *const u8),
    RomPtr(0xd4d4bbcc as *const u8),
    RomPtr(0x40000ff as *const u8),
    RomPtr(0x3060078 as *const u8),
    RomPtr(sBerryDescriptionPart1_Razz.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Razz.as_ptr().cast::<u8>()),
    RomPtr(0xa0a01 as *const u8),
    RomPtr(0x140000 as *const u8),
    RomPtr(0xc5cfc6bc as *const u8),
    RomPtr(0x20000ff as *const u8),
    RomPtr(0x306006c as *const u8),
    RomPtr(sBerryDescriptionPart1_Bluk.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Bluk.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0001 as *const u8),
    RomPtr(0x140000 as *const u8),
    RomPtr(0xbbc8bbc8 as *const u8),
    RomPtr(0x400ffbc as *const u8),
    RomPtr(0x306004d as *const u8),
    RomPtr(sBerryDescriptionPart1_Nanab.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Nanab.as_ptr().cast::<u8>()),
    RomPtr(0xa000001 as *const u8),
    RomPtr(0x14000a as *const u8),
    RomPtr(0xbfcabfd1 as *const u8),
    RomPtr(0x5ffccbb as *const u8),
    RomPtr(0x306004a as *const u8),
    RomPtr(sBerryDescriptionPart1_Wepear.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Wepear.as_ptr().cast::<u8>()),
    RomPtr(0x1 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xbbc8c3ca as *const u8),
    RomPtr(0x300ffca as *const u8),
    RomPtr(0x3060050 as *const u8),
    RomPtr(sBerryDescriptionPart1_Pinap.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Pinap.as_ptr().cast::<u8>()),
    RomPtr(0xa01 as *const u8),
    RomPtr(0x140a00 as *const u8),
    RomPtr(0xbfc7c9ca as *const u8),
    RomPtr(0x400ffc1 as *const u8),
    RomPtr(0x2060087 as *const u8),
    RomPtr(sBerryDescriptionPart1_Pomeg.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Pomeg.as_ptr().cast::<u8>()),
    RomPtr(0xa000a03 as *const u8),
    RomPtr(0x14000a as *const u8),
    RomPtr(0xcac6bfc5 as *const u8),
    RomPtr(0x3ffd3cd as *const u8),
    RomPtr(0x2060096 as *const u8),
    RomPtr(sBerryDescriptionPart1_Kelpsy.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Kelpsy.as_ptr().cast::<u8>()),
    RomPtr(0xa0003 as *const u8),
    RomPtr(0x140a0a as *const u8),
    RomPtr(0xc6bbcfcb as *const u8),
    RomPtr(0x3ffcec9 as *const u8),
    RomPtr(0x206006e as *const u8),
    RomPtr(sBerryDescriptionPart1_Qualot.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Qualot.as_ptr().cast::<u8>()),
    RomPtr(0xa000a03 as *const u8),
    RomPtr(0x140a00 as *const u8),
    RomPtr(0xbec8c9c2 as *const u8),
    RomPtr(0x3ffd1bf as *const u8),
    RomPtr(0x20600a2 as *const u8),
    RomPtr(sBerryDescriptionPart1_Hondew.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Hondew.as_ptr().cast::<u8>()),
    RomPtr(0xa0a03 as *const u8),
    RomPtr(0x14000a as *const u8),
    RomPtr(0xcabfccc1 as *const u8),
    RomPtr(0x200ffbb as *const u8),
    RomPtr(0x2060095 as *const u8),
    RomPtr(sBerryDescriptionPart1_Grepa.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Grepa.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0003 as *const u8),
    RomPtr(0x140a00 as *const u8),
    RomPtr(0xbbc7bbce as *const u8),
    RomPtr(0x2ffc9ce as *const u8),
    RomPtr(0x20400c8 as *const u8),
    RomPtr(sBerryDescriptionPart1_Tamato.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Tamato.as_ptr().cast::<u8>()),
    RomPtr(0xa1406 as *const u8),
    RomPtr(0x1e0000 as *const u8),
    RomPtr(0xc8ccc9bd as *const u8),
    RomPtr(0x300ffc8 as *const u8),
    RomPtr(0x204004b as *const u8),
    RomPtr(sBerryDescriptionPart1_Cornn.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Cornn.as_ptr().cast::<u8>()),
    RomPtr(0xa140006 as *const u8),
    RomPtr(0x1e0000 as *const u8),
    RomPtr(0xc9c1bbc7 as *const u8),
    RomPtr(0x3ffcecd as *const u8),
    RomPtr(0x204008c as *const u8),
    RomPtr(sBerryDescriptionPart1_Magost.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Magost.as_ptr().cast::<u8>()),
    RomPtr(0x14000006 as *const u8),
    RomPtr(0x1e000a as *const u8),
    RomPtr(0xcfbcbbcc as *const u8),
    RomPtr(0x2ffbbce as *const u8),
    RomPtr(0x20400e2 as *const u8),
    RomPtr(sBerryDescriptionPart1_Rabuta.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Rabuta.as_ptr().cast::<u8>()),
    RomPtr(0x6 as *const u8),
    RomPtr(0x1e0a14 as *const u8),
    RomPtr(0xbfc7c9c8 as *const u8),
    RomPtr(0x500ffc6 as *const u8),
    RomPtr(0x204011d as *const u8),
    RomPtr(sBerryDescriptionPart1_Nomel.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Nomel.as_ptr().cast::<u8>()),
    RomPtr(0xa06 as *const u8),
    RomPtr(0x1e1400 as *const u8),
    RomPtr(0xc6bfcacd as *const u8),
    RomPtr(0x2ffc8c9 as *const u8),
    RomPtr(0x1020085 as *const u8),
    RomPtr(sBerryDescriptionPart1_Spelon.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Spelon.as_ptr().cast::<u8>()),
    RomPtr(0xa2812 as *const u8),
    RomPtr(0x460000 as *const u8),
    RomPtr(0xcec7bbca as *const u8),
    RomPtr(0x1ffbfcc as *const u8),
    RomPtr(0x10200f4 as *const u8),
    RomPtr(sBerryDescriptionPart1_Pamtre.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Pamtre.as_ptr().cast::<u8>()),
    RomPtr(0xa280012 as *const u8),
    RomPtr(0x460000 as *const u8),
    RomPtr(0xc7cebbd1 as *const u8),
    RomPtr(0x2ffc6bf as *const u8),
    RomPtr(0x10200fa as *const u8),
    RomPtr(sBerryDescriptionPart1_Watmel.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Watmel.as_ptr().cast::<u8>()),
    RomPtr(0x28000012 as *const u8),
    RomPtr(0x46000a as *const u8),
    RomPtr(0xc3cccfbe as *const u8),
    RomPtr(0x300ffc8 as *const u8),
    RomPtr(0x1020118 as *const u8),
    RomPtr(sBerryDescriptionPart1_Durin.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Durin.as_ptr().cast::<u8>()),
    RomPtr(0x12 as *const u8),
    RomPtr(0x460a28 as *const u8),
    RomPtr(0xcfc6bfbc as *const u8),
    RomPtr(0x100ffbf as *const u8),
    RomPtr(0x102012c as *const u8),
    RomPtr(sBerryDescriptionPart1_Belue.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Belue.as_ptr().cast::<u8>()),
    RomPtr(0xa12 as *const u8),
    RomPtr(0x462800 as *const u8),
    RomPtr(0xbdbfc3c6 as *const u8),
    RomPtr(0x4ffc3c2 as *const u8),
    RomPtr(0x102006f as *const u8),
    RomPtr(sBerryDescriptionPart1_Liechi.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Liechi.as_ptr().cast::<u8>()),
    RomPtr(0x28002818 as *const u8),
    RomPtr(0x500a00 as *const u8),
    RomPtr(0xc6c8bbc1 as *const u8),
    RomPtr(0x4ffc8c9 as *const u8),
    RomPtr(0x1020021 as *const u8),
    RomPtr(sBerryDescriptionPart1_Ganlon.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Ganlon.as_ptr().cast::<u8>()),
    RomPtr(0x280018 as *const u8),
    RomPtr(0x500028 as *const u8),
    RomPtr(0xbbc6bbcd as *const u8),
    RomPtr(0x400ffbd as *const u8),
    RomPtr(0x102005f as *const u8),
    RomPtr(sBerryDescriptionPart1_Salac.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Salac.as_ptr().cast::<u8>()),
    RomPtr(0x28000018 as *const u8),
    RomPtr(0x502800 as *const u8),
    RomPtr(0xbbcebfca as *const u8),
    RomPtr(0x4ffbbd3 as *const u8),
    RomPtr(0x10200ed as *const u8),
    RomPtr(sBerryDescriptionPart1_Petaya.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Petaya.as_ptr().cast::<u8>()),
    RomPtr(0x2818 as *const u8),
    RomPtr(0x500028 as *const u8),
    RomPtr(0xbdc3cabb as *const u8),
    RomPtr(0x3ffcec9 as *const u8),
    RomPtr(0x102004b as *const u8),
    RomPtr(sBerryDescriptionPart1_Apicot.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Apicot.as_ptr().cast::<u8>()),
    RomPtr(0x280018 as *const u8),
    RomPtr(0x502800 as *const u8),
    RomPtr(0xcdc8bbc6 as *const u8),
    RomPtr(0x2ffcebb as *const u8),
    RomPtr(0x1020061 as *const u8),
    RomPtr(sBerryDescriptionPart1_Lansat.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Lansat.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a18 as *const u8),
    RomPtr(0x1e0a0a as *const u8),
    RomPtr(0xccbbcecd as *const u8),
    RomPtr(0x500ffc0 as *const u8),
    RomPtr(0x1020099 as *const u8),
    RomPtr(sBerryDescriptionPart1_Starf.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Starf.as_ptr().cast::<u8>()),
    RomPtr(0xa0a0a18 as *const u8),
    RomPtr(0x1e0a0a as *const u8),
    RomPtr(0xc1c3c8bf as *const u8),
    RomPtr(0xffbbc7 as *const u8),
    RomPtr(0x1020000 as *const u8),
    RomPtr(sBerryDescriptionPart1_Enigma.as_ptr().cast::<u8>()),
    RomPtr(sBerryDescriptionPart2_Enigma.as_ptr().cast::<u8>()),
    RomPtr(0x28282818 as *const u8),
    RomPtr(0x282828 as *const u8),
];

#[unsafe(no_mangle)]
pub static gBerryCrush_BerryData: RomBytes<172> = RomBytes([50, 0, 20, 0, 50, 0, 20, 0, 50, 0, 20, 0, 50, 0, 20, 0, 50, 0, 20, 0, 50, 0, 30, 0, 50, 0, 30, 0, 50, 0, 30, 0, 50, 0, 30, 0, 50, 0, 30, 0, 60, 0, 50, 0, 60, 0, 50, 0, 60, 0, 50, 0, 60, 0, 50, 0, 60, 0, 50, 0, 80, 0, 70, 0, 80, 0, 70, 0, 80, 0, 70, 0, 80, 0, 70, 0, 80, 0, 70, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 100, 0, 130, 0, 150, 0, 130, 0, 150, 0, 130, 0, 150, 0, 130, 0, 150, 0, 130, 0, 150, 0, 160, 0, 250, 0, 160, 0, 250, 0, 160, 0, 250, 0, 160, 0, 250, 0, 160, 0, 250, 0, 180, 0, 244, 1, 180, 0, 244, 1, 180, 0, 244, 1, 180, 0, 244, 1, 180, 0, 244, 1, 200, 0, 238, 2, 200, 0, 238, 2, 150, 0, 200, 0]);

#[unsafe(no_mangle)]
pub static gBlankBerryTree: RomBytes<8> = RomBytes([0, 0, 0, 0, 0, 0, 0, 0]);

