// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sWindowTemplate_LinkPlayerCount: RomBytes<8> = RomBytes([0, 16, 11, 11, 2, 15, 37, 1]);

pub(crate) static sTrainerCardColorNames: [RomPtr<u8>; 4] = [
    RomPtr((&raw const crate::data::strings::gText_BronzeCard).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_CopperCard).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_SilverCard).cast::<u8>()),
    RomPtr((&raw const crate::data::strings::gText_GoldCard).cast::<u8>()),
];

