// @generated by tools/rustport/cdata.py from the original C tables.
// Regenerate instead of editing by hand.
#![allow(non_upper_case_globals, dead_code, unused_imports)]

use crate::ffi::{RomBytes, RomPtr};

pub(crate) static sEggPalette: RomBytes<32> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon/egg/normal.pal.gbapal")));

pub(crate) static sEggHatchTiles: RomBytes<2048> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon/egg/hatch.png.4bpp")));

pub(crate) static sEggShardTiles: RomBytes<128> = RomBytes(*include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../build/assets/graphics/pokemon/egg/shard.png.4bpp")));

pub(crate) static sOamData_Egg: RomBytes<8> = RomBytes([0, 0, 0, 128, 0, 4, 0, 0]);

pub(crate) static sSpriteAnim_Egg_Normal: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Egg_Cracked1: RomBytes<8> = RomBytes([16, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Egg_Cracked2: RomBytes<8> = RomBytes([32, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_Egg_Cracked3: RomBytes<8> = RomBytes([48, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnimTable_Egg: [RomPtr<u8>; 4] = [
    RomPtr(sSpriteAnim_Egg_Normal.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Egg_Cracked1.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Egg_Cracked2.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_Egg_Cracked3.as_ptr().cast::<u8>()),
];

pub(crate) static sEggHatch_Sheet: [RomPtr<u8>; 2] = [
    RomPtr(sEggHatchTiles.as_ptr().cast::<u8>()),
    RomPtr(0x30390800 as *const u8),
];

pub(crate) static sEggShards_Sheet: [RomPtr<u8>; 2] = [
    RomPtr(sEggShardTiles.as_ptr().cast::<u8>()),
    RomPtr(0x5ba00080 as *const u8),
];

pub(crate) static sEgg_SpritePalette: [RomPtr<u8>; 2] = [
    RomPtr(sEggPalette.as_ptr().cast::<u8>()),
    RomPtr(0xd431 as *const u8),
];

pub(crate) static sSpriteTemplate_Egg: [RomPtr<u8>; 6] = [
    RomPtr(0xd4313039 as *const u8),
    RomPtr(sOamData_Egg.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnimTable_Egg.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::sprite::SpriteCallbackDummy as *const u8),
];

pub(crate) static sOamData_EggShard: RomBytes<8> = RomBytes([0, 0, 0, 0, 0, 8, 0, 0]);

pub(crate) static sSpriteAnim_EggShard0: RomBytes<8> = RomBytes([0, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_EggShard1: RomBytes<8> = RomBytes([1, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_EggShard2: RomBytes<8> = RomBytes([2, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnim_EggShard3: RomBytes<8> = RomBytes([3, 0, 5, 0, 255, 255, 0, 0]);

pub(crate) static sSpriteAnimTable_EggShard: [RomPtr<u8>; 4] = [
    RomPtr(sSpriteAnim_EggShard0.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_EggShard1.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_EggShard2.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnim_EggShard3.as_ptr().cast::<u8>()),
];

pub(crate) static sSpriteTemplate_EggShard: [RomPtr<u8>; 6] = [
    RomPtr(0xd4315ba0 as *const u8),
    RomPtr(sOamData_EggShard.as_ptr().cast::<u8>()),
    RomPtr(sSpriteAnimTable_EggShard.as_ptr().cast::<u8>()),
    RomPtr(0x0 as *const u8),
    RomPtr((&raw const crate::sprite::gDummySpriteAffineAnimTable).cast::<u8>()),
    RomPtr(crate::egg_hatch::SpriteCB_EggShard as *const u8),
];

pub(crate) static sBgTemplates_EggHatch: RomBytes<8> = RomBytes([136, 7, 0, 0, 129, 34, 0, 0]);

pub(crate) static sWinTemplates_EggHatch: RomBytes<16> = RomBytes([0, 2, 15, 26, 4, 0, 64, 0, 255, 0, 0, 0, 0, 0, 0, 0]);

pub(crate) static sYesNoWinTemplate: RomBytes<8> = RomBytes([0, 21, 9, 5, 4, 15, 168, 1]);

pub(crate) static sEggShardVelocities: RomBytes<76> = RomBytes([128, 254, 64, 252, 0, 251, 0, 253, 128, 3, 0, 253, 0, 252, 64, 252, 0, 2, 128, 254, 128, 255, 64, 249, 0, 5, 192, 253, 128, 254, 64, 252, 128, 4, 128, 254, 0, 255, 64, 249, 0, 4, 192, 253, 128, 252, 64, 252, 0, 1, 128, 254, 124, 252, 64, 249, 128, 4, 192, 253, 128, 255, 128, 248, 0, 1, 128, 251, 128, 253, 192, 253, 128, 2, 128, 248]);

